import { ErrorCode, ValueTag, type CellValue } from "@bilig/protocol";

const protocolScalarPlaceholderBuiltinNames = [] as const;

const implementedScalarBuiltinNames = new Set<string>([
  "CONFIDENCE.NORM",
  "CONFIDENCE",
  "CHIDIST",
  "CHISQ.DIST",
  "CHISQ.DIST.RT",
  "DELTA",
  "EFFECT",
  "ERF",
  "ERF.PRECISE",
  "ERFC",
  "ERFC.PRECISE",
  "EXPON.DIST",
  "EXPONDIST",
  "FV",
  "GAUSS",
  "GAMMA",
  "GAMMA.DIST",
  "GAMMADIST",
  "GAMMALN",
  "GAMMALN.PRECISE",
  "GESTEP",
  "BINOMDIST",
  "BINOM.DIST",
  "BINOM.DIST.RANGE",
  "BINOM.INV",
  "BIN2DEC",
  "BIN2HEX",
  "BIN2OCT",
  "CELL",
  "COLUMN",
  "COMPLEX",
  "CRITBINOM",
  "DATEDIF",
  "DB",
  "DDB",
  "DEC2BIN",
  "DEC2HEX",
  "DEC2OCT",
  "FISHER",
  "FISHERINV",
  "FORMULATEXT",
  "FVSCHEDULE",
  "HEX2BIN",
  "HEX2DEC",
  "HEX2OCT",
  "HYPGEOM.DIST",
  "HYPGEOMDIST",
  "IMABS",
  "IMAGINARY",
  "IMARGUMENT",
  "IMCONJUGATE",
  "IMCOS",
  "IMCOSH",
  "IMCOT",
  "IMCSC",
  "IMCSCH",
  "IMDIV",
  "IMEXP",
  "IMLN",
  "IMLOG10",
  "IMLOG2",
  "IMPOWER",
  "IMPRODUCT",
  "IMREAL",
  "IMSEC",
  "IMSECH",
  "IMSIN",
  "IMSINH",
  "IMSQRT",
  "IMSUB",
  "IMSUM",
  "IMTAN",
  "IPMT",
  "ISOMITTED",
  "ISPMT",
  "KURT",
  "LENB",
  "LOGINV",
  "LEGACY.CHIDIST",
  "LEGACY.NORMSDIST",
  "LEGACY.NORMSINV",
  "LOGNORM.DIST",
  "LOGNORMDIST",
  "LOGNORM.INV",
  "MODE",
  "MODE.SNGL",
  "N",
  "NEGBINOM.DIST",
  "NEGBINOMDIST",
  "NOMINAL",
  "NORM.DIST",
  "NORMDIST",
  "NORM.INV",
  "NORMINV",
  "NORM.S.DIST",
  "NORM.S.INV",
  "NORMSDIST",
  "NORMSINV",
  "NUMBERVALUE",
  "NPER",
  "NPV",
  "OCT2BIN",
  "OCT2DEC",
  "OCT2HEX",
  "OFFSET",
  "PDURATION",
  "PERMUT",
  "PERMUTATIONA",
  "PHI",
  "POISSON",
  "POISSON.DIST",
  "PMT",
  "PPMT",
  "PV",
  "REGEXEXTRACT",
  "REGEXREPLACE",
  "REGEXTEST",
  "REPLACEB",
  "RRI",
  "DROP",
  "SORT",
  "SORTBY",
  "ROW",
  "SEARCHB",
  "SHEET",
  "SHEETS",
  "SLN",
  "SKEW",
  "SKEW.P",
  "SKEWP",
  "STANDARDIZE",
  "STDEV",
  "STDEV.P",
  "STDEV.S",
  "STDEVA",
  "STDEVP",
  "STDEVPA",
  "SYD",
  "TAKE",
  "T",
  "TOCOL",
  "TOROW",
  "TYPE",
  "VALUETOTEXT",
  "VAR",
  "VAR.P",
  "VAR.S",
  "VARA",
  "VARP",
  "VARPA",
  "VDB",
  "WEIBULL",
  "WEIBULL.DIST",
  "WORKDAY.INTL",
  "NETWORKDAYS.INTL",
  "WRAPCOLS",
  "WRAPROWS",
] as const);

const allAdditionalExcelScalarBuiltinNames = [
  "ASC",
  "BAHTTEXT",
  "BESSELI",
  "BESSELJ",
  "BESSELK",
  "BESSELY",
  "BETADIST",
  "BETA.DIST",
  "BETAINV",
  "BIN2DEC",
  "BIN2HEX",
  "BIN2OCT",
  "BINOMDIST",
  "BINOM.DIST",
  "BINOM.DIST.RANGE",
  "BINOM.INV",
  "CALL",
  "CELL",
  "CHIDIST",
  "CHIINV",
  "CHITEST",
  "CHISQ.DIST",
  "CHISQ.DIST.RT",
  "CHISQ.INV",
  "CHISQ.INV.RT",
  "CHISQ.TEST",
  "COLUMN",
  "COMPLEX",
  "CONFIDENCE",

  "CONFIDENCE.T",
  "CONVERT",
  "COPILOT",
  "COUPDAYBS",
  "COUPDAYS",
  "COUPDAYSNC",
  "COUPNCD",
  "COUPNUM",
  "COUPPCD",
  "CRITBINOM",
  "CUBEKPIMEMBER",
  "CUBEMEMBER",
  "CUBEMEMBERPROPERTY",
  "CUBERANKEDMEMBER",
  "CUBESET",
  "CUBESETCOUNT",
  "CUBEVALUE",
  "CUMIPMT",
  "CUMPRINC",
  "DATEDIF",
  "DAVERAGE",
  "DB",
  "DBCS",
  "DCOUNT",
  "DCOUNTA",
  "DDB",
  "DEC2BIN",
  "DEC2HEX",
  "DEC2OCT",
  "DETECTLANGUAGE",
  "DGET",
  "DISC",
  "DMAX",
  "DMIN",

  "DPRODUCT",
  "DROP",
  "DSTDEV",
  "DSTDEVP",
  "DSUM",
  "DURATION",
  "DVAR",
  "DVARP",
  "ERF",
  "ERF.PRECISE",
  "ERFC",
  "ERFC.PRECISE",
  "EUROCONVERT",
  "EXPAND",
  "EXPON.DIST",
  "EXPONDIST",
  "F.DIST",
  "FDIST",
  "F.DIST.RT",
  "FILTERXML",
  "F.INV",
  "F.INV.RT",
  "FINV",
  "FISHER",
  "FISHERINV",

  "FORECAST",
  "FORECAST.LINEAR",
  "FORECAST.ETS",
  "FORECAST.ETS.CONFINT",
  "FORECAST.ETS.SEASONALITY",
  "FORECAST.ETS.STAT",
  "FORMULATEXT",
  "FREQUENCY",
  "F.TEST",
  "FTEST",
  "FVSCHEDULE",
  "GAMMA",
  "GAMMA.DIST",
  "GAMMADIST",
  "GAMMA.INV",
  "GAMMAINV",
  "GAMMALN",
  "GAMMALN.PRECISE",

  "GETPIVOTDATA",
  "GROUPBY",
  "GROWTH",

  "HEX2BIN",
  "HEX2DEC",
  "HEX2OCT",
  "HYPERLINK",
  "HYPGEOM.DIST",
  "HYPGEOMDIST",
  "IMABS",
  "IMAGE",
  "IMAGINARY",
  "IMARGUMENT",
  "IMCONJUGATE",
  "IMCOS",
  "IMCOSH",
  "IMCOT",
  "IMCSC",
  "IMCSCH",
  "IMDIV",
  "IMEXP",
  "IMLN",
  "IMLOG10",
  "IMLOG2",
  "IMPOWER",
  "IMPRODUCT",
  "IMREAL",
  "IMSEC",
  "IMSECH",
  "IMSIN",
  "IMSINH",
  "IMSQRT",
  "IMSUB",
  "IMSUM",
  "IMTAN",
  "INDIRECT",
  "INFO",
  "INTERCEPT",
  "INTRATE",
  "IRR",
  "ISOMITTED",
  "JIS",

  "LINEST",
  "LOGEST",

  "MDURATION",
  "MIRR",

  "MODE.MULT",

  "NEGBINOM.DIST",
  "NEGBINOMDIST",
  "NETWORKDAYS.INTL",

  "NUMBERVALUE",
  "OCT2BIN",
  "OCT2DEC",
  "OCT2HEX",
  "ODDFPRICE",
  "ODDFYIELD",
  "ODDLPRICE",
  "ODDLYIELD",
  "OFFSET",

  "PERCENTILE.EXC",
  "PERCENTILE.INC",
  "PERCENTILE",
  "PERCENTRANK.EXC",
  "PERCENTRANK.INC",
  "PERCENTRANK",

  "PHONETIC",
  "PIVOTBY",

  "POISSON.DIST",
  "POISSON",

  "PRICE",
  "PRICEDISC",
  "PRICEMAT",
  "PROB",

  "QUARTILE",
  "QUARTILE.EXC",
  "QUARTILE.INC",
  "RANK.AVG",
  "RATE",
  "RECEIVED",
  "REGEXEXTRACT",
  "REGEXREPLACE",
  "REGEXTEST",
  "REGISTER.ID",
  "ROW",

  "RSQ",
  "RTD",
  "SHEET",
  "SHEETS",

  "SLN",
  "SLOPE",
  "SORT",
  "SORTBY",

  "STEYX",
  "STOCKHISTORY",
  "SYD",

  "TAKE",
  "TBILLEQ",
  "TBILLPRICE",
  "TBILLYIELD",
  "T.DIST",
  "T.DIST.2T",
  "T.DIST.RT",
  "TDIST",
  "TEXT",
  "TEXTSPLIT",
  "T.INV",
  "T.INV.2T",
  "TINV",
  "TOCOL",
  "TOROW",
  "TRANSLATE",
  "TREND",
  "TRIMMEAN",
  "TRIMRANGE",
  "T.TEST",
  "TTEST",

  "VALUETOTEXT",

  "VDB",
  "WEBSERVICE",
  "WEIBULL",
  "WEIBULL.DIST",
  "WORKDAY.INTL",
  "WRAPCOLS",
  "WRAPROWS",
  "XIRR",
  "XNPV",
  "YIELD",
  "YIELDDISC",
  "YIELDMAT",
  "Z.TEST",
  "ZTEST",
] as const;

const additionalExcelScalarPlaceholderBuiltinNames = allAdditionalExcelScalarBuiltinNames.filter(
  (name) => !implementedScalarBuiltinNames.has(name),
);

export const scalarPlaceholderBuiltinNames = [
  ...protocolScalarPlaceholderBuiltinNames,
  ...additionalExcelScalarPlaceholderBuiltinNames,
] as const;

export const logicalPlaceholderBuiltinNames = [] as const;

export const datetimePlaceholderBuiltinNames = [] as const;

export const textPlaceholderBuiltinNames = [] as const;

export const placeholderBuiltinNames = [
  ...scalarPlaceholderBuiltinNames,
  ...logicalPlaceholderBuiltinNames,
  ...datetimePlaceholderBuiltinNames,
  ...textPlaceholderBuiltinNames,
] as const;

export const protocolPlaceholderBuiltinNames = [
  ...protocolScalarPlaceholderBuiltinNames,
  ...logicalPlaceholderBuiltinNames,
  ...datetimePlaceholderBuiltinNames,
  ...textPlaceholderBuiltinNames,
] as const;

export type PlaceholderBuiltin = (...args: CellValue[]) => CellValue;

function blockedResult(): CellValue {
  return { tag: ValueTag.Error, code: ErrorCode.Blocked };
}

export function createBlockedBuiltin(): PlaceholderBuiltin {
  return () => blockedResult();
}

export function createBlockedBuiltinMap(
  names: readonly string[],
): Record<string, PlaceholderBuiltin> {
  return Object.fromEntries(names.map((name) => [name, createBlockedBuiltin()]));
}
