import { expect, test, type Page } from '@playwright/test'
import { createTestDocumentId, getBox, waitForWorkbookReady } from './web-shell-helpers.js'

async function selectRange(page: Page, address: string) {
  await page.getByTestId('name-box').fill(address)
  await page.getByTestId('name-box').press('Enter')
}

async function enterValue(page: Page, address: string, value: string) {
  await selectRange(page, address)
  await page.getByTestId('formula-input').fill(value)
  await page.getByTestId('formula-input').press('Enter')
}

test('@browser-ci long formulas expand during editing and collapse without losing text', async ({ page }) => {
  await page.goto(`/?document=${createTestDocumentId('formula-polish')}&sheet=Sheet1&cell=A1`)
  await waitForWorkbookReady(page)
  const input = page.getByTestId('formula-input')
  const frame = page.getByTestId('formula-input-frame')
  const value = '=SUM(\n1,\n2,\n3\n)'
  await input.fill(value)
  expect((await getBox(frame)).height).toBeGreaterThan(80)
  expect((await getBox(frame)).height).toBeLessThanOrEqual(162)
  await input.press('Enter')
  await expect(page.getByTestId('name-box')).toHaveValue('A1')
  await selectRange(page, 'A1')
  await expect(page.getByTestId('formula-resolved-value')).toHaveText('6')
  expect((await getBox(frame)).height).toBe(32)
  await expect(page.getByTestId('workbook-save-status')).toHaveText(/^(Saved on this device|Saved)$/)
  await page.reload()
  await waitForWorkbookReady(page)
  await expect(input).toHaveValue(value)
  await expect(page.getByTestId('formula-resolved-value')).toHaveText('6')
  await page.setViewportSize({ width: 320, height: 700 })
  await input.click()
  expect((await getBox(frame)).height).toBeGreaterThan(80)
  expect((await getBox(input)).width).toBeGreaterThan(160)
  await input.fill(`=SUM(\n${Array.from({ length: 30 }, () => '1').join(',\n')}\n)`)
  expect((await getBox(frame)).height).toBeLessThanOrEqual(160)
  await input.press('Escape')
  expect((await getBox(frame)).height).toBe(32)
  await expect(input).toHaveValue(value)
})

test('@browser-ci color palettes support arrow navigation and a single tab stop per grid', async ({ page }) => {
  await page.goto(`/?document=${createTestDocumentId('palette-polish')}&persist=0&sheet=Sheet1&cell=A1`)
  await waitForWorkbookReady(page)
  const trigger = page.getByLabel('Fill color', { exact: true })
  await trigger.click()
  const grid = page.getByRole('grid', { name: 'Fill color swatches', exact: true })
  await expect(grid).toBeVisible()
  await expect(grid.locator('button[tabindex="0"]')).toHaveCount(1)
  await expect(page.getByLabel('Fill color white', { exact: true })).toBeFocused()
  await page.keyboard.press('Home')
  await expect(page.getByLabel('Fill color black', { exact: true })).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByLabel('Fill color red berry', { exact: true })).toBeFocused()
  await page.keyboard.press('End')
  await expect(page.getByLabel('Fill color magenta', { exact: true })).toBeFocused()
  await page.keyboard.press('Control+End')
  await expect(page.getByLabel('Fill color dark magenta 3', { exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByLabel('Reset fill color')).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await trigger.press('Enter')
  await page.keyboard.press('Home')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('Enter')
  await expect(trigger).toHaveAttribute('data-current-color', '#ff0000')
  await expect(page.getByTestId('sheet-grid-focus-target')).toBeFocused()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByTestId('name-box')).toHaveValue('B1')
})

test('@browser-ci selection calculations include offscreen cells and preserve small values', async ({ page }) => {
  await page.goto(`/?document=${createTestDocumentId('summary-polish')}&sheet=Sheet1&cell=A1`)
  await waitForWorkbookReady(page)
  await enterValue(page, 'A1', '0.0004')
  await enterValue(page, 'A5000', '0.0006')
  await enterValue(page, 'A10000', '=SUM(A1,A5000)')
  await enterValue(page, 'B1', 'alpha')
  await enterValue(page, 'B10000', 'beta')
  await selectRange(page, 'A:A')
  const summary = page.getByRole('combobox', { name: 'Selection calculations' })
  await expect(summary).toHaveText('Sum: 0.002')
  await summary.click()
  await page.getByTestId('workbook-selection-status-option-min').click()
  await expect(summary).toHaveText('Min: 0.0004')
  await selectRange(page, 'B:B')
  await expect(summary).toHaveText('Count: 2')
  await selectRange(page, 'A:A')
  await expect(summary).toHaveText('Min: 0.0004')
  await expect(page.getByTestId('workbook-save-status')).toHaveText(/^(Saved on this device|Saved)$/)
  await page.reload()
  await waitForWorkbookReady(page)
  await selectRange(page, 'A:A')
  await expect(summary).toHaveText('Sum: 0.002')
  await enterValue(page, 'A5000', '0.0016')
  await selectRange(page, 'A:A')
  await expect(summary).toHaveText('Sum: 0.004')
  await selectRange(page, 'C:C')
  await expect(summary).toHaveCount(0)
  await expect(page.getByTestId('workbook-selection-summary')).toHaveText('C:C')
})
