export {
  init,
  ensureCellCapacity,
  ensureFormulaCapacity,
  ensureConstantCapacity,
  ensureRangeCapacity,
  ensureMemberCapacity,
  uploadPrograms,
  uploadConstants,
  uploadRangeMembers,
  uploadStringLengths,
  uploadStrings,
  writeCells,
  evalBatch,
  getTagsPtr,
  getNumbersPtr,
  getStringIdsPtr,
  getErrorsPtr,
  getProgramOffsetsPtr,
  getProgramLengthsPtr,
  getConstantOffsetsPtr,
  getConstantLengthsPtr,
  getConstantArenaPtr,
  getRangeOffsetsPtr,
  getRangeLengthsPtr,
  getRangeMembersPtr,
  getCellCapacity,
  getFormulaCapacity,
  getConstantCapacity,
  getRangeCapacity,
  getMemberCapacity
} from "./vm";

export {
  materializePivotTable,
  getPivotResultTagsPtr,
  getPivotResultNumbersPtr,
  getPivotResultStringIdsPtr,
  getPivotResultErrorsPtr,
  pivotResultRows,
  pivotResultCols
} from "./pivot";
