export {
  init,
  ensureCellCapacity,
  ensureFormulaCapacity,
  ensureConstantCapacity,
  ensureRangeCapacity,
  ensureMemberCapacity,
  uploadPrograms,
  uploadConstants,
  uploadRangeMembers,
  writeCells,
  evalBatch,
  getTagsPtr,
  getNumbersPtr,
  getStringIdsPtr,
  getErrorsPtr,
  getProgramOffsetsPtr,
  getProgramLengthsPtr,
  getRangeOffsetsPtr,
  getRangeLengthsPtr,
  getRangeMembersPtr,
  getCellCapacity,
  getFormulaCapacity,
  getConstantCapacity,
  getRangeCapacity,
  getMemberCapacity
} from "./vm";
