export {
  init,
  ensureCellCapacity,
  ensureFormulaCapacity,
  ensureConstantCapacity,
  ensureRangeCapacity,
  ensureMemberCapacity,
  uploadPrograms,
  uploadConstants,
  uploadRangeMembers,
  uploadRangeShapes,
  uploadVolatileNowSerial,
  uploadVolatileRandomValues,
  uploadStringLengths,
  uploadStrings,
  writeCells,
  evalBatch,
  getTagsPtr,
  getNumbersPtr,
  getStringIdsPtr,
  getErrorsPtr,
  getProgramOffsetsPtr,
  getProgramLengthsPtr,
  getConstantOffsetsPtr,
  getConstantLengthsPtr,
  getConstantArenaPtr,
  getRangeOffsetsPtr,
  getRangeLengthsPtr,
  getRangeMembersPtr,
  getOutputStringLengthsPtr,
  getOutputStringOffsetsPtr,
  getOutputStringDataPtr,
  getOutputStringCount,
  getOutputStringDataLength,
  getSpillResultRowsPtr,
  getSpillResultColsPtr,
  getSpillResultOffsetsPtr,
  getSpillResultLengthsPtr,
  getSpillResultNumbersPtr,
  getSpillResultValueCount,
  getCellCapacity,
  getFormulaCapacity,
  getConstantCapacity,
  getRangeCapacity,
  getMemberCapacity
} from "./vm";

export {
  materializePivotTable,
  getPivotResultTagsPtr,
  getPivotResultNumbersPtr,
  getPivotResultStringIdsPtr,
  getPivotResultErrorsPtr,
  pivotResultRows,
  pivotResultCols
} from "./pivot";
