export const WORKBOOK_AGENT_TOOL_NAMES = {
  getContext: "get_context",
  readWorkbook: "read_workbook",
  listSheets: "list_sheets",
  getSheetView: "get_sheet_view",
  getUsedRange: "get_used_range",
  getCurrentRegion: "get_current_region",
  listNamedRanges: "list_named_ranges",
  listTables: "list_tables",
  listPivots: "list_pivots",
  readRange: "read_range",
  readSelection: "read_selection",
  readVisibleRange: "read_visible_range",
  readRecentChanges: "read_recent_changes",
  startWorkflow: "start_workflow",
  inspectCell: "inspect_cell",
  findFormulaIssues: "find_formula_issues",
  searchWorkbook: "search_workbook",
  traceDependencies: "trace_dependencies",
  setFormula: "set_formula",
  getRowMetadata: "get_row_metadata",
  getColumnMetadata: "get_column_metadata",
  writeRange: "write_range",
  clearRange: "clear_range",
  formatRange: "format_range",
  fillRange: "fill_range",
  copyRange: "copy_range",
  moveRange: "move_range",
  createSheet: "create_sheet",
  renameSheet: "rename_sheet",
  deleteSheet: "delete_sheet",
  insertRows: "insert_rows",
  deleteRows: "delete_rows",
  insertColumns: "insert_columns",
  deleteColumns: "delete_columns",
  setFreezePane: "set_freeze_pane",
  setFilter: "set_filter",
  clearFilter: "clear_filter",
  setSort: "set_sort",
  clearSort: "clear_sort",
  updateRowMetadata: "update_row_metadata",
  updateColumnMetadata: "update_column_metadata",
  createNamedRange: "create_named_range",
  updateNamedRange: "update_named_range",
  deleteNamedRange: "delete_named_range",
  createTable: "create_table",
  resizeTable: "resize_table",
  deleteTable: "delete_table",
  createPivotTable: "create_pivot_table",
  updatePivotTable: "update_pivot_table",
  deletePivotTable: "delete_pivot_table",
} as const;

export type WorkbookAgentToolName =
  (typeof WORKBOOK_AGENT_TOOL_NAMES)[keyof typeof WORKBOOK_AGENT_TOOL_NAMES];

const LEGACY_WORKBOOK_AGENT_TOOL_NAME_MAP: Record<string, WorkbookAgentToolName> = {
  bilig_get_context: WORKBOOK_AGENT_TOOL_NAMES.getContext,
  "bilig.get_context": WORKBOOK_AGENT_TOOL_NAMES.getContext,
  bilig_read_workbook: WORKBOOK_AGENT_TOOL_NAMES.readWorkbook,
  "bilig.read_workbook": WORKBOOK_AGENT_TOOL_NAMES.readWorkbook,
  bilig_list_sheets: WORKBOOK_AGENT_TOOL_NAMES.listSheets,
  "bilig.list_sheets": WORKBOOK_AGENT_TOOL_NAMES.listSheets,
  bilig_get_sheet_view: WORKBOOK_AGENT_TOOL_NAMES.getSheetView,
  "bilig.get_sheet_view": WORKBOOK_AGENT_TOOL_NAMES.getSheetView,
  bilig_get_used_range: WORKBOOK_AGENT_TOOL_NAMES.getUsedRange,
  "bilig.get_used_range": WORKBOOK_AGENT_TOOL_NAMES.getUsedRange,
  bilig_get_current_region: WORKBOOK_AGENT_TOOL_NAMES.getCurrentRegion,
  "bilig.get_current_region": WORKBOOK_AGENT_TOOL_NAMES.getCurrentRegion,
  bilig_list_named_ranges: WORKBOOK_AGENT_TOOL_NAMES.listNamedRanges,
  "bilig.list_named_ranges": WORKBOOK_AGENT_TOOL_NAMES.listNamedRanges,
  bilig_list_tables: WORKBOOK_AGENT_TOOL_NAMES.listTables,
  "bilig.list_tables": WORKBOOK_AGENT_TOOL_NAMES.listTables,
  bilig_list_pivots: WORKBOOK_AGENT_TOOL_NAMES.listPivots,
  "bilig.list_pivots": WORKBOOK_AGENT_TOOL_NAMES.listPivots,
  bilig_read_range: WORKBOOK_AGENT_TOOL_NAMES.readRange,
  "bilig.read_range": WORKBOOK_AGENT_TOOL_NAMES.readRange,
  bilig_read_selection: WORKBOOK_AGENT_TOOL_NAMES.readSelection,
  "bilig.read_selection": WORKBOOK_AGENT_TOOL_NAMES.readSelection,
  bilig_read_visible_range: WORKBOOK_AGENT_TOOL_NAMES.readVisibleRange,
  "bilig.read_visible_range": WORKBOOK_AGENT_TOOL_NAMES.readVisibleRange,
  bilig_read_recent_changes: WORKBOOK_AGENT_TOOL_NAMES.readRecentChanges,
  "bilig.read_recent_changes": WORKBOOK_AGENT_TOOL_NAMES.readRecentChanges,
  bilig_start_workflow: WORKBOOK_AGENT_TOOL_NAMES.startWorkflow,
  "bilig.start_workflow": WORKBOOK_AGENT_TOOL_NAMES.startWorkflow,
  bilig_inspect_cell: WORKBOOK_AGENT_TOOL_NAMES.inspectCell,
  "bilig.inspect_cell": WORKBOOK_AGENT_TOOL_NAMES.inspectCell,
  bilig_find_formula_issues: WORKBOOK_AGENT_TOOL_NAMES.findFormulaIssues,
  "bilig.find_formula_issues": WORKBOOK_AGENT_TOOL_NAMES.findFormulaIssues,
  bilig_search_workbook: WORKBOOK_AGENT_TOOL_NAMES.searchWorkbook,
  "bilig.search_workbook": WORKBOOK_AGENT_TOOL_NAMES.searchWorkbook,
  bilig_trace_dependencies: WORKBOOK_AGENT_TOOL_NAMES.traceDependencies,
  "bilig.trace_dependencies": WORKBOOK_AGENT_TOOL_NAMES.traceDependencies,
  bilig_set_formula: WORKBOOK_AGENT_TOOL_NAMES.setFormula,
  "bilig.set_formula": WORKBOOK_AGENT_TOOL_NAMES.setFormula,
  bilig_get_row_metadata: WORKBOOK_AGENT_TOOL_NAMES.getRowMetadata,
  "bilig.get_row_metadata": WORKBOOK_AGENT_TOOL_NAMES.getRowMetadata,
  bilig_get_column_metadata: WORKBOOK_AGENT_TOOL_NAMES.getColumnMetadata,
  "bilig.get_column_metadata": WORKBOOK_AGENT_TOOL_NAMES.getColumnMetadata,
  bilig_write_range: WORKBOOK_AGENT_TOOL_NAMES.writeRange,
  "bilig.write_range": WORKBOOK_AGENT_TOOL_NAMES.writeRange,
  bilig_clear_range: WORKBOOK_AGENT_TOOL_NAMES.clearRange,
  "bilig.clear_range": WORKBOOK_AGENT_TOOL_NAMES.clearRange,
  bilig_format_range: WORKBOOK_AGENT_TOOL_NAMES.formatRange,
  "bilig.format_range": WORKBOOK_AGENT_TOOL_NAMES.formatRange,
  bilig_fill_range: WORKBOOK_AGENT_TOOL_NAMES.fillRange,
  "bilig.fill_range": WORKBOOK_AGENT_TOOL_NAMES.fillRange,
  bilig_copy_range: WORKBOOK_AGENT_TOOL_NAMES.copyRange,
  "bilig.copy_range": WORKBOOK_AGENT_TOOL_NAMES.copyRange,
  bilig_move_range: WORKBOOK_AGENT_TOOL_NAMES.moveRange,
  "bilig.move_range": WORKBOOK_AGENT_TOOL_NAMES.moveRange,
  bilig_create_sheet: WORKBOOK_AGENT_TOOL_NAMES.createSheet,
  "bilig.create_sheet": WORKBOOK_AGENT_TOOL_NAMES.createSheet,
  bilig_rename_sheet: WORKBOOK_AGENT_TOOL_NAMES.renameSheet,
  "bilig.rename_sheet": WORKBOOK_AGENT_TOOL_NAMES.renameSheet,
  bilig_delete_sheet: WORKBOOK_AGENT_TOOL_NAMES.deleteSheet,
  "bilig.delete_sheet": WORKBOOK_AGENT_TOOL_NAMES.deleteSheet,
  bilig_insert_rows: WORKBOOK_AGENT_TOOL_NAMES.insertRows,
  "bilig.insert_rows": WORKBOOK_AGENT_TOOL_NAMES.insertRows,
  bilig_delete_rows: WORKBOOK_AGENT_TOOL_NAMES.deleteRows,
  "bilig.delete_rows": WORKBOOK_AGENT_TOOL_NAMES.deleteRows,
  bilig_insert_columns: WORKBOOK_AGENT_TOOL_NAMES.insertColumns,
  "bilig.insert_columns": WORKBOOK_AGENT_TOOL_NAMES.insertColumns,
  bilig_delete_columns: WORKBOOK_AGENT_TOOL_NAMES.deleteColumns,
  "bilig.delete_columns": WORKBOOK_AGENT_TOOL_NAMES.deleteColumns,
  bilig_set_freeze_pane: WORKBOOK_AGENT_TOOL_NAMES.setFreezePane,
  "bilig.set_freeze_pane": WORKBOOK_AGENT_TOOL_NAMES.setFreezePane,
  bilig_set_filter: WORKBOOK_AGENT_TOOL_NAMES.setFilter,
  "bilig.set_filter": WORKBOOK_AGENT_TOOL_NAMES.setFilter,
  bilig_clear_filter: WORKBOOK_AGENT_TOOL_NAMES.clearFilter,
  "bilig.clear_filter": WORKBOOK_AGENT_TOOL_NAMES.clearFilter,
  bilig_set_sort: WORKBOOK_AGENT_TOOL_NAMES.setSort,
  "bilig.set_sort": WORKBOOK_AGENT_TOOL_NAMES.setSort,
  bilig_clear_sort: WORKBOOK_AGENT_TOOL_NAMES.clearSort,
  "bilig.clear_sort": WORKBOOK_AGENT_TOOL_NAMES.clearSort,
  bilig_update_row_metadata: WORKBOOK_AGENT_TOOL_NAMES.updateRowMetadata,
  "bilig.update_row_metadata": WORKBOOK_AGENT_TOOL_NAMES.updateRowMetadata,
  bilig_update_column_metadata: WORKBOOK_AGENT_TOOL_NAMES.updateColumnMetadata,
  "bilig.update_column_metadata": WORKBOOK_AGENT_TOOL_NAMES.updateColumnMetadata,
  bilig_create_named_range: WORKBOOK_AGENT_TOOL_NAMES.createNamedRange,
  "bilig.create_named_range": WORKBOOK_AGENT_TOOL_NAMES.createNamedRange,
  bilig_update_named_range: WORKBOOK_AGENT_TOOL_NAMES.updateNamedRange,
  "bilig.update_named_range": WORKBOOK_AGENT_TOOL_NAMES.updateNamedRange,
  bilig_delete_named_range: WORKBOOK_AGENT_TOOL_NAMES.deleteNamedRange,
  "bilig.delete_named_range": WORKBOOK_AGENT_TOOL_NAMES.deleteNamedRange,
  bilig_create_table: WORKBOOK_AGENT_TOOL_NAMES.createTable,
  "bilig.create_table": WORKBOOK_AGENT_TOOL_NAMES.createTable,
  bilig_resize_table: WORKBOOK_AGENT_TOOL_NAMES.resizeTable,
  "bilig.resize_table": WORKBOOK_AGENT_TOOL_NAMES.resizeTable,
  bilig_delete_table: WORKBOOK_AGENT_TOOL_NAMES.deleteTable,
  "bilig.delete_table": WORKBOOK_AGENT_TOOL_NAMES.deleteTable,
  bilig_create_pivot_table: WORKBOOK_AGENT_TOOL_NAMES.createPivotTable,
  "bilig.create_pivot_table": WORKBOOK_AGENT_TOOL_NAMES.createPivotTable,
  bilig_update_pivot_table: WORKBOOK_AGENT_TOOL_NAMES.updatePivotTable,
  "bilig.update_pivot_table": WORKBOOK_AGENT_TOOL_NAMES.updatePivotTable,
  bilig_delete_pivot_table: WORKBOOK_AGENT_TOOL_NAMES.deletePivotTable,
  "bilig.delete_pivot_table": WORKBOOK_AGENT_TOOL_NAMES.deletePivotTable,
};

const workbookAgentToolNameSet = new Set<string>(Object.values(WORKBOOK_AGENT_TOOL_NAMES));

export function normalizeWorkbookAgentToolName(toolName: string): string {
  return LEGACY_WORKBOOK_AGENT_TOOL_NAME_MAP[toolName] ?? toolName;
}

export function isWorkbookAgentToolName(toolName: string): toolName is WorkbookAgentToolName {
  return workbookAgentToolNameSet.has(normalizeWorkbookAgentToolName(toolName));
}
