import { ErrorCode } from '@bilig/protocol'
import type {
  ExcelExpectedValue,
  ExcelFixtureCase,
  ExcelFixtureFamily,
  ExcelFixtureExpectedOutput,
  ExcelFixtureInputCell,
} from './index.js'

const excelFixtureIdPattern = /^[a-z][a-z0-9-]*:[a-z0-9-]+$/

function createExcelFixtureId(family: ExcelFixtureFamily, slug: string): string {
  const normalizedSlug = slug.trim().toLowerCase()
  const id = `${family}:${normalizedSlug}`
  if (!excelFixtureIdPattern.test(id)) {
    throw new Error(`Invalid Excel fixture id: ${id}`)
  }
  return id
}

function numberExpected(value: number): ExcelExpectedValue {
  return { kind: 'number', value }
}

function booleanExpected(value: boolean): ExcelExpectedValue {
  return { kind: 'boolean', value }
}

function stringExpected(value: string): ExcelExpectedValue {
  return { kind: 'string', value }
}

function errorExpected(code: ErrorCode, display: string): ExcelExpectedValue {
  return { kind: 'error', code, display }
}

function input(address: string, value: ExcelFixtureInputCell['input'], note?: string): ExcelFixtureInputCell {
  return note === undefined ? { address, input: value } : { address, input: value, note }
}

function output(address: string, expected: ExcelFixtureExpectedOutput['expected'], note?: string): ExcelFixtureExpectedOutput {
  return note === undefined ? { address, expected } : { address, expected, note }
}

function fixture(
  family: ExcelFixtureFamily,
  slug: string,
  title: string,
  formula: string,
  inputs: ExcelFixtureInputCell[],
  outputs: ExcelFixtureExpectedOutput[],
  notes?: string,
): ExcelFixtureCase {
  const base = {
    id: createExcelFixtureId(family, slug),
    family,
    title,
    formula,
    inputs,
    outputs,
    sheetName: 'Sheet1',
  }
  return notes === undefined ? base : { ...base, notes }
}

export const canonicalFoundationFixtures: ExcelFixtureCase[] = [
  fixture('arithmetic', 'add-basic', 'Addition', '=A1+A2', [input('A1', 2), input('A2', 5)], [output('A3', numberExpected(7))]),
  fixture(
    'arithmetic',
    'precedence-basic',
    'Operator precedence',
    '=A1+A2*A3',
    [input('A1', 2), input('A2', 3), input('A3', 4)],
    [output('A4', numberExpected(14))],
  ),
  fixture('arithmetic', 'unary-negation', 'Unary negation', '=-A1', [input('A1', 9)], [output('A2', numberExpected(-9))]),
  fixture('arithmetic', 'division-basic', 'Division', '=A1/A2', [input('A1', 12), input('A2', 3)], [output('A3', numberExpected(4))]),
  fixture('arithmetic', 'power-basic', 'Exponentiation', '=A1^A2', [input('A1', 2), input('A2', 3)], [output('A3', numberExpected(8))]),
  fixture(
    'arithmetic',
    'percent-operator',
    'Percent postfix operator',
    '=A1*10%',
    [input('A1', 50)],
    [output('A2', numberExpected(5))],
    'Tracks unsupported postfix percent grammar until parity lands.',
  ),
  fixture(
    'comparison',
    'equality-number',
    'Numeric equality',
    '=A1=A2',
    [input('A1', 7), input('A2', 7)],
    [output('A3', booleanExpected(true))],
  ),
  fixture('comparison', 'equality-text', 'Case-insensitive text equality', '="hello"="HELLO"', [], [output('A1', booleanExpected(true))]),
  fixture('comparison', 'greater-than', 'Greater-than', '=A1>A2', [input('A1', 9), input('A2', 4)], [output('A3', booleanExpected(true))]),
  fixture(
    'comparison',
    'less-than-or-equal',
    'Less-than-or-equal',
    '=A1<=A2',
    [input('A1', 4), input('A2', 4)],
    [output('A3', booleanExpected(true))],
  ),
  fixture('logical', 'if-basic', 'IF true branch', '=IF(A1>0,"yes","no")', [input('A1', 3)], [output('A2', stringExpected('yes'))]),
  fixture('logical', 'and-basic', 'AND', '=AND(A1,A2)', [input('A1', true), input('A2', true)], [output('A3', booleanExpected(true))]),
  fixture('logical', 'or-basic', 'OR', '=OR(A1,A2)', [input('A1', false), input('A2', true)], [output('A3', booleanExpected(true))]),
  fixture('logical', 'not-basic', 'NOT', '=NOT(A1)', [input('A1', false)], [output('A2', booleanExpected(true))]),
  fixture(
    'logical',
    'ifs-basic',
    'IFS returns the first matching branch',
    '=IFS(A1>1,"big",TRUE(),"small")',
    [input('A1', 1)],
    [output('A2', stringExpected('small'))],
  ),
  fixture(
    'logical',
    'switch-basic',
    'SWITCH matches an exact case',
    '=SWITCH(A1,1,"one","other")',
    [input('A1', 1)],
    [output('A2', stringExpected('one'))],
  ),
  fixture(
    'logical',
    'xor-basic',
    'XOR returns true only for odd logical parity',
    '=XOR(TRUE(),FALSE(),TRUE())',
    [],
    [output('A1', booleanExpected(false))],
  ),
  fixture(
    'aggregation',
    'sum-range',
    'SUM over range',
    '=SUM(A1:A3)',
    [input('A1', 2), input('A2', 3), input('A3', 4)],
    [output('A4', numberExpected(9))],
  ),
  fixture(
    'aggregation',
    'avg-range',
    'AVG over range',
    '=AVG(A1:A3)',
    [input('A1', 2), input('A2', 4), input('A3', 6)],
    [output('A4', numberExpected(4))],
  ),
  fixture(
    'aggregation',
    'min-range',
    'MIN over range',
    '=MIN(A1:A3)',
    [input('A1', 8), input('A2', 2), input('A3', 5)],
    [output('A4', numberExpected(2))],
  ),
  fixture(
    'aggregation',
    'max-range',
    'MAX over range',
    '=MAX(A1:A3)',
    [input('A1', 8), input('A2', 2), input('A3', 5)],
    [output('A4', numberExpected(8))],
  ),
  fixture(
    'aggregation',
    'count-range',
    'COUNT over range',
    '=COUNT(A1:A4)',
    [input('A1', 8), input('A2', 2), input('A3', null), input('A4', 'x')],
    [output('A5', numberExpected(2))],
  ),
  fixture(
    'aggregation',
    'counta-range',
    'COUNTA over range',
    '=COUNTA(A1:A4)',
    [input('A1', 8), input('A2', 2), input('A3', null), input('A4', 'x')],
    [output('A5', numberExpected(3))],
  ),
  fixture(
    'aggregation',
    'countblank-range',
    'COUNTBLANK over range',
    '=COUNTBLANK(A1:A4)',
    [input('A1', 8), input('A2', null), input('A3', null), input('A4', 'x')],
    [output('A5', numberExpected(2))],
  ),
  fixture('math', 'abs-basic', 'ABS', '=ABS(A1)', [input('A1', -7)], [output('A2', numberExpected(7))]),
  fixture('math', 'round-basic', 'ROUND', '=ROUND(A1,1)', [input('A1', 3.125)], [output('A2', numberExpected(3.1))]),
  fixture('math', 'trunc-basic', 'TRUNC', '=TRUNC(A1,1)', [input('A1', -3.98)], [output('A2', numberExpected(-3.9))]),
  fixture('math', 'floor-math-basic', 'FLOOR.MATH', '=FLOOR.MATH(A1,2)', [input('A1', -5.5)], [output('A2', numberExpected(-6))]),
  fixture('math', 'floor-precise-basic', 'FLOOR.PRECISE', '=FLOOR.PRECISE(A1,2)', [input('A1', -5.5)], [output('A2', numberExpected(-6))]),
  fixture('math', 'ceiling-math-basic', 'CEILING.MATH', '=CEILING.MATH(A1,2)', [input('A1', -5.5)], [output('A2', numberExpected(-4))]),
  fixture(
    'math',
    'ceiling-precise-basic',
    'CEILING.PRECISE',
    '=CEILING.PRECISE(A1,2)',
    [input('A1', -5.5)],
    [output('A2', numberExpected(-4))],
  ),
  fixture('math', 'iso-ceiling-basic', 'ISO.CEILING', '=ISO.CEILING(A1,2)', [input('A1', -5.5)], [output('A2', numberExpected(-4))]),
  fixture('math', 'mround-basic', 'MROUND', '=MROUND(A1,4)', [input('A1', 10)], [output('A2', numberExpected(12))]),
  fixture('math', 'seriessum-basic', 'SERIESSUM', '=SERIESSUM(2,1,2,1,2)', [], [output('A1', numberExpected(18))]),
  fixture('math', 'sqrtpi-basic', 'SQRTPI', '=SQRTPI(A1)', [input('A1', 2)], [output('A2', numberExpected(2.5066282746310002))]),
  fixture('math', 'floor-basic', 'FLOOR', '=FLOOR(A1,2)', [input('A1', 7)], [output('A2', numberExpected(6))]),
  fixture('math', 'ceiling-basic', 'CEILING', '=CEILING(A1,2)', [input('A1', 7)], [output('A2', numberExpected(8))]),
  fixture('math', 'mod-basic', 'MOD', '=MOD(A1,A2)', [input('A1', 10), input('A2', 3)], [output('A3', numberExpected(1))]),
  fixture('math', 'bitand-basic', 'BITAND', '=BITAND(6,3)', [], [output('A1', numberExpected(2))]),
  fixture('math', 'base-basic', 'BASE', '=BASE(255,16,4)', [], [output('A1', stringExpected('00FF'))]),
  fixture('math', 'decimal-basic', 'DECIMAL', '=DECIMAL("00FF",16)', [], [output('A1', numberExpected(255))]),
  fixture('math', 'bin2dec-basic', 'BIN2DEC', '=BIN2DEC("1111111111")', [], [output('A1', numberExpected(-1))]),
  fixture('math', 'dec2bin-basic', 'DEC2BIN', '=DEC2BIN(10,8)', [], [output('A1', stringExpected('00001010'))]),
  fixture('math', 'oct2hex-basic', 'OCT2HEX', '=OCT2HEX("17",4)', [], [output('A1', stringExpected('000F'))]),
  fixture('math', 'besseli-basic', 'BESSELI', '=BESSELI(1.5,1)', [], [output('A1', numberExpected(0.981666428))]),
  fixture('math', 'besselj-basic', 'BESSELJ', '=BESSELJ(1.9,2)', [], [output('A1', numberExpected(0.329925728))]),
  fixture('math', 'besselk-basic', 'BESSELK', '=BESSELK(1.5,1)', [], [output('A1', numberExpected(0.277387804))]),
  fixture('math', 'bessely-basic', 'BESSELY', '=BESSELY(2.5,1)', [], [output('A1', numberExpected(0.145918138))]),
  fixture('math', 'convert-basic', 'CONVERT miles to kilometers', '=CONVERT(6,"mi","km")', [], [output('A1', numberExpected(9.656064))]),
  fixture(
    'math',
    'euroconvert-basic',
    'EUROCONVERT triangulation',
    '=EUROCONVERT(1,"FRF","DEM",TRUE,3)',
    [],
    [output('A1', numberExpected(0.29728616))],
  ),
  fixture('math', 'acosh-basic', 'ACOSH', '=ACOSH(1)', [], [output('A1', numberExpected(0))]),
  fixture('math', 'fact-basic', 'FACT', '=FACT(5)', [], [output('A1', numberExpected(120))]),
  fixture('math', 'combin-basic', 'COMBIN', '=COMBIN(8,3)', [], [output('A1', numberExpected(56))]),
  fixture('math', 'permut-basic', 'PERMUT', '=PERMUT(5,3)', [], [output('A1', numberExpected(60))]),
  fixture('math', 'permutationa-basic', 'PERMUTATIONA', '=PERMUTATIONA(2,3)', [], [output('A1', numberExpected(8))]),
  fixture('math', 'gcd-basic', 'GCD', '=GCD(A1:A3)', [input('A1', 2), input('A2', 3), input('A3', 4)], [output('A4', numberExpected(1))]),
  fixture(
    'math',
    'product-basic',
    'PRODUCT',
    '=PRODUCT(A1:A3)',
    [input('A1', 2), input('A2', 3), input('A3', 4)],
    [output('A4', numberExpected(24))],
  ),
  fixture(
    'math',
    'geomean-basic',
    'GEOMEAN',
    '=GEOMEAN(A1:A3)',
    [input('A1', 2), input('A2', 3), input('A3', 4)],
    [output('A4', numberExpected(2.8844991406148166))],
  ),
  fixture(
    'math',
    'harmean-basic',
    'HARMEAN',
    '=HARMEAN(A1:A3)',
    [input('A1', 2), input('A2', 3), input('A3', 4)],
    [output('A4', numberExpected(2.769230769230769))],
  ),
  fixture(
    'math',
    'sumsq-basic',
    'SUMSQ',
    '=SUMSQ(A1:A3)',
    [input('A1', 2), input('A2', 3), input('A3', 4)],
    [output('A4', numberExpected(29))],
  ),
  fixture('text', 'concat-operator', 'Concatenation operator', '="bi"&"lig"', [], [output('A1', stringExpected('bilig'))]),
  fixture('text', 'concat-function', 'CONCAT function', '=CONCAT("bi","lig")', [], [output('A1', stringExpected('bilig'))]),
  fixture('text', 'len-basic', 'LEN', '=LEN("bilig")', [], [output('A1', numberExpected(5))]),
  fixture('text', 'char-basic', 'CHAR', '=CHAR(65)', [], [output('A1', stringExpected('A'))]),
  fixture('text', 'code-basic', 'CODE', '=CODE("A")', [], [output('A1', numberExpected(65))]),
  fixture('text', 'clean-basic', 'CLEAN', '=CLEAN(CHAR(97)&CHAR(1)&CHAR(98))', [], [output('A1', stringExpected('ab'))]),
  fixture('text', 'unichar-basic', 'UNICHAR', '=UNICHAR(66)', [], [output('A1', stringExpected('B'))]),
  fixture('text', 'dollar-basic', 'DOLLAR formatting', '=DOLLAR(-1234.5,1)', [], [output('A1', stringExpected('-$1,234.5'))]),
  fixture('text', 'text-basic', 'TEXT numeric formatting', '=TEXT(1234.567,"#,##0.00")', [], [output('A1', stringExpected('1,234.57'))]),
  fixture(
    'text',
    'text-date-basic',
    'TEXT date formatting',
    '=TEXT(DATE(2024,3,5),"yyyy-mm-dd")',
    [],
    [output('A1', stringExpected('2024-03-05'))],
  ),
  fixture('text', 'phonetic-basic', 'PHONETIC', '=PHONETIC("カタカナ")', [], [output('A1', stringExpected('カタカナ'))]),
  fixture('text', 'bahttext-basic', 'BAHTTEXT', '=BAHTTEXT(1234)', [], [output('A1', stringExpected('หนึ่งพันสองร้อยสามสิบสี่บาทถ้วน'))]),
  fixture('information', 't-basic', 'T', '=T("alpha")', [], [output('A1', stringExpected('alpha'))]),
  fixture('information', 'n-basic', 'N', '=N(TRUE())', [], [output('A1', numberExpected(1))]),
  fixture('information', 'type-basic', 'TYPE', '=TYPE("alpha")', [], [output('A1', numberExpected(2))]),
  fixture('math', 'delta-basic', 'DELTA', '=DELTA(4,4)', [], [output('A1', numberExpected(1))]),
  fixture('math', 'gestep-basic', 'GESTEP', '=GESTEP(-1)', [], [output('A1', numberExpected(0))]),
  fixture('statistical', 'gauss-basic', 'GAUSS', '=GAUSS(0)', [], [output('A1', numberExpected(0))]),
  fixture('statistical', 'phi-basic', 'PHI', '=PHI(0)', [], [output('A1', numberExpected(0.3989422804014327))]),
  fixture('text', 'case-insensitive-compare', 'Text compare semantics', '="a"="A"', [], [output('A1', booleanExpected(true))]),
  fixture(
    'date-time',
    'serial-addition',
    'Date serial addition',
    '=A1+7',
    [input('A1', 45292)],
    [output('A2', numberExpected(45299))],
    'Uses raw serials so the oracle stays stable across locale formatting.',
  ),
  fixture(
    'date-time',
    'date-constructor',
    'DATE constructor',
    '=DATE(2026,3,15)',
    [],
    [output('A1', numberExpected(46096))],
    'Committed oracle result captured from Excel for the web.',
  ),
  fixture(
    'date-time',
    'today-volatile',
    'TODAY volatile function',
    '=TODAY()',
    [],
    [output('A1', numberExpected(46100))],
    'Captured output is pinned to the current Excel-for-web oracle timestamp rather than treated as timeless.',
  ),
  fixture(
    'lookup-reference',
    'choose-basic',
    'CHOOSE selects the indexed argument',
    '=CHOOSE(2,"red","blue","green")',
    [],
    [output('A1', stringExpected('blue'))],
  ),
  fixture(
    'lookup-reference',
    'address-basic',
    'ADDRESS default A1 reference',
    '=ADDRESS(12,3)',
    [],
    [output('A1', stringExpected('$C$12'))],
  ),
  fixture(
    'lookup-reference',
    'index-basic',
    'INDEX exact cell lookup',
    '=INDEX(A1:B2,2,1)',
    [input('A1', 10), input('B1', 20), input('A2', 30), input('B2', 40)],
    [output('C1', numberExpected(30))],
  ),
  fixture(
    'lookup-reference',
    'match-exact',
    'MATCH exact',
    '=MATCH("pear",A1:A3,0)',
    [input('A1', 'apple'), input('A2', 'pear'), input('A3', 'plum')],
    [output('A4', numberExpected(2))],
  ),
  fixture(
    'lookup-reference',
    'vlookup-exact',
    'VLOOKUP exact',
    '=VLOOKUP("pear",A1:B3,2,FALSE)',
    [input('A1', 'apple'), input('B1', 10), input('A2', 'pear'), input('B2', 20), input('A3', 'plum'), input('B3', 30)],
    [output('C1', numberExpected(20))],
  ),
  fixture(
    'lookup-reference',
    'xlookup-exact',
    'XLOOKUP exact',
    '=XLOOKUP("pear",A1:A3,B1:B3)',
    [input('A1', 'apple'), input('B1', 10), input('A2', 'pear'), input('B2', 20), input('A3', 'plum'), input('B3', 30)],
    [output('C1', numberExpected(20))],
  ),
  fixture(
    'statistical',
    'averageif-basic',
    'AVERAGEIF',
    '=AVERAGEIF(A1:A4,">0")',
    [input('A1', 2), input('A2', 4), input('A3', -1), input('A4', 6)],
    [output('A5', numberExpected(4))],
  ),
  fixture(
    'statistical',
    'countif-basic',
    'COUNTIF',
    '=COUNTIF(A1:A4,">0")',
    [input('A1', 2), input('A2', 4), input('A3', -1), input('A4', 6)],
    [output('A5', numberExpected(3))],
  ),
  fixture(
    'statistical',
    'chisqdist-basic',
    'CHISQDIST legacy right-tail probability',
    '=CHISQDIST(18.307,10)',
    [],
    [output('A1', numberExpected(0.05000058909139826))],
  ),
  fixture(
    'statistical',
    'chiinv-basic',
    'CHIINV legacy right-tail inverse',
    '=CHIINV(0.050001,10)',
    [],
    [output('A1', numberExpected(18.30697345696106))],
  ),
  fixture(
    'statistical',
    'chisq-inv-rt-basic',
    'CHISQ.INV.RT right-tail inverse',
    '=CHISQ.INV.RT(0.050001,10)',
    [],
    [output('A1', numberExpected(18.30697345696106))],
  ),
  fixture(
    'statistical',
    'chisqinv-basic',
    'CHISQINV legacy right-tail inverse',
    '=CHISQINV(0.050001,10)',
    [],
    [output('A1', numberExpected(18.30697345696106))],
  ),
  fixture(
    'statistical',
    'chisq-inv-basic',
    'CHISQ.INV left-tail inverse',
    '=CHISQ.INV(0.93,1)',
    [],
    [output('A1', numberExpected(3.2830202867594993))],
  ),
  fixture(
    'statistical',
    'chisq-test-basic',
    'CHISQ.TEST independence test',
    '=CHISQ.TEST(A1:B3,D1:E3)',
    [
      input('A1', 58),
      input('B1', 35),
      input('A2', 11),
      input('B2', 25),
      input('A3', 10),
      input('B3', 23),
      input('D1', 45.35),
      input('E1', 47.65),
      input('D2', 17.56),
      input('E2', 18.44),
      input('D3', 16.09),
      input('E3', 16.91),
    ],
    [output('G1', numberExpected(0.0003082))],
  ),
  fixture(
    'statistical',
    'beta-dist-basic',
    'BETA.DIST cumulative',
    '=BETA.DIST(2,8,10,TRUE,1,3)',
    [],
    [output('A1', numberExpected(0.6854705810117458))],
  ),
  fixture(
    'statistical',
    'beta-inv-basic',
    'BETA.INV inverse',
    '=BETA.INV(0.6854705810117458,8,10,1,3)',
    [],
    [output('A1', numberExpected(2))],
  ),
  fixture(
    'statistical',
    'f-dist-rt-basic',
    'F.DIST.RT right-tail probability',
    '=F.DIST.RT(15.2068649,6,4)',
    [],
    [output('A1', numberExpected(0.01))],
  ),
  fixture(
    'statistical',
    'fdist-basic',
    'FDIST legacy right-tail probability',
    '=FDIST(15.2068649,6,4)',
    [],
    [output('A1', numberExpected(0.01))],
  ),
  fixture(
    'statistical',
    'f-inv-basic',
    'F.INV left-tail inverse',
    '=F.INV(0.01,6,4)',
    [],
    [output('A1', numberExpected(0.10930991466299911))],
  ),
  fixture(
    'statistical',
    'f-inv-rt-basic',
    'F.INV.RT right-tail inverse',
    '=F.INV.RT(0.01,6,4)',
    [],
    [output('A1', numberExpected(15.206864870947697))],
  ),
  fixture(
    'statistical',
    'f-test-basic',
    'F.TEST two-sample variance test',
    '=F.TEST(A1:A5,B1:B5)',
    [
      input('A1', 6),
      input('A2', 7),
      input('A3', 9),
      input('A4', 15),
      input('A5', 21),
      input('B1', 20),
      input('B2', 28),
      input('B3', 31),
      input('B4', 38),
      input('B5', 40),
    ],
    [output('D1', numberExpected(0.648317846786175))],
  ),
  fixture(
    'statistical',
    'z-test-basic',
    'Z.TEST one-tailed z test',
    '=Z.TEST(D1:D5,2,1)',
    [input('D1', 1), input('D2', 2), input('D3', 3), input('D4', 4), input('D5', 5)],
    [output('F1', numberExpected(0.012673617875446075))],
  ),
  fixture('information', 'isblank-basic', 'ISBLANK', '=ISBLANK(A1)', [input('A1', null)], [output('A2', booleanExpected(true))]),
  fixture('information', 'isnumber-basic', 'ISNUMBER', '=ISNUMBER(A1)', [input('A1', 42)], [output('A2', booleanExpected(true))]),
  fixture('information', 'istext-basic', 'ISTEXT', '=ISTEXT(A1)', [input('A1', 'hello')], [output('A2', booleanExpected(true))]),
  fixture(
    'dynamic-array',
    'sequence-spill',
    'SEQUENCE spill',
    '=SEQUENCE(3,1,1,1)',
    [],
    [output('A1', numberExpected(1)), output('A2', numberExpected(2)), output('A3', numberExpected(3))],
  ),
  fixture(
    'dynamic-array',
    'sequence-aggregate',
    'SUM over SEQUENCE',
    '=SUM(SEQUENCE(A1,1,1,1))',
    [input('A1', 3)],
    [output('B1', numberExpected(6))],
  ),
  fixture(
    'dynamic-array',
    'filter-basic',
    'FILTER',
    '=FILTER(A1:A4,A1:A4>2)',
    [input('A1', 1), input('A2', 3), input('A3', 2), input('A4', 4)],
    [output('B1', numberExpected(3)), output('B2', numberExpected(4))],
  ),
  fixture(
    'dynamic-array',
    'unique-basic',
    'UNIQUE',
    '=UNIQUE(A1:A4)',
    [input('A1', 'A'), input('A2', 'B'), input('A3', 'A'), input('A4', 'C')],
    [output('B1', stringExpected('A')), output('B2', stringExpected('B')), output('B3', stringExpected('C'))],
  ),
  {
    ...fixture(
      'names',
      'defined-name-scalar',
      'Defined name scalar reference',
      '=TaxRate*A1',
      [input('A1', 100)],
      [output('A2', numberExpected(8.5))],
      'Requires workbook-level defined names in the oracle workbook.',
    ),
    definedNames: [{ name: 'TaxRate', value: 0.085 }],
  },
  {
    ...fixture(
      'tables',
      'table-total-row-sum',
      'Excel table total row SUM',
      '=SUM(Sales[Amount])',
      [input('A1', 10), input('A2', 12), input('A3', 15)],
      [output('A4', numberExpected(37))],
      'Table metadata must be part of the fixture workbook, not implied by plain cells.',
    ),
    tables: [
      {
        name: 'Sales',
        startAddress: 'A1',
        endAddress: 'A3',
        columnNames: ['Amount'],
        headerRow: false,
        totalsRow: false,
      },
    ],
  },
  {
    ...fixture(
      'structured-reference',
      'table-column-ref',
      'Structured table column reference',
      '=SUM(Sales[Amount])',
      [input('A1', 10), input('A2', 12), input('A3', 15)],
      [output('A4', numberExpected(37))],
      'Kept separate from table totals so the registry can track metadata-aware parsing independently.',
    ),
    tables: [
      {
        name: 'Sales',
        startAddress: 'A1',
        endAddress: 'A3',
        columnNames: ['Amount'],
        headerRow: false,
        totalsRow: false,
      },
    ],
  },
  fixture(
    'volatile',
    'rand-basic',
    'RAND',
    '=RAND()',
    [],
    [output('A1', numberExpected(0.625))],
    'Volatile fixtures must record the exact captured output from the oracle workbook session.',
  ),
  fixture('lambda', 'let-basic', 'LET', '=LET(x,2,x+3)', [], [output('A1', numberExpected(5))]),
  fixture('lambda', 'lambda-invoke', 'LAMBDA invocation', '=LAMBDA(x,x+1)(4)', [], [output('A1', numberExpected(5))]),
  fixture(
    'lambda',
    'map-basic',
    'MAP with LAMBDA',
    '=MAP(A1:A3,LAMBDA(x,x*2))',
    [input('A1', 1), input('A2', 2), input('A3', 3)],
    [output('B1', numberExpected(2)), output('B2', numberExpected(4)), output('B3', numberExpected(6))],
  ),
  fixture(
    'information',
    'value-error-display',
    'Visible #VALUE! error',
    '=1+"x"',
    [],
    [output('A1', errorExpected(ErrorCode.Value, '#VALUE!'))],
  ),
]
