import { ErrorCode } from "@bilig/protocol";
import type { ExcelExpectedValue, ExcelFixtureFamily, ExcelFixtureSuite } from "./index.js";

const excelFixtureIdPattern = /^[a-z][a-z0-9-]*:[a-z0-9-]+$/;

function createExcelFixtureId(family: ExcelFixtureFamily, slug: string): string {
  const normalizedSlug = slug.trim().toLowerCase();
  const id = `${family}:${normalizedSlug}`;
  if (!excelFixtureIdPattern.test(id)) {
    throw new Error(`Invalid Excel fixture id: ${id}`);
  }
  return id;
}

function numberExpected(value: number): ExcelExpectedValue {
  return { kind: "number", value };
}

function errorExpected(code: ErrorCode, display: string): ExcelExpectedValue {
  return { kind: "error", code, display };
}

export const excelDateTimeFixtureSuite: ExcelFixtureSuite = {
  id: "datetime-serial-1900",
  description:
    "Focused Excel 1900-system serial date coverage for DATE, parts, TIME, weekday/time extraction, EDATE, and EOMONTH. TODAY/NOW are documented separately because they are volatile.",
  excelBuild: "Microsoft 365 / 2026-03-19",
  capturedAt: "2026-03-19T15:45:30.000Z",
  sheets: [{ name: "Sheet1" }],
  cases: [
    {
      id: createExcelFixtureId("date-time", "serial-addition"),
      family: "date-time",
      title: "Date serial addition",
      formula: "=A1+7",
      sheetName: "Sheet1",
      notes: "Real parity case using raw serial arithmetic rather than a seeded placeholder.",
      inputs: [{ address: "A1", input: 45292 }],
      outputs: [{ address: "A2", expected: numberExpected(45299) }],
    },
    {
      id: createExcelFixtureId("date-time", "date-constructor-leap-day"),
      family: "date-time",
      title: "DATE constructor leap day",
      formula: "=DATE(2024,2,29)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(45351) }],
    },
    {
      id: createExcelFixtureId("date-time", "date-empty-year-coercion"),
      family: "date-time",
      title: "DATE coerces empty year to 1900",
      formula: "=DATE(A1,1,1)",
      sheetName: "Sheet1",
      inputs: [{ address: "A1", input: null }],
      outputs: [{ address: "A2", expected: numberExpected(1) }],
    },
    {
      id: createExcelFixtureId("date-time", "date-text-error"),
      family: "date-time",
      title: "DATE returns #VALUE! for text year",
      formula: "=DATE(A1,1,1)",
      sheetName: "Sheet1",
      inputs: [{ address: "A1", input: "bad" }],
      outputs: [{ address: "A2", expected: errorExpected(ErrorCode.Value, "#VALUE!") }],
    },
    {
      id: createExcelFixtureId("date-time", "year-month-day-parts"),
      family: "date-time",
      title: "YEAR, MONTH, and DAY from a serial",
      formula: "=YEAR(A1)+MONTH(A1)/100+DAY(A1)/10000",
      sheetName: "Sheet1",
      inputs: [{ address: "A1", input: 45351 }],
      outputs: [{ address: "A2", expected: numberExpected(2024.0229) }],
    },
    {
      id: createExcelFixtureId("date-time", "year-boolean-coercion"),
      family: "date-time",
      title: "YEAR coerces boolean serials",
      formula: "=YEAR(A1)",
      sheetName: "Sheet1",
      inputs: [{ address: "A1", input: true }],
      outputs: [{ address: "A2", expected: numberExpected(1900) }],
    },
    {
      id: createExcelFixtureId("date-time", "month-text-error"),
      family: "date-time",
      title: "MONTH returns #VALUE! for text input",
      formula: "=MONTH(A1)",
      sheetName: "Sheet1",
      inputs: [{ address: "A1", input: "bad" }],
      outputs: [{ address: "A2", expected: errorExpected(ErrorCode.Value, "#VALUE!") }],
    },
    {
      id: createExcelFixtureId("date-time", "day-leap-bug-serial"),
      family: "date-time",
      title: "DAY preserves Excel's 1900 leap-bug serial",
      formula: "=DAY(A1)",
      sheetName: "Sheet1",
      inputs: [{ address: "A1", input: 60 }],
      outputs: [{ address: "A2", expected: numberExpected(29) }],
    },
    {
      id: createExcelFixtureId("date-time", "time-basic"),
      family: "date-time",
      title: "TIME constructs a fractional day serial",
      formula: "=TIME(12,30,0)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(0.5208333333333334) }],
    },
    {
      id: createExcelFixtureId("date-time", "hour-basic"),
      family: "date-time",
      title: "HOUR extracts the hour component",
      formula: "=HOUR(A1)",
      sheetName: "Sheet1",
      inputs: [{ address: "A1", input: 0.5208333333333334 }],
      outputs: [{ address: "A2", expected: numberExpected(12) }],
    },
    {
      id: createExcelFixtureId("date-time", "minute-basic"),
      family: "date-time",
      title: "MINUTE extracts the minute component",
      formula: "=MINUTE(A1)",
      sheetName: "Sheet1",
      inputs: [{ address: "A1", input: 0.5208333333333334 }],
      outputs: [{ address: "A2", expected: numberExpected(30) }],
    },
    {
      id: createExcelFixtureId("date-time", "second-basic"),
      family: "date-time",
      title: "SECOND extracts the second component",
      formula: "=SECOND(A1)",
      sheetName: "Sheet1",
      inputs: [{ address: "A1", input: 0.5208449074074074 }],
      outputs: [{ address: "A2", expected: numberExpected(1) }],
    },
    {
      id: createExcelFixtureId("date-time", "weekday-basic"),
      family: "date-time",
      title: "WEEKDAY returns default Sunday-first numbering",
      formula: "=WEEKDAY(DATE(2026,3,15))",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(1) }],
    },
    {
      id: createExcelFixtureId("date-time", "edate-month-shift"),
      family: "date-time",
      title: "EDATE month shift with leap-year clamp",
      formula: "=EDATE(A1,1)",
      sheetName: "Sheet1",
      inputs: [{ address: "A1", input: 45322 }],
      outputs: [{ address: "A2", expected: numberExpected(45351) }],
    },
    {
      id: createExcelFixtureId("date-time", "edate-boolean-coercion"),
      family: "date-time",
      title: "EDATE coerces boolean start dates",
      formula: "=EDATE(A1,1)",
      sheetName: "Sheet1",
      inputs: [{ address: "A1", input: true }],
      outputs: [{ address: "A2", expected: numberExpected(32) }],
    },
    {
      id: createExcelFixtureId("date-time", "edate-text-error"),
      family: "date-time",
      title: "EDATE returns #VALUE! for text start dates",
      formula: "=EDATE(A1,1)",
      sheetName: "Sheet1",
      inputs: [{ address: "A1", input: "bad" }],
      outputs: [{ address: "A2", expected: errorExpected(ErrorCode.Value, "#VALUE!") }],
    },
    {
      id: createExcelFixtureId("date-time", "eomonth-forward"),
      family: "date-time",
      title: "EOMONTH current and next month",
      formula: "=EOMONTH(A1,B1)",
      sheetName: "Sheet1",
      inputs: [
        { address: "A1", input: 45337 },
        { address: "B1", input: 1 },
      ],
      outputs: [{ address: "A2", expected: numberExpected(45382) }],
    },
    {
      id: createExcelFixtureId("date-time", "eomonth-boolean-coercion"),
      family: "date-time",
      title: "EOMONTH coerces boolean start dates",
      formula: "=EOMONTH(A1,1)",
      sheetName: "Sheet1",
      inputs: [{ address: "A1", input: true }],
      outputs: [{ address: "A2", expected: numberExpected(60) }],
    },
    {
      id: createExcelFixtureId("date-time", "eomonth-text-error"),
      family: "date-time",
      title: "EOMONTH returns #VALUE! for text offsets",
      formula: "=EOMONTH(A1,A2)",
      sheetName: "Sheet1",
      inputs: [
        { address: "A1", input: 1 },
        { address: "A2", input: "bad" },
      ],
      outputs: [{ address: "A3", expected: errorExpected(ErrorCode.Value, "#VALUE!") }],
    },
    {
      id: createExcelFixtureId("date-time", "datedif-ym"),
      family: "date-time",
      title: "DATEDIF returns remaining months after full years",
      formula: '=DATEDIF(DATE(2020,1,15),DATE(2021,3,20),"YM")',
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(2) }],
    },
    {
      id: createExcelFixtureId("date-time", "days360-basic"),
      family: "date-time",
      title: "DAYS360 defaults to the US 30/360 day-count method",
      formula: "=DAYS360(DATE(2024,1,29),DATE(2024,3,31))",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(62) }],
    },
    {
      id: createExcelFixtureId("date-time", "yearfrac-basic"),
      family: "date-time",
      title: "YEARFRAC supports actual/365 basis values",
      formula: "=YEARFRAC(DATE(2024,1,1),DATE(2024,7,1),3)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(182 / 365) }],
    },
    {
      id: createExcelFixtureId("date-time", "fvschedule-basic"),
      family: "date-time",
      title: "FVSCHEDULE compounds a principal by a schedule of rates",
      formula: "=FVSCHEDULE(1000,0.09,0.11,0.1)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(1330.89) }],
    },
    {
      id: createExcelFixtureId("date-time", "effect-basic"),
      family: "date-time",
      title: "EFFECT converts a nominal rate into an effective annual rate",
      formula: "=EFFECT(12%,12)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(0.12682503013196977) }],
    },
    {
      id: createExcelFixtureId("date-time", "nominal-basic"),
      family: "date-time",
      title: "NOMINAL converts an effective annual rate into a nominal rate",
      formula: "=NOMINAL(0.12682503013196977,12)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(0.12) }],
    },
    {
      id: createExcelFixtureId("date-time", "pduration-basic"),
      family: "date-time",
      title: "PDURATION returns the periods needed to reach a future value",
      formula: "=PDURATION(10%,100,121)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(2) }],
    },
    {
      id: createExcelFixtureId("date-time", "rri-basic"),
      family: "date-time",
      title: "RRI returns the equivalent interest rate for growth",
      formula: "=RRI(2,100,121)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(0.1) }],
    },
    {
      id: createExcelFixtureId("date-time", "pv-basic"),
      family: "date-time",
      title: "PV discounts a two-period annuity stream",
      formula: "=PV(10%,2,-576.1904761904761)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(1000.0000000000006) }],
    },
    {
      id: createExcelFixtureId("date-time", "fv-basic"),
      family: "date-time",
      title: "FV compounds a present value and annuity stream",
      formula: "=FV(10%,2,-100,-1000)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(1420) }],
    },
    {
      id: createExcelFixtureId("date-time", "pmt-basic"),
      family: "date-time",
      title: "PMT solves the fixed payment for a two-period loan",
      formula: "=PMT(10%,2,1000)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(-576.1904761904758) }],
    },
    {
      id: createExcelFixtureId("date-time", "nper-basic"),
      family: "date-time",
      title: "NPER returns the total periods implied by payment and rate",
      formula: "=NPER(10%,-576.1904761904761,1000)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(1.9999999999999982) }],
    },
    {
      id: createExcelFixtureId("date-time", "npv-basic"),
      family: "date-time",
      title: "NPV discounts periodic cash flows by period index",
      formula: "=NPV(10%,100,200,300)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(481.5927873779113) }],
    },
    {
      id: createExcelFixtureId("date-time", "rate-basic"),
      family: "date-time",
      title: "RATE solves the per-period annuity rate",
      formula: "=RATE(48,-200,8000)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(0.007701472488246008) }],
    },
    {
      id: createExcelFixtureId("date-time", "irr-basic"),
      family: "date-time",
      title: "IRR solves the periodic internal rate of return from cash flows",
      formula: "=IRR(A1:A6)",
      sheetName: "Sheet1",
      inputs: [
        { address: "A1", input: -70000 },
        { address: "A2", input: 12000 },
        { address: "A3", input: 15000 },
        { address: "A4", input: 18000 },
        { address: "A5", input: 21000 },
        { address: "A6", input: 26000 },
      ],
      outputs: [{ address: "A7", expected: numberExpected(0.08663094803653162) }],
    },
    {
      id: createExcelFixtureId("date-time", "mirr-basic"),
      family: "date-time",
      title: "MIRR uses financing and reinvestment rates for modified returns",
      formula: "=MIRR(A1:A6,10%,12%)",
      sheetName: "Sheet1",
      inputs: [
        { address: "A1", input: -120000 },
        { address: "A2", input: 39000 },
        { address: "A3", input: 30000 },
        { address: "A4", input: 21000 },
        { address: "A5", input: 37000 },
        { address: "A6", input: 46000 },
      ],
      outputs: [{ address: "A7", expected: numberExpected(0.1260941303659051) }],
    },
    {
      id: createExcelFixtureId("date-time", "xnpv-basic"),
      family: "date-time",
      title: "XNPV discounts irregular cash flows by their actual day offsets",
      formula: "=XNPV(0.09,A1:A5,B1:B5)",
      sheetName: "Sheet1",
      inputs: [
        { address: "A1", input: -10000 },
        { address: "A2", input: 2750 },
        { address: "A3", input: 4250 },
        { address: "A4", input: 3250 },
        { address: "A5", input: 2750 },
        { address: "B1", input: 39448 },
        { address: "B2", input: 39508 },
        { address: "B3", input: 39751 },
        { address: "B4", input: 39859 },
        { address: "B5", input: 39904 },
      ],
      outputs: [{ address: "C1", expected: numberExpected(2086.647602031535) }],
    },
    {
      id: createExcelFixtureId("date-time", "xirr-basic"),
      family: "date-time",
      title: "XIRR solves an annualized rate for irregularly timed cash flows",
      formula: "=XIRR(A1:A5,B1:B5)",
      sheetName: "Sheet1",
      inputs: [
        { address: "A1", input: -10000 },
        { address: "A2", input: 2750 },
        { address: "A3", input: 4250 },
        { address: "A4", input: 3250 },
        { address: "A5", input: 2750 },
        { address: "B1", input: 39448 },
        { address: "B2", input: 39508 },
        { address: "B3", input: 39751 },
        { address: "B4", input: 39859 },
        { address: "B5", input: 39904 },
      ],
      outputs: [{ address: "C1", expected: numberExpected(0.37336253351883136) }],
    },
    {
      id: createExcelFixtureId("date-time", "ipmt-basic"),
      family: "date-time",
      title: "IPMT returns the first-period interest payment",
      formula: "=IPMT(10%,1,2,1000)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(-100) }],
    },
    {
      id: createExcelFixtureId("date-time", "ppmt-basic"),
      family: "date-time",
      title: "PPMT returns the first-period principal payment",
      formula: "=PPMT(10%,1,2,1000)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(-476.1904761904758) }],
    },
    {
      id: createExcelFixtureId("date-time", "ispmt-basic"),
      family: "date-time",
      title: "ISPMT uses the straight-line interest schedule",
      formula: "=ISPMT(10%,1,2,1000)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(-50) }],
    },
    {
      id: createExcelFixtureId("date-time", "cumipmt-basic"),
      family: "date-time",
      title: "CUMIPMT returns cumulative loan interest over a period band",
      formula: "=CUMIPMT(9%/12,30*12,125000,13,24,0)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(-11135.232130750845) }],
    },
    {
      id: createExcelFixtureId("date-time", "cumprinc-basic"),
      family: "date-time",
      title: "CUMPRINC returns cumulative loan principal over a period band",
      formula: "=CUMPRINC(9%/12,30*12,125000,13,24,0)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(-934.1071234208765) }],
    },
    {
      id: createExcelFixtureId("date-time", "db-basic"),
      family: "date-time",
      title: "DB calculates fixed-declining balance depreciation",
      formula: "=DB(10000,1000,5,1)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(3690) }],
    },
    {
      id: createExcelFixtureId("date-time", "ddb-basic"),
      family: "date-time",
      title: "DDB calculates double-declining balance depreciation",
      formula: "=DDB(2400,300,10,2)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(384) }],
    },
    {
      id: createExcelFixtureId("date-time", "vdb-basic"),
      family: "date-time",
      title: "VDB sums variable declining balance depreciation across periods",
      formula: "=VDB(2400,300,10,1,3)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(691.2) }],
    },
    {
      id: createExcelFixtureId("date-time", "sln-basic"),
      family: "date-time",
      title: "SLN calculates straight-line depreciation",
      formula: "=SLN(10000,1000,9)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(1000) }],
    },
    {
      id: createExcelFixtureId("date-time", "syd-basic"),
      family: "date-time",
      title: "SYD calculates sum-of-years' digits depreciation",
      formula: "=SYD(10000,1000,9,1)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(1800) }],
    },
    {
      id: createExcelFixtureId("date-time", "disc-basic"),
      family: "date-time",
      title: "DISC annualizes a discounted security price",
      formula: "=DISC(DATE(2023,1,1),DATE(2023,4,1),97,100,2)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(0.12) }],
    },
    {
      id: createExcelFixtureId("date-time", "intrate-basic"),
      family: "date-time",
      title: "INTRATE annualizes fully invested security returns",
      formula: "=INTRATE(DATE(2023,1,1),DATE(2023,4,1),1000,1030,2)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(0.12) }],
    },
    {
      id: createExcelFixtureId("date-time", "received-basic"),
      family: "date-time",
      title: "RECEIVED computes maturity value from investment and discount",
      formula: "=RECEIVED(DATE(2023,1,1),DATE(2023,4,1),1000,0.12,2)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(1030.9278350515465) }],
    },
    {
      id: createExcelFixtureId("date-time", "pricedisc-basic"),
      family: "date-time",
      title: "PRICEDISC prices a discounted security per $100 redemption value",
      formula: "=PRICEDISC(DATE(2008,2,16),DATE(2008,3,1),0.0525,100,2)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(99.79583333333333) }],
    },
    {
      id: createExcelFixtureId("date-time", "yielddisc-basic"),
      family: "date-time",
      title: "YIELDDISC returns the annualized yield for a discounted security",
      formula: "=YIELDDISC(DATE(2008,2,16),DATE(2008,3,1),99.795,100,2)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(0.05282257198685834) }],
    },
    {
      id: createExcelFixtureId("date-time", "pricemat-basic"),
      family: "date-time",
      title: "PRICEMAT prices a maturity-interest security per $100 face value",
      formula: "=PRICEMAT(DATE(2008,2,15),DATE(2008,4,13),DATE(2007,11,11),0.061,0.061,0)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(99.98449887555694) }],
    },
    {
      id: createExcelFixtureId("date-time", "yieldmat-basic"),
      family: "date-time",
      title: "YIELDMAT returns the annualized yield of a maturity-interest security",
      formula: "=YIELDMAT(DATE(2008,3,15),DATE(2008,11,3),DATE(2007,11,8),0.0625,100.0123,0)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(0.060954333691538576) }],
    },
    {
      id: createExcelFixtureId("date-time", "oddfprice-basic"),
      family: "date-time",
      title: "ODDFPRICE prices a security with an odd first coupon period",
      formula:
        "=ODDFPRICE(DATE(2008,11,11),DATE(2021,3,1),DATE(2008,10,15),DATE(2009,3,1),0.0785,0.0625,100,2,1)",
      sheetName: "Sheet1",
      notes: "Matches the Microsoft Learn ODDFPRICE example for an odd first coupon bond.",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(113.597717474079) }],
    },
    {
      id: createExcelFixtureId("date-time", "oddfyield-basic"),
      family: "date-time",
      title: "ODDFYIELD returns the yield of a security with an odd first coupon period",
      formula:
        "=ODDFYIELD(DATE(2008,11,11),DATE(2021,3,1),DATE(2008,10,15),DATE(2009,3,1),0.0575,84.5,100,2,0)",
      sheetName: "Sheet1",
      notes: "Matches the Microsoft Learn ODDFYIELD example for an odd first coupon bond.",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(0.0772455415972989) }],
    },
    {
      id: createExcelFixtureId("date-time", "oddlprice-basic"),
      family: "date-time",
      title: "ODDLPRICE prices a security with an odd last coupon period",
      formula: "=ODDLPRICE(DATE(2008,2,7),DATE(2008,6,15),DATE(2007,10,15),0.0375,0.0405,100,2,0)",
      sheetName: "Sheet1",
      notes: "Matches the Microsoft Learn ODDLPRICE example for a semiannual 30/360 bond.",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(99.8782860147213) }],
    },
    {
      id: createExcelFixtureId("date-time", "oddlyield-basic"),
      family: "date-time",
      title: "ODDLYIELD returns the yield of a security with an odd last coupon period",
      formula: "=ODDLYIELD(DATE(2008,4,20),DATE(2008,6,15),DATE(2007,12,24),0.0375,99.875,100,2,0)",
      sheetName: "Sheet1",
      notes: "Matches the Microsoft Support ODDLYIELD example for a semiannual 30/360 bond.",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(0.0451922356291692) }],
    },
    {
      id: createExcelFixtureId("date-time", "coupdaybs-basic"),
      family: "date-time",
      title: "COUPDAYBS returns accrued days from the coupon period start",
      formula: "=COUPDAYBS(DATE(2007,1,25),DATE(2009,11,15),2,4)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(70) }],
    },
    {
      id: createExcelFixtureId("date-time", "coupdays-basic"),
      family: "date-time",
      title: "COUPDAYS returns the settlement coupon period length",
      formula: "=COUPDAYS(DATE(2007,1,25),DATE(2009,11,15),2,4)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(180) }],
    },
    {
      id: createExcelFixtureId("date-time", "coupdaysnc-basic"),
      family: "date-time",
      title: "COUPDAYSNC returns days from settlement to the next coupon",
      formula: "=COUPDAYSNC(DATE(2007,1,25),DATE(2009,11,15),2,4)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(110) }],
    },
    {
      id: createExcelFixtureId("date-time", "coupncd-basic"),
      family: "date-time",
      title: "COUPNCD returns the next coupon date",
      formula: "=COUPNCD(DATE(2007,1,25),DATE(2009,11,15),2,4)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(39217) }],
    },
    {
      id: createExcelFixtureId("date-time", "coupnum-basic"),
      family: "date-time",
      title: "COUPNUM returns the remaining coupon count",
      formula: "=COUPNUM(DATE(2007,1,25),DATE(2009,11,15),2,4)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(6) }],
    },
    {
      id: createExcelFixtureId("date-time", "couppcd-basic"),
      family: "date-time",
      title: "COUPPCD returns the previous coupon date",
      formula: "=COUPPCD(DATE(2007,1,25),DATE(2009,11,15),2,4)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(39036) }],
    },
    {
      id: createExcelFixtureId("date-time", "price-basic"),
      family: "date-time",
      title: "PRICE returns the clean price per $100 face value",
      formula: "=PRICE(DATE(2008,2,15),DATE(2017,11,15),0.0575,0.065,100,2,0)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(94.63436162132213) }],
    },
    {
      id: createExcelFixtureId("date-time", "yield-basic"),
      family: "date-time",
      title: "YIELD solves the periodic-interest bond yield from price",
      formula: "=YIELD(DATE(2008,2,15),DATE(2016,11,15),0.0575,95.04287,100,2,0)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(0.065) }],
    },
    {
      id: createExcelFixtureId("date-time", "duration-basic"),
      family: "date-time",
      title: "DURATION returns Macauley duration",
      formula: "=DURATION(DATE(2018,7,1),DATE(2048,1,1),0.08,0.09,2,1)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(10.919145281591925) }],
    },
    {
      id: createExcelFixtureId("date-time", "mduration-basic"),
      family: "date-time",
      title: "MDURATION returns modified Macauley duration",
      formula: "=MDURATION(DATE(2008,1,1),DATE(2016,1,1),0.08,0.09,2,1)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(5.735669813918838) }],
    },
    {
      id: createExcelFixtureId("date-time", "tbillprice-basic"),
      family: "date-time",
      title: "TBILLPRICE prices a Treasury bill per $100 face value",
      formula: "=TBILLPRICE(DATE(2008,3,31),DATE(2008,6,1),0.09)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(98.45) }],
    },
    {
      id: createExcelFixtureId("date-time", "tbillyield-basic"),
      family: "date-time",
      title: "TBILLYIELD annualizes a Treasury bill yield from its price",
      formula: "=TBILLYIELD(DATE(2008,3,31),DATE(2008,6,1),98.45)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(0.09141696292534264) }],
    },
    {
      id: createExcelFixtureId("date-time", "tbilleq-basic"),
      family: "date-time",
      title: "TBILLEQ converts a Treasury bill discount rate to a bond-equivalent yield",
      formula: "=TBILLEQ(DATE(2008,3,31),DATE(2008,6,1),0.0914)",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(0.09415149356594302) }],
    },
    {
      id: createExcelFixtureId("date-time", "isoweeknum-basic"),
      family: "date-time",
      title: "ISOWEEKNUM returns ISO week numbering",
      formula: "=ISOWEEKNUM(DATE(2024,1,1))",
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(1) }],
    },
    {
      id: createExcelFixtureId("date-time", "timevalue-basic"),
      family: "date-time",
      title: "TIMEVALUE parses 12-hour clock strings",
      formula: '=TIMEVALUE("1:30 PM")',
      sheetName: "Sheet1",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(0.5625) }],
    },
    {
      id: createExcelFixtureId("date-time", "workday-intl-basic"),
      family: "date-time",
      title: "WORKDAY.INTL skips configured weekend days and holidays",
      formula: "=WORKDAY.INTL(A1,2,7,B1)",
      sheetName: "Sheet1",
      inputs: [
        { address: "A1", input: 46094 },
        { address: "B1", input: 46096 },
      ],
      outputs: [{ address: "A2", expected: numberExpected(46099) }],
    },
    {
      id: createExcelFixtureId("date-time", "networkdays-intl-basic"),
      family: "date-time",
      title: "NETWORKDAYS.INTL counts workdays under a weekend mask",
      formula: "=NETWORKDAYS.INTL(A1,A2,7,B1)",
      sheetName: "Sheet1",
      inputs: [
        { address: "A1", input: 46094 },
        { address: "A2", input: 46098 },
        { address: "B1", input: 46096 },
      ],
      outputs: [{ address: "A3", expected: numberExpected(2) }],
    },
    {
      id: createExcelFixtureId("volatile", "today-captured-utc"),
      family: "volatile",
      title: "TODAY captured at suite timestamp",
      formula: "=TODAY()",
      sheetName: "Sheet1",
      notes:
        "Snapshot recorded against the suite capturedAt UTC timestamp for later oracle comparison.",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(46100) }],
    },
    {
      id: createExcelFixtureId("volatile", "now-captured-utc"),
      family: "volatile",
      title: "NOW captured at suite timestamp",
      formula: "=NOW()",
      sheetName: "Sheet1",
      notes:
        "Snapshot recorded against the suite capturedAt UTC timestamp for later oracle comparison.",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(46100.65659722222) }],
    },
    {
      id: createExcelFixtureId("volatile", "rand-captured"),
      family: "volatile",
      title: "RAND captured sample",
      formula: "=RAND()",
      sheetName: "Sheet1",
      notes:
        "Uses a fixed sampled output so fixture harnesses can assert deterministic JS behavior under a stubbed random source.",
      inputs: [],
      outputs: [{ address: "A1", expected: numberExpected(0.625) }],
    },
  ],
};
