// GENERATED FILE. DO NOT EDIT DIRECTLY.
// Source: scripts/gen-protocol.ts

import { BuiltinId, Opcode } from "./enums.js";

export interface BuiltinDescriptor {
  readonly id: BuiltinId;
  readonly name: string;
  readonly supportsWasm: boolean;
}

export const OPCODE_NAMES: Record<Opcode, string> = {
  [Opcode.PushNumber]: "PushNumber",
  [Opcode.PushBoolean]: "PushBoolean",
  [Opcode.PushCell]: "PushCell",
  [Opcode.PushRange]: "PushRange",
  [Opcode.Add]: "Add",
  [Opcode.Sub]: "Sub",
  [Opcode.Mul]: "Mul",
  [Opcode.Div]: "Div",
  [Opcode.Pow]: "Pow",
  [Opcode.Concat]: "Concat",
  [Opcode.Neg]: "Neg",
  [Opcode.Eq]: "Eq",
  [Opcode.Neq]: "Neq",
  [Opcode.Gt]: "Gt",
  [Opcode.Gte]: "Gte",
  [Opcode.Lt]: "Lt",
  [Opcode.Lte]: "Lte",
  [Opcode.Jump]: "Jump",
  [Opcode.JumpIfFalse]: "JumpIfFalse",
  [Opcode.CallBuiltin]: "CallBuiltin",
  [Opcode.PushString]: "PushString",
  [Opcode.PushError]: "PushError",
  [Opcode.Ret]: "Ret"
};

export const BUILTINS: BuiltinDescriptor[] = [
  { id: BuiltinId.Sum, name: "SUM", supportsWasm: true },
  { id: BuiltinId.Avg, name: "AVG", supportsWasm: true },
  { id: BuiltinId.Min, name: "MIN", supportsWasm: true },
  { id: BuiltinId.Max, name: "MAX", supportsWasm: true },
  { id: BuiltinId.Count, name: "COUNT", supportsWasm: true },
  { id: BuiltinId.CountA, name: "COUNTA", supportsWasm: true },
  { id: BuiltinId.Abs, name: "ABS", supportsWasm: true },
  { id: BuiltinId.Round, name: "ROUND", supportsWasm: true },
  { id: BuiltinId.Floor, name: "FLOOR", supportsWasm: true },
  { id: BuiltinId.Ceiling, name: "CEILING", supportsWasm: true },
  { id: BuiltinId.Mod, name: "MOD", supportsWasm: true },
  { id: BuiltinId.If, name: "IF", supportsWasm: true },
  { id: BuiltinId.And, name: "AND", supportsWasm: true },
  { id: BuiltinId.Or, name: "OR", supportsWasm: true },
  { id: BuiltinId.Not, name: "NOT", supportsWasm: true },
  { id: BuiltinId.Len, name: "LEN", supportsWasm: true },
  { id: BuiltinId.Concat, name: "CONCAT", supportsWasm: true },
  { id: BuiltinId.IsBlank, name: "ISBLANK", supportsWasm: true },
  { id: BuiltinId.IsNumber, name: "ISNUMBER", supportsWasm: true },
  { id: BuiltinId.IsText, name: "ISTEXT", supportsWasm: true },
  { id: BuiltinId.Date, name: "DATE", supportsWasm: true },
  { id: BuiltinId.Year, name: "YEAR", supportsWasm: true },
  { id: BuiltinId.Month, name: "MONTH", supportsWasm: true },
  { id: BuiltinId.Day, name: "DAY", supportsWasm: true },
  { id: BuiltinId.Edate, name: "EDATE", supportsWasm: true },
  { id: BuiltinId.Eomonth, name: "EOMONTH", supportsWasm: true },
  { id: BuiltinId.Exact, name: "EXACT", supportsWasm: true },
  { id: BuiltinId.Int, name: "INT", supportsWasm: true },
  { id: BuiltinId.RoundUp, name: "ROUNDUP", supportsWasm: true },
  { id: BuiltinId.RoundDown, name: "ROUNDDOWN", supportsWasm: true },
  { id: BuiltinId.Time, name: "TIME", supportsWasm: true },
  { id: BuiltinId.Hour, name: "HOUR", supportsWasm: true },
  { id: BuiltinId.Minute, name: "MINUTE", supportsWasm: true },
  { id: BuiltinId.Second, name: "SECOND", supportsWasm: true },
  { id: BuiltinId.Weekday, name: "WEEKDAY", supportsWasm: true },
  { id: BuiltinId.Sin, name: "SIN", supportsWasm: true },
  { id: BuiltinId.Cos, name: "COS", supportsWasm: true },
  { id: BuiltinId.Tan, name: "TAN", supportsWasm: true },
  { id: BuiltinId.Asin, name: "ASIN", supportsWasm: true },
  { id: BuiltinId.Acos, name: "ACOS", supportsWasm: true },
  { id: BuiltinId.Atan, name: "ATAN", supportsWasm: true },
  { id: BuiltinId.Atan2, name: "ATAN2", supportsWasm: true },
  { id: BuiltinId.Degrees, name: "DEGREES", supportsWasm: true },
  { id: BuiltinId.Radians, name: "RADIANS", supportsWasm: true },
  { id: BuiltinId.Exp, name: "EXP", supportsWasm: true },
  { id: BuiltinId.Ln, name: "LN", supportsWasm: true },
  { id: BuiltinId.Log, name: "LOG", supportsWasm: true },
  { id: BuiltinId.Log10, name: "LOG10", supportsWasm: true },
  { id: BuiltinId.Power, name: "POWER", supportsWasm: true },
  { id: BuiltinId.Sqrt, name: "SQRT", supportsWasm: true },
  { id: BuiltinId.Pi, name: "PI", supportsWasm: true },
  { id: BuiltinId.Ifs, name: "IFS", supportsWasm: true },
  { id: BuiltinId.Switch, name: "SWITCH", supportsWasm: true },
  { id: BuiltinId.Xor, name: "XOR", supportsWasm: true },
  { id: BuiltinId.Ifna, name: "IFNA", supportsWasm: true },
  { id: BuiltinId.Days, name: "DAYS", supportsWasm: true },
  { id: BuiltinId.Workday, name: "WORKDAY", supportsWasm: true },
  { id: BuiltinId.Networkdays, name: "NETWORKDAYS", supportsWasm: true },
  { id: BuiltinId.Weeknum, name: "WEEKNUM", supportsWasm: true },
  { id: BuiltinId.Replace, name: "REPLACE", supportsWasm: true },
  { id: BuiltinId.Substitute, name: "SUBSTITUTE", supportsWasm: true },
  { id: BuiltinId.Rept, name: "REPT", supportsWasm: true },
  { id: BuiltinId.Na, name: "NA", supportsWasm: true },
  { id: BuiltinId.Iferror, name: "IFERROR", supportsWasm: true },
  { id: BuiltinId.Match, name: "MATCH", supportsWasm: true },
  { id: BuiltinId.Index, name: "INDEX", supportsWasm: true },
  { id: BuiltinId.Vlookup, name: "VLOOKUP", supportsWasm: true },
  { id: BuiltinId.Hlookup, name: "HLOOKUP", supportsWasm: true },
  { id: BuiltinId.Xlookup, name: "XLOOKUP", supportsWasm: true },
  { id: BuiltinId.Xmatch, name: "XMATCH", supportsWasm: true },
  { id: BuiltinId.Countif, name: "COUNTIF", supportsWasm: true },
  { id: BuiltinId.Countifs, name: "COUNTIFS", supportsWasm: true },
  { id: BuiltinId.Sumif, name: "SUMIF", supportsWasm: true },
  { id: BuiltinId.Sumifs, name: "SUMIFS", supportsWasm: true },
  { id: BuiltinId.Averageif, name: "AVERAGEIF", supportsWasm: true },
  { id: BuiltinId.Averageifs, name: "AVERAGEIFS", supportsWasm: true },
  { id: BuiltinId.Sumproduct, name: "SUMPRODUCT", supportsWasm: true },
  { id: BuiltinId.Left, name: "LEFT", supportsWasm: true },
  { id: BuiltinId.Right, name: "RIGHT", supportsWasm: true },
  { id: BuiltinId.Mid, name: "MID", supportsWasm: true },
  { id: BuiltinId.Trim, name: "TRIM", supportsWasm: true },
  { id: BuiltinId.Upper, name: "UPPER", supportsWasm: true },
  { id: BuiltinId.Lower, name: "LOWER", supportsWasm: true },
  { id: BuiltinId.Find, name: "FIND", supportsWasm: true },
  { id: BuiltinId.Search, name: "SEARCH", supportsWasm: true },
  { id: BuiltinId.Value, name: "VALUE", supportsWasm: true },
  { id: BuiltinId.Today, name: "TODAY", supportsWasm: true },
  { id: BuiltinId.Now, name: "NOW", supportsWasm: true },
  { id: BuiltinId.Rand, name: "RAND", supportsWasm: true },
  { id: BuiltinId.Sequence, name: "SEQUENCE", supportsWasm: true },
  { id: BuiltinId.Offset, name: "OFFSET", supportsWasm: true },
  { id: BuiltinId.Take, name: "TAKE", supportsWasm: true },
  { id: BuiltinId.Drop, name: "DROP", supportsWasm: true },
  { id: BuiltinId.Choosecols, name: "CHOOSECOLS", supportsWasm: true },
  { id: BuiltinId.Chooserows, name: "CHOOSEROWS", supportsWasm: true },
  { id: BuiltinId.Sort, name: "SORT", supportsWasm: true },
  { id: BuiltinId.Sortby, name: "SORTBY", supportsWasm: true },
  { id: BuiltinId.Tocol, name: "TOCOL", supportsWasm: true },
  { id: BuiltinId.Torow, name: "TOROW", supportsWasm: true },
  { id: BuiltinId.Wraprows, name: "WRAPROWS", supportsWasm: true },
  { id: BuiltinId.Wrapcols, name: "WRAPCOLS", supportsWasm: true },
  { id: BuiltinId.Lookup, name: "LOOKUP", supportsWasm: true },
  { id: BuiltinId.Areas, name: "AREAS", supportsWasm: true },
  { id: BuiltinId.Arraytotext, name: "ARRAYTOTEXT", supportsWasm: true },
  { id: BuiltinId.Columns, name: "COLUMNS", supportsWasm: true },
  { id: BuiltinId.Rows, name: "ROWS", supportsWasm: true },
  { id: BuiltinId.Transpose, name: "TRANSPOSE", supportsWasm: true },
  { id: BuiltinId.Hstack, name: "HSTACK", supportsWasm: true },
  { id: BuiltinId.Vstack, name: "VSTACK", supportsWasm: true },
  { id: BuiltinId.Minifs, name: "MINIFS", supportsWasm: true },
  { id: BuiltinId.Maxifs, name: "MAXIFS", supportsWasm: true },
  { id: BuiltinId.T, name: "T", supportsWasm: true },
  { id: BuiltinId.N, name: "N", supportsWasm: true },
  { id: BuiltinId.Type, name: "TYPE", supportsWasm: true },
  { id: BuiltinId.Delta, name: "DELTA", supportsWasm: true },
  { id: BuiltinId.Gestep, name: "GESTEP", supportsWasm: true },
  { id: BuiltinId.Gauss, name: "GAUSS", supportsWasm: true },
  { id: BuiltinId.Phi, name: "PHI", supportsWasm: true },
  { id: BuiltinId.Standardize, name: "STANDARDIZE", supportsWasm: true },
  { id: BuiltinId.Mode, name: "MODE", supportsWasm: true },
  { id: BuiltinId.ModeSngl, name: "MODE.SNGL", supportsWasm: true },
  { id: BuiltinId.Stdev, name: "STDEV", supportsWasm: true },
  { id: BuiltinId.StdevP, name: "STDEV.P", supportsWasm: true },
  { id: BuiltinId.StdevS, name: "STDEV.S", supportsWasm: true },
  { id: BuiltinId.Stdeva, name: "STDEVA", supportsWasm: true },
  { id: BuiltinId.Stdevp, name: "STDEVP", supportsWasm: true },
  { id: BuiltinId.Stdevpa, name: "STDEVPA", supportsWasm: true },
  { id: BuiltinId.Var, name: "VAR", supportsWasm: true },
  { id: BuiltinId.VarP, name: "VAR.P", supportsWasm: true },
  { id: BuiltinId.VarS, name: "VAR.S", supportsWasm: true },
  { id: BuiltinId.Vara, name: "VARA", supportsWasm: true },
  { id: BuiltinId.Varp, name: "VARP", supportsWasm: true },
  { id: BuiltinId.Varpa, name: "VARPA", supportsWasm: true },
  { id: BuiltinId.Skew, name: "SKEW", supportsWasm: true },
  { id: BuiltinId.SkewP, name: "SKEW.P", supportsWasm: true },
  { id: BuiltinId.Kurt, name: "KURT", supportsWasm: true },
  { id: BuiltinId.Normdist, name: "NORMDIST", supportsWasm: true },
  { id: BuiltinId.NormDist, name: "NORM.DIST", supportsWasm: true },
  { id: BuiltinId.Norminv, name: "NORMINV", supportsWasm: true },
  { id: BuiltinId.NormInv, name: "NORM.INV", supportsWasm: true },
  { id: BuiltinId.Normsdist, name: "NORMSDIST", supportsWasm: true },
  { id: BuiltinId.NormSDist, name: "NORM.S.DIST", supportsWasm: true },
  { id: BuiltinId.Normsinv, name: "NORMSINV", supportsWasm: true },
  { id: BuiltinId.NormSInv, name: "NORM.S.INV", supportsWasm: true },
  { id: BuiltinId.Loginv, name: "LOGINV", supportsWasm: true },
  { id: BuiltinId.LognormInv, name: "LOGNORM.INV", supportsWasm: true },
  { id: BuiltinId.Lognormdist, name: "LOGNORMDIST", supportsWasm: true },
  { id: BuiltinId.LognormDist, name: "LOGNORM.DIST", supportsWasm: true },
  { id: BuiltinId.ConfidenceNorm, name: "CONFIDENCE.NORM", supportsWasm: true },
  { id: BuiltinId.Effect, name: "EFFECT", supportsWasm: true },
  { id: BuiltinId.Nominal, name: "NOMINAL", supportsWasm: true },
  { id: BuiltinId.Pduration, name: "PDURATION", supportsWasm: true },
  { id: BuiltinId.Rri, name: "RRI", supportsWasm: true },
  { id: BuiltinId.Fv, name: "FV", supportsWasm: true },
  { id: BuiltinId.Pv, name: "PV", supportsWasm: true },
  { id: BuiltinId.Pmt, name: "PMT", supportsWasm: true },
  { id: BuiltinId.Nper, name: "NPER", supportsWasm: true },
  { id: BuiltinId.Npv, name: "NPV", supportsWasm: true },
  { id: BuiltinId.Ipmt, name: "IPMT", supportsWasm: true },
  { id: BuiltinId.Ppmt, name: "PPMT", supportsWasm: true },
  { id: BuiltinId.Ispmt, name: "ISPMT", supportsWasm: true },
  { id: BuiltinId.Permut, name: "PERMUT", supportsWasm: true },
  { id: BuiltinId.Permutationa, name: "PERMUTATIONA", supportsWasm: true },
  { id: BuiltinId.Erf, name: "ERF", supportsWasm: true },
  { id: BuiltinId.ErfPrecise, name: "ERF.PRECISE", supportsWasm: true },
  { id: BuiltinId.Erfc, name: "ERFC", supportsWasm: true },
  { id: BuiltinId.ErfcPrecise, name: "ERFC.PRECISE", supportsWasm: true },
  { id: BuiltinId.Fisher, name: "FISHER", supportsWasm: true },
  { id: BuiltinId.Fisherinv, name: "FISHERINV", supportsWasm: true },
  { id: BuiltinId.Gammaln, name: "GAMMALN", supportsWasm: true },
  { id: BuiltinId.GammalnPrecise, name: "GAMMALN.PRECISE", supportsWasm: true },
  { id: BuiltinId.Gamma, name: "GAMMA", supportsWasm: true },
  { id: BuiltinId.Confidence, name: "CONFIDENCE", supportsWasm: true },
  { id: BuiltinId.Expondist, name: "EXPONDIST", supportsWasm: true },
  { id: BuiltinId.ExponDist, name: "EXPON.DIST", supportsWasm: true },
  { id: BuiltinId.Poisson, name: "POISSON", supportsWasm: true },
  { id: BuiltinId.PoissonDist, name: "POISSON.DIST", supportsWasm: true },
  { id: BuiltinId.Weibull, name: "WEIBULL", supportsWasm: true },
  { id: BuiltinId.WeibullDist, name: "WEIBULL.DIST", supportsWasm: true },
  { id: BuiltinId.Gammadist, name: "GAMMADIST", supportsWasm: true },
  { id: BuiltinId.GammaDist, name: "GAMMA.DIST", supportsWasm: true },
  { id: BuiltinId.Chidist, name: "CHIDIST", supportsWasm: true },
  { id: BuiltinId.ChisqDistRt, name: "CHISQ.DIST.RT", supportsWasm: true },
  { id: BuiltinId.ChisqDist, name: "CHISQ.DIST", supportsWasm: true },
  { id: BuiltinId.Binomdist, name: "BINOMDIST", supportsWasm: true },
  { id: BuiltinId.BinomDist, name: "BINOM.DIST", supportsWasm: true },
  { id: BuiltinId.BinomDistRange, name: "BINOM.DIST.RANGE", supportsWasm: true },
  { id: BuiltinId.Critbinom, name: "CRITBINOM", supportsWasm: true },
  { id: BuiltinId.BinomInv, name: "BINOM.INV", supportsWasm: true },
  { id: BuiltinId.Hypgeomdist, name: "HYPGEOMDIST", supportsWasm: true },
  { id: BuiltinId.HypgeomDist, name: "HYPGEOM.DIST", supportsWasm: true },
  { id: BuiltinId.Negbinomdist, name: "NEGBINOMDIST", supportsWasm: true },
  { id: BuiltinId.NegbinomDist, name: "NEGBINOM.DIST", supportsWasm: true }
];
