// GENERATED FILE. DO NOT EDIT DIRECTLY.
// Source: scripts/gen-protocol.ts

import { BuiltinId, Opcode } from "./enums.js";

export interface BuiltinDescriptor {
  readonly id: BuiltinId;
  readonly name: string;
  readonly supportsWasm: boolean;
}

export const OPCODE_NAMES: Record<Opcode, string> = {
  [Opcode.PushNumber]: "PushNumber",
  [Opcode.PushBoolean]: "PushBoolean",
  [Opcode.PushCell]: "PushCell",
  [Opcode.PushRange]: "PushRange",
  [Opcode.Add]: "Add",
  [Opcode.Sub]: "Sub",
  [Opcode.Mul]: "Mul",
  [Opcode.Div]: "Div",
  [Opcode.Pow]: "Pow",
  [Opcode.Concat]: "Concat",
  [Opcode.Neg]: "Neg",
  [Opcode.Eq]: "Eq",
  [Opcode.Neq]: "Neq",
  [Opcode.Gt]: "Gt",
  [Opcode.Gte]: "Gte",
  [Opcode.Lt]: "Lt",
  [Opcode.Lte]: "Lte",
  [Opcode.Jump]: "Jump",
  [Opcode.JumpIfFalse]: "JumpIfFalse",
  [Opcode.CallBuiltin]: "CallBuiltin",
  [Opcode.PushString]: "PushString",
  [Opcode.PushError]: "PushError",
  [Opcode.Ret]: "Ret"
};

export const BUILTINS: BuiltinDescriptor[] = [
  { id: BuiltinId.Sum, name: "SUM", supportsWasm: true },
  { id: BuiltinId.Avg, name: "AVG", supportsWasm: true },
  { id: BuiltinId.Min, name: "MIN", supportsWasm: true },
  { id: BuiltinId.Max, name: "MAX", supportsWasm: true },
  { id: BuiltinId.Count, name: "COUNT", supportsWasm: true },
  { id: BuiltinId.CountA, name: "COUNTA", supportsWasm: true },
  { id: BuiltinId.Abs, name: "ABS", supportsWasm: true },
  { id: BuiltinId.Round, name: "ROUND", supportsWasm: true },
  { id: BuiltinId.Floor, name: "FLOOR", supportsWasm: true },
  { id: BuiltinId.Ceiling, name: "CEILING", supportsWasm: true },
  { id: BuiltinId.Mod, name: "MOD", supportsWasm: true },
  { id: BuiltinId.If, name: "IF", supportsWasm: true },
  { id: BuiltinId.And, name: "AND", supportsWasm: true },
  { id: BuiltinId.Or, name: "OR", supportsWasm: true },
  { id: BuiltinId.Not, name: "NOT", supportsWasm: true },
  { id: BuiltinId.Len, name: "LEN", supportsWasm: true },
  { id: BuiltinId.Concat, name: "CONCAT", supportsWasm: true },
  { id: BuiltinId.IsBlank, name: "ISBLANK", supportsWasm: true },
  { id: BuiltinId.IsNumber, name: "ISNUMBER", supportsWasm: true },
  { id: BuiltinId.IsText, name: "ISTEXT", supportsWasm: true },
  { id: BuiltinId.Date, name: "DATE", supportsWasm: true },
  { id: BuiltinId.Year, name: "YEAR", supportsWasm: true },
  { id: BuiltinId.Month, name: "MONTH", supportsWasm: true },
  { id: BuiltinId.Day, name: "DAY", supportsWasm: true },
  { id: BuiltinId.Edate, name: "EDATE", supportsWasm: true },
  { id: BuiltinId.Eomonth, name: "EOMONTH", supportsWasm: true },
  { id: BuiltinId.Exact, name: "EXACT", supportsWasm: true },
  { id: BuiltinId.Int, name: "INT", supportsWasm: true },
  { id: BuiltinId.RoundUp, name: "ROUNDUP", supportsWasm: true },
  { id: BuiltinId.RoundDown, name: "ROUNDDOWN", supportsWasm: true },
  { id: BuiltinId.Time, name: "TIME", supportsWasm: true },
  { id: BuiltinId.Hour, name: "HOUR", supportsWasm: true },
  { id: BuiltinId.Minute, name: "MINUTE", supportsWasm: true },
  { id: BuiltinId.Second, name: "SECOND", supportsWasm: true },
  { id: BuiltinId.Weekday, name: "WEEKDAY", supportsWasm: true },
  { id: BuiltinId.Sin, name: "SIN", supportsWasm: true },
  { id: BuiltinId.Cos, name: "COS", supportsWasm: true },
  { id: BuiltinId.Tan, name: "TAN", supportsWasm: true },
  { id: BuiltinId.Asin, name: "ASIN", supportsWasm: true },
  { id: BuiltinId.Acos, name: "ACOS", supportsWasm: true },
  { id: BuiltinId.Atan, name: "ATAN", supportsWasm: true },
  { id: BuiltinId.Atan2, name: "ATAN2", supportsWasm: true },
  { id: BuiltinId.Degrees, name: "DEGREES", supportsWasm: true },
  { id: BuiltinId.Radians, name: "RADIANS", supportsWasm: true },
  { id: BuiltinId.Exp, name: "EXP", supportsWasm: true },
  { id: BuiltinId.Ln, name: "LN", supportsWasm: true },
  { id: BuiltinId.Log, name: "LOG", supportsWasm: true },
  { id: BuiltinId.Log10, name: "LOG10", supportsWasm: true },
  { id: BuiltinId.Power, name: "POWER", supportsWasm: true },
  { id: BuiltinId.Sqrt, name: "SQRT", supportsWasm: true },
  { id: BuiltinId.Pi, name: "PI", supportsWasm: true },
  { id: BuiltinId.Ifs, name: "IFS", supportsWasm: true },
  { id: BuiltinId.Switch, name: "SWITCH", supportsWasm: true },
  { id: BuiltinId.Xor, name: "XOR", supportsWasm: true },
  { id: BuiltinId.Ifna, name: "IFNA", supportsWasm: true },
  { id: BuiltinId.Days, name: "DAYS", supportsWasm: true },
  { id: BuiltinId.Workday, name: "WORKDAY", supportsWasm: true },
  { id: BuiltinId.Networkdays, name: "NETWORKDAYS", supportsWasm: true },
  { id: BuiltinId.Weeknum, name: "WEEKNUM", supportsWasm: true },
  { id: BuiltinId.Replace, name: "REPLACE", supportsWasm: true },
  { id: BuiltinId.Substitute, name: "SUBSTITUTE", supportsWasm: true },
  { id: BuiltinId.Rept, name: "REPT", supportsWasm: true },
  { id: BuiltinId.Na, name: "NA", supportsWasm: true },
  { id: BuiltinId.Iferror, name: "IFERROR", supportsWasm: true },
  { id: BuiltinId.Match, name: "MATCH", supportsWasm: true },
  { id: BuiltinId.Index, name: "INDEX", supportsWasm: true },
  { id: BuiltinId.Vlookup, name: "VLOOKUP", supportsWasm: true },
  { id: BuiltinId.Hlookup, name: "HLOOKUP", supportsWasm: true },
  { id: BuiltinId.Xlookup, name: "XLOOKUP", supportsWasm: true },
  { id: BuiltinId.Xmatch, name: "XMATCH", supportsWasm: true },
  { id: BuiltinId.Countif, name: "COUNTIF", supportsWasm: true },
  { id: BuiltinId.Countifs, name: "COUNTIFS", supportsWasm: true },
  { id: BuiltinId.Sumif, name: "SUMIF", supportsWasm: true },
  { id: BuiltinId.Sumifs, name: "SUMIFS", supportsWasm: true },
  { id: BuiltinId.Averageif, name: "AVERAGEIF", supportsWasm: true },
  { id: BuiltinId.Averageifs, name: "AVERAGEIFS", supportsWasm: true },
  { id: BuiltinId.Sumproduct, name: "SUMPRODUCT", supportsWasm: true },
  { id: BuiltinId.Left, name: "LEFT", supportsWasm: true },
  { id: BuiltinId.Right, name: "RIGHT", supportsWasm: true },
  { id: BuiltinId.Mid, name: "MID", supportsWasm: true },
  { id: BuiltinId.Trim, name: "TRIM", supportsWasm: true },
  { id: BuiltinId.Upper, name: "UPPER", supportsWasm: true },
  { id: BuiltinId.Lower, name: "LOWER", supportsWasm: true },
  { id: BuiltinId.Find, name: "FIND", supportsWasm: true },
  { id: BuiltinId.Search, name: "SEARCH", supportsWasm: true },
  { id: BuiltinId.Value, name: "VALUE", supportsWasm: true },
  { id: BuiltinId.Today, name: "TODAY", supportsWasm: true },
  { id: BuiltinId.Now, name: "NOW", supportsWasm: true },
  { id: BuiltinId.Rand, name: "RAND", supportsWasm: true },
  { id: BuiltinId.Sequence, name: "SEQUENCE", supportsWasm: true },
  { id: BuiltinId.Offset, name: "OFFSET", supportsWasm: true },
  { id: BuiltinId.Take, name: "TAKE", supportsWasm: true },
  { id: BuiltinId.Drop, name: "DROP", supportsWasm: true },
  { id: BuiltinId.Choosecols, name: "CHOOSECOLS", supportsWasm: true },
  { id: BuiltinId.Chooserows, name: "CHOOSEROWS", supportsWasm: true },
  { id: BuiltinId.Sort, name: "SORT", supportsWasm: true },
  { id: BuiltinId.Sortby, name: "SORTBY", supportsWasm: true },
  { id: BuiltinId.Tocol, name: "TOCOL", supportsWasm: true },
  { id: BuiltinId.Torow, name: "TOROW", supportsWasm: true },
  { id: BuiltinId.Wraprows, name: "WRAPROWS", supportsWasm: true },
  { id: BuiltinId.Wrapcols, name: "WRAPCOLS", supportsWasm: true },
  { id: BuiltinId.Lookup, name: "LOOKUP", supportsWasm: true },
  { id: BuiltinId.Areas, name: "AREAS", supportsWasm: true },
  { id: BuiltinId.Arraytotext, name: "ARRAYTOTEXT", supportsWasm: true },
  { id: BuiltinId.Columns, name: "COLUMNS", supportsWasm: true },
  { id: BuiltinId.Rows, name: "ROWS", supportsWasm: true },
  { id: BuiltinId.Transpose, name: "TRANSPOSE", supportsWasm: true },
  { id: BuiltinId.Hstack, name: "HSTACK", supportsWasm: true },
  { id: BuiltinId.Vstack, name: "VSTACK", supportsWasm: true },
  { id: BuiltinId.Minifs, name: "MINIFS", supportsWasm: true },
  { id: BuiltinId.Maxifs, name: "MAXIFS", supportsWasm: true }
];
