import type { BuildScorecardInput } from '../gen-bilig-dominance-scorecard.ts'
import {
  family,
  googleSheetsCalculationCase,
  googleSheetsLargeWorkbookCase,
  googleSheetsLargeWorkbookSpreadsheet,
  googleSheetsRecalculationCase,
  googleSheetsRecalculationSpreadsheet,
  googleSheetsStructuralCase,
  googleSheetsStructuralSpreadsheet,
  headedBrowserContract,
  largeWorkbookCase,
  recalculationCase,
  sloMeasurement,
  structuralCase,
} from './bilig-dominance-scorecard.fixture-helpers.ts'

export function buildFixtureInput(): BuildScorecardInput {
  return {
    competitiveArtifactPath: 'packages/benchmarks/baselines/workpaper-vs-hyperformula.json',
    calculationSemanticsScorecardPath: 'packages/benchmarks/baselines/calculation-semantics-scorecard.json',
    formulaSnapshotPath: 'packages/formula/src/__tests__/fixtures/formula-dominance-snapshot.json',
    googleSheetsLiveCalculationScorecardPath: 'packages/benchmarks/baselines/google-sheets-live-calculation-scorecard.json',
    googleSheetsLiveRecalculationScorecardPath: 'packages/benchmarks/baselines/google-sheets-live-recalculation-scorecard.json',
    googleSheetsLiveStructuralScorecardPath: 'packages/benchmarks/baselines/google-sheets-live-structural-scorecard.json',
    googleSheetsLiveLargeWorkbookScorecardPath: 'packages/benchmarks/baselines/google-sheets-live-large-workbook-scorecard.json',
    microsoftExcelLiveCalculationScorecardPath: 'packages/benchmarks/baselines/microsoft-excel-live-calculation-scorecard.json',
    microsoftExcelLiveRecalculationScorecardPath: 'packages/benchmarks/baselines/microsoft-excel-live-recalculation-scorecard.json',
    microsoftExcelLiveLargeWorkbookScorecardPath: 'packages/benchmarks/baselines/microsoft-excel-live-large-workbook-scorecard.json',
    microsoftExcelLiveStructuralScorecardPath: 'packages/benchmarks/baselines/microsoft-excel-live-structural-scorecard.json',
    auditabilityScorecardPath: 'packages/benchmarks/baselines/auditability-scorecard.json',
    automationScorecardPath: 'packages/benchmarks/baselines/automation-scorecard.json',
    collaborationScorecardPath: 'packages/benchmarks/baselines/collaboration-scorecard.json',
    importExportFidelityScorecardPath: 'packages/benchmarks/baselines/import-export-fidelity-scorecard.json',
    largeWorkbookSloScorecardPath: 'packages/benchmarks/baselines/large-workbook-slo-scorecard.json',
    uiResponsivenessLiveBrowserScorecardPath: 'packages/benchmarks/baselines/ui-responsiveness-live-browser-scorecard.json',
    reliabilityScorecardPath: 'packages/benchmarks/baselines/reliability-scorecard.json',
    securityPostureScorecardPath: 'packages/benchmarks/baselines/security-posture-scorecard.json',
    surfaceSnapshotPath: 'packages/headless/src/__tests__/fixtures/hyperformula-surface.json',
    formulaSnapshot: {
      schemaVersion: 1,
      formulaBreadth: {
        officeListed: {
          production: 461,
          total: 508,
          percent: 90.7,
        },
        tracked: {
          production: 475,
          total: 525,
          percent: 90.5,
        },
        missingOfficeFunctions: ['ACCRINT', 'MMULT'],
      },
      canonical: {
        summary: {
          production: 300,
          total: 300,
          percent: 100,
        },
        nonProductionRows: [],
      },
    },
    surfaceSnapshot: {
      hyperFormulaVersion: '3.2.0',
      hyperFormulaCommit: 'abc123',
      classSurface: {
        staticMembers: ['version'],
        staticMethods: ['buildEmpty'],
        instanceAccessors: ['dependencyGraph'],
        instanceMethods: ['getCellValue', 'setCellContents'],
      },
      configKeys: ['licenseKey', 'useColumnIndex'],
    },
    calculationSemanticsScorecard: {
      schemaVersion: 1,
      suite: 'calculation-semantics-coverage',
      generatedAt: 'checked-in-generated-artifact',
      source: {
        artifactGenerator: 'scripts/gen-calculation-semantics-scorecard.ts',
        fixturePackage: 'packages/excel-fixtures',
        compatibilityRegistry: 'packages/formula/src/compatibility.ts',
        fixtureHarnessTest: 'packages/formula/src/__tests__/fixture-harness.test.ts',
        runtimeCorrectnessTest: 'packages/core/src/__tests__/formula-runtime-correctness.test.ts',
        executionCommand: 'pnpm test:correctness:formula',
      },
      summary: {
        allCommittedFormulaSemanticsCovered: true,
        canonicalFormulaFixtureCount: 300,
        workbookSemanticsFixtureCount: 10,
        executableStableFormulaFixtureCount: 297,
        deterministicVolatileFixtureCount: 3,
        executableWorkbookSemanticsFixtureCount: 10,
        dateTimeEdgeFixtureCount: 62,
        coveredCanonicalFixtureCount: 300,
        coveredWorkbookSemanticsFixtureCount: 10,
        workbookSemanticsCategoryCount: 1,
        coveredWorkbookSemanticsCategories: ['cross-sheet-references'],
        coveredFamilies: ['aggregation', 'arithmetic', 'comparison', 'date-time', 'dynamic-array', 'information', 'lambda', 'logical'],
        missingCanonicalFixtureIds: [],
        missingWorkbookSemanticsFixtureIds: [],
        fixtureRegistryAligned: true,
      },
      coverage: {
        stableFormulaFixtureIds: ['lookup-reference:offset-basic'],
        deterministicVolatileFixtureIds: ['date-time:now-volatile', 'date-time:today-volatile', 'volatile:rand-basic'],
        workbookSemanticsFixtureIds: ['arithmetic:cross-sheet-multiply'],
        workbookSemanticsCategories: [{ category: 'cross-sheet-references', fixtureIds: ['arithmetic:cross-sheet-multiply'] }],
        dateTimeEdgeFixtureIds: ['date-time:date-constructor'],
      },
    },
    googleSheetsLiveCalculationScorecard: {
      schemaVersion: 1,
      suite: 'google-sheets-live-calculation-correctness',
      generatedAt: '2026-05-06T17:00:00.000Z',
      host: {
        arch: 'arm64',
        platform: 'darwin',
      },
      source: {
        artifactGenerator: 'scripts/gen-google-sheets-live-calculation-scorecard.ts',
        implementationPackage: 'packages/headless',
        evidenceKind: 'live-google-sheets-native-conversion-via-google-drive-connector',
        captureTransport: 'google-drive-connector',
      },
      googleSheets: {
        spreadsheetId: 'google-sheet-test-id',
        spreadsheetUrl: 'https://docs.google.com/spreadsheets/d/google-sheet-test-id',
        title: 'bilig live calculation parity capture',
        worksheetName: 'Cases',
        valueRenderOption: 'UNFORMATTED_VALUE',
      },
      summary: {
        allRequiredCasesPassed: true,
        requiredCaseCount: 2,
        matchingCaseCount: 2,
        coveredFeatures: ['excelLive.arithmeticPrecedence', 'excelLive.aggregateSumRange'],
        microsoftExcelEvidence: 'not-covered-by-this-artifact',
      },
      cases: [
        googleSheetsCalculationCase('arithmetic-precedence', '=A2+B2*2', 'D2', 'excelLive.arithmeticPrecedence', 24),
        googleSheetsCalculationCase('aggregate-sum-range', '=SUM(A3:C3)', 'D3', 'excelLive.aggregateSumRange', 6),
      ],
    },
    googleSheetsLiveRecalculationScorecard: {
      schemaVersion: 1,
      suite: 'google-sheets-live-recalculation-performance',
      generatedAt: '2026-05-06T20:00:00.000Z',
      host: {
        arch: 'arm64',
        platform: 'darwin',
      },
      source: {
        artifactGenerator: 'scripts/gen-google-sheets-live-recalculation-scorecard.ts',
        implementationPackage: 'packages/headless',
        evidenceKind: 'live-google-sheets-native-conversion-via-google-drive-connector',
        captureTransport: 'google-drive-connector',
      },
      benchmark: {
        sampleCount: 3,
        warmupCount: 0,
        valueRenderOption: 'UNFORMATTED_VALUE',
        measuredGoogleSheetsOperation: 'edit-and-read-recalculated-values',
        measuredWorkpaperOperation: 'mutate-and-recalculate',
        samplingOrder: 'engine-isolated-workpaper-then-google-sheets',
      },
      googleSheets: {
        spreadsheets: [
          googleSheetsRecalculationSpreadsheet('google-sheets-live-recalculation-dirty-fanout-edit', 0),
          googleSheetsRecalculationSpreadsheet('google-sheets-live-recalculation-dirty-fanout-edit', 1),
          googleSheetsRecalculationSpreadsheet('google-sheets-live-recalculation-dirty-fanout-edit', 2),
          googleSheetsRecalculationSpreadsheet('google-sheets-live-recalculation-suspended-batch-single-column-edit', 0),
          googleSheetsRecalculationSpreadsheet('google-sheets-live-recalculation-suspended-batch-single-column-edit', 1),
          googleSheetsRecalculationSpreadsheet('google-sheets-live-recalculation-suspended-batch-single-column-edit', 2),
          googleSheetsRecalculationSpreadsheet('google-sheets-live-recalculation-conditional-aggregation-criteria-edit', 0),
          googleSheetsRecalculationSpreadsheet('google-sheets-live-recalculation-conditional-aggregation-criteria-edit', 1),
          googleSheetsRecalculationSpreadsheet('google-sheets-live-recalculation-conditional-aggregation-criteria-edit', 2),
          googleSheetsRecalculationSpreadsheet('google-sheets-live-recalculation-full-rebuild-recalculate', 0),
          googleSheetsRecalculationSpreadsheet('google-sheets-live-recalculation-full-rebuild-recalculate', 1),
          googleSheetsRecalculationSpreadsheet('google-sheets-live-recalculation-full-rebuild-recalculate', 2),
        ],
      },
      summary: {
        allRequiredCasesPassed: true,
        requiredCaseCount: 4,
        tenXMeanAndP95CaseCount: 4,
        workpaperWins: 4,
        coveredWorkloads: [
          'dirty-fanout-edit',
          'suspended-batch-single-column-edit',
          'conditional-aggregation-criteria-edit',
          'full-rebuild-recalculate',
        ],
        microsoftExcelEvidence: 'not-covered-by-this-artifact',
      },
      cases: [
        googleSheetsRecalculationCase('google-sheets-live-recalculation-dirty-fanout-edit', 'dirty-fanout-edit'),
        googleSheetsRecalculationCase(
          'google-sheets-live-recalculation-suspended-batch-single-column-edit',
          'suspended-batch-single-column-edit',
        ),
        googleSheetsRecalculationCase(
          'google-sheets-live-recalculation-conditional-aggregation-criteria-edit',
          'conditional-aggregation-criteria-edit',
        ),
        googleSheetsRecalculationCase('google-sheets-live-recalculation-full-rebuild-recalculate', 'full-rebuild-recalculate'),
      ],
    },
    googleSheetsLiveStructuralScorecard: {
      schemaVersion: 1,
      suite: 'google-sheets-live-structural-performance',
      generatedAt: '2026-05-06T20:15:00.000Z',
      host: {
        arch: 'arm64',
        platform: 'darwin',
      },
      source: {
        artifactGenerator: 'scripts/gen-google-sheets-live-structural-scorecard.ts',
        implementationPackage: 'packages/headless',
        evidenceKind: 'live-google-sheets-native-conversion-via-google-drive-connector',
        captureTransport: 'google-drive-connector',
      },
      benchmark: {
        rowCount: 500,
        sampleCount: 3,
        valueRenderOption: 'UNFORMATTED_VALUE',
        measuredGoogleSheetsOperation: 'structural-edit-and-read-verification-values',
        measuredWorkpaperOperation: 'structural-edit',
        samplingOrder: 'engine-isolated-workpaper-then-google-sheets',
      },
      googleSheets: {
        spreadsheets: [
          googleSheetsStructuralSpreadsheet('google-sheets-live-structural-insert-rows', 0),
          googleSheetsStructuralSpreadsheet('google-sheets-live-structural-insert-rows', 1),
          googleSheetsStructuralSpreadsheet('google-sheets-live-structural-insert-rows', 2),
          googleSheetsStructuralSpreadsheet('google-sheets-live-structural-delete-rows', 0),
          googleSheetsStructuralSpreadsheet('google-sheets-live-structural-delete-rows', 1),
          googleSheetsStructuralSpreadsheet('google-sheets-live-structural-delete-rows', 2),
          googleSheetsStructuralSpreadsheet('google-sheets-live-structural-move-rows', 0),
          googleSheetsStructuralSpreadsheet('google-sheets-live-structural-move-rows', 1),
          googleSheetsStructuralSpreadsheet('google-sheets-live-structural-move-rows', 2),
          googleSheetsStructuralSpreadsheet('google-sheets-live-structural-insert-columns', 0),
          googleSheetsStructuralSpreadsheet('google-sheets-live-structural-insert-columns', 1),
          googleSheetsStructuralSpreadsheet('google-sheets-live-structural-insert-columns', 2),
          googleSheetsStructuralSpreadsheet('google-sheets-live-structural-delete-columns', 0),
          googleSheetsStructuralSpreadsheet('google-sheets-live-structural-delete-columns', 1),
          googleSheetsStructuralSpreadsheet('google-sheets-live-structural-delete-columns', 2),
          googleSheetsStructuralSpreadsheet('google-sheets-live-structural-move-columns', 0),
          googleSheetsStructuralSpreadsheet('google-sheets-live-structural-move-columns', 1),
          googleSheetsStructuralSpreadsheet('google-sheets-live-structural-move-columns', 2),
        ],
      },
      summary: {
        allRequiredCasesPassed: true,
        requiredCaseCount: 6,
        tenXMeanAndP95CaseCount: 6,
        workpaperWins: 6,
        coveredOperations: ['insert-rows', 'delete-rows', 'move-rows', 'insert-columns', 'delete-columns', 'move-columns'],
        microsoftExcelEvidence: 'not-covered-by-this-artifact',
      },
      cases: [
        googleSheetsStructuralCase('google-sheets-live-structural-insert-rows', 'insert-rows', 'rows'),
        googleSheetsStructuralCase('google-sheets-live-structural-delete-rows', 'delete-rows', 'rows'),
        googleSheetsStructuralCase('google-sheets-live-structural-move-rows', 'move-rows', 'rows'),
        googleSheetsStructuralCase('google-sheets-live-structural-insert-columns', 'insert-columns', 'columns'),
        googleSheetsStructuralCase('google-sheets-live-structural-delete-columns', 'delete-columns', 'columns'),
        googleSheetsStructuralCase('google-sheets-live-structural-move-columns', 'move-columns', 'columns'),
      ],
    },
    googleSheetsLiveLargeWorkbookScorecard: {
      schemaVersion: 1,
      suite: 'google-sheets-live-large-workbook-performance',
      generatedAt: '2026-05-06T19:25:00.000Z',
      host: {
        arch: 'arm64',
        platform: 'darwin',
      },
      source: {
        artifactGenerator: 'scripts/gen-google-sheets-live-large-workbook-scorecard.ts',
        implementationPackage: 'packages/core',
        xlsxExportPackage: 'packages/excel-import',
        corpusPackage: 'packages/benchmarks',
        evidenceKind: 'live-google-sheets-native-conversion-via-google-drive-connector',
        captureTransport: 'google-drive-connector',
      },
      benchmark: {
        sampleCount: 3,
        valueRenderOption: 'UNFORMATTED_VALUE',
        measuredGoogleSheetsOperation: 'native-xlsx-import-and-read-terminal-cell',
        measuredBiligOperation: 'import-snapshot',
        samplingOrder: 'engine-isolated-bilig-then-google-sheets',
      },
      googleSheets: {
        spreadsheets: [
          googleSheetsLargeWorkbookSpreadsheet('google-sheets-live-large-workbook-import-read-dense-mixed-100k', 0),
          googleSheetsLargeWorkbookSpreadsheet('google-sheets-live-large-workbook-import-read-dense-mixed-100k', 1),
          googleSheetsLargeWorkbookSpreadsheet('google-sheets-live-large-workbook-import-read-dense-mixed-100k', 2),
          googleSheetsLargeWorkbookSpreadsheet('google-sheets-live-large-workbook-import-read-dense-mixed-250k', 0),
          googleSheetsLargeWorkbookSpreadsheet('google-sheets-live-large-workbook-import-read-dense-mixed-250k', 1),
          googleSheetsLargeWorkbookSpreadsheet('google-sheets-live-large-workbook-import-read-dense-mixed-250k', 2),
        ],
      },
      summary: {
        allRequiredCasesPassed: true,
        requiredCaseCount: 2,
        tenXMeanAndP95CaseCount: 2,
        biligWins: 2,
        coveredCorpusCaseIds: ['dense-mixed-100k', 'dense-mixed-250k'],
        coveredMaterializedCells: [100_000, 250_000],
        microsoftExcelEvidence: 'not-covered-by-this-artifact',
      },
      cases: [
        googleSheetsLargeWorkbookCase(
          'google-sheets-live-large-workbook-import-read-dense-mixed-100k',
          'native-import-read-dense-mixed-100k',
          'dense-mixed-100k',
          100_000,
        ),
        googleSheetsLargeWorkbookCase(
          'google-sheets-live-large-workbook-import-read-dense-mixed-250k',
          'native-import-read-dense-mixed-250k',
          'dense-mixed-250k',
          250_000,
        ),
      ],
    },
    microsoftExcelLiveCalculationScorecard: {
      schemaVersion: 1,
      suite: 'microsoft-excel-live-calculation-correctness',
      generatedAt: '2026-05-06T09:00:00.000Z',
      host: {
        arch: 'arm64',
        platform: 'darwin',
      },
      source: {
        artifactGenerator: 'scripts/gen-microsoft-excel-live-calculation-scorecard.ts',
        implementationPackage: 'packages/headless',
        evidenceKind: 'live-local-microsoft-excel-automation',
        appleScriptTransport: 'osascript',
      },
      microsoftExcel: {
        appPath: '/Applications/Microsoft Excel.app',
        version: '16.test',
      },
      summary: {
        allRequiredCasesPassed: true,
        requiredCaseCount: 2,
        matchingCaseCount: 2,
        coveredFeatures: ['excelLive.arithmeticPrecedence', 'excelLive.aggregateSumRange'],
        googleSheetsEvidence: 'not-covered-by-this-artifact',
      },
      cases: [
        {
          id: 'arithmetic-precedence',
          formula: '=A2+B2*2',
          formulaCell: 'D2',
          coveredFeature: 'excelLive.arithmeticPrecedence',
          biligValue: 24,
          microsoftExcelRawValue: '24.0',
          microsoftExcelValue: 24,
          passed: true,
        },
        {
          id: 'aggregate-sum-range',
          formula: '=SUM(A3:C3)',
          formulaCell: 'D3',
          coveredFeature: 'excelLive.aggregateSumRange',
          biligValue: 6,
          microsoftExcelRawValue: '6.0',
          microsoftExcelValue: 6,
          passed: true,
        },
      ],
    },
    microsoftExcelLiveRecalculationScorecard: {
      schemaVersion: 1,
      suite: 'microsoft-excel-live-recalculation-performance',
      generatedAt: '2026-05-06T15:30:00.000Z',
      host: {
        arch: 'arm64',
        platform: 'darwin',
      },
      source: {
        artifactGenerator: 'scripts/gen-microsoft-excel-live-recalculation-scorecard.ts',
        implementationPackage: 'packages/headless',
        evidenceKind: 'live-local-microsoft-excel-automation',
        appleScriptTransport: 'osascript',
      },
      benchmark: {
        sampleCount: 5,
        warmupCount: 1,
        screenUpdating: false,
        calculationMode: 'manual-during-measurement',
      },
      microsoftExcel: {
        appPath: '/Applications/Microsoft Excel.app',
        version: '16.test',
      },
      summary: {
        allRequiredCasesPassed: true,
        requiredCaseCount: 4,
        tenXMeanAndP95CaseCount: 4,
        workpaperWins: 4,
        coveredWorkloads: [
          'dirty-fanout-edit',
          'suspended-batch-single-column-edit',
          'conditional-aggregation-criteria-edit',
          'full-rebuild-recalculate',
        ],
        googleSheetsEvidence: 'not-covered-by-this-artifact',
      },
      cases: [
        recalculationCase('excel-live-recalculation-dirty-fanout-edit', 'dirty-fanout-edit', true),
        recalculationCase('excel-live-recalculation-suspended-batch-single-column-edit', 'suspended-batch-single-column-edit', false),
        recalculationCase('excel-live-recalculation-conditional-aggregation-criteria-edit', 'conditional-aggregation-criteria-edit', true),
        recalculationCase('excel-live-recalculation-full-rebuild-recalculate', 'full-rebuild-recalculate', true),
      ],
    },
    microsoftExcelLiveLargeWorkbookScorecard: {
      schemaVersion: 1,
      suite: 'microsoft-excel-live-large-workbook-performance',
      generatedAt: '2026-05-06T16:30:00.000Z',
      host: {
        arch: 'arm64',
        platform: 'darwin',
      },
      source: {
        artifactGenerator: 'scripts/gen-microsoft-excel-live-large-workbook-scorecard.ts',
        implementationPackage: 'packages/core',
        xlsxExportPackage: 'packages/excel-import',
        corpusPackage: 'packages/benchmarks',
        evidenceKind: 'live-local-microsoft-excel-automation',
        appleScriptTransport: 'osascript',
      },
      benchmark: {
        sampleCount: 3,
        screenUpdating: false,
        calculationMode: 'manual-during-open-and-calculate',
        measuredExcelOperation: 'open-workbook-and-calculate-full-rebuild',
        measuredBiligOperation: 'import-snapshot',
        samplingOrder: 'engine-isolated-bilig-then-excel',
      },
      microsoftExcel: {
        appPath: '/Applications/Microsoft Excel.app',
        version: '16.test',
      },
      summary: {
        allRequiredCasesPassed: true,
        requiredCaseCount: 2,
        tenXMeanAndP95CaseCount: 1,
        biligWins: 2,
        coveredCorpusCaseIds: ['dense-mixed-100k', 'dense-mixed-250k'],
        coveredMaterializedCells: [100_000, 250_000],
        googleSheetsEvidence: 'not-covered-by-this-artifact',
      },
      cases: [
        largeWorkbookCase(
          'excel-live-large-workbook-open-calculate-dense-mixed-100k',
          'open-calculate-dense-mixed-100k',
          'dense-mixed-100k',
          100_000,
          true,
        ),
        largeWorkbookCase(
          'excel-live-large-workbook-open-calculate-dense-mixed-250k',
          'open-calculate-dense-mixed-250k',
          'dense-mixed-250k',
          250_000,
          false,
        ),
      ],
    },
    microsoftExcelLiveStructuralScorecard: {
      schemaVersion: 1,
      suite: 'microsoft-excel-live-structural-performance',
      generatedAt: '2026-05-06T15:00:00.000Z',
      host: {
        arch: 'arm64',
        platform: 'darwin',
      },
      source: {
        artifactGenerator: 'scripts/gen-microsoft-excel-live-structural-scorecard.ts',
        implementationPackage: 'packages/headless',
        evidenceKind: 'live-local-microsoft-excel-automation',
        appleScriptTransport: 'osascript',
      },
      benchmark: {
        rowCount: 500,
        sampleCount: 5,
        screenUpdating: false,
      },
      microsoftExcel: {
        appPath: '/Applications/Microsoft Excel.app',
        version: '16.test',
      },
      summary: {
        allRequiredCasesPassed: true,
        requiredCaseCount: 6,
        tenXMeanAndP95CaseCount: 6,
        workpaperWins: 6,
        coveredOperations: ['insert-rows', 'delete-rows', 'move-rows', 'insert-columns', 'delete-columns', 'move-columns'],
        googleSheetsEvidence: 'not-covered-by-this-artifact',
      },
      cases: [
        structuralCase('excel-live-structural-insert-rows', 'insert-rows', 'rows'),
        structuralCase('excel-live-structural-delete-rows', 'delete-rows', 'rows'),
        structuralCase('excel-live-structural-move-rows', 'move-rows', 'rows'),
        structuralCase('excel-live-structural-insert-columns', 'insert-columns', 'columns'),
        structuralCase('excel-live-structural-delete-columns', 'delete-columns', 'columns'),
        structuralCase('excel-live-structural-move-columns', 'move-columns', 'columns'),
      ],
    },
    importExportFidelityScorecard: {
      schemaVersion: 1,
      suite: 'import-export-fidelity',
      generatedAt: '2026-05-06T08:00:00.000Z',
      source: {
        artifactGenerator: 'scripts/gen-import-export-fidelity-scorecard.ts',
        implementationPackage: 'packages/excel-import',
        enginePackage: 'packages/core',
        externalImportExportComparisonArtifact: 'packages/benchmarks/baselines/import-export-external-sheets-excel-comparison.json',
      },
      summary: {
        allRequiredCasesPassed: true,
        csvRoundTripPassed: true,
        xlsxImportPassed: true,
        xlsxSnapshotRoundTripPassed: true,
        coveredFeatures: [
          'csv.import',
          'xlsx.import',
          'xlsx.export',
          'xlsx.macros.payloadRoundtrip',
          'xlsx.macros.codeNameRoundtrip',
          'external.googleSheetsImportExportDocs',
          'external.microsoftExcelImportExportDocs',
          'external.sheetsExcelImportExportComparison',
        ],
        unsupportedFeatures: [],
        declinedRuntimeFeatures: ['xlsx.macros.execution'],
        externalGoogleSheetsEvidence: 'official-docs-comparison-artifact',
        externalMicrosoftExcelEvidence: 'official-docs-comparison-artifact',
      },
      cases: [
        {
          id: 'xlsx-snapshot-roundtrip-values-formulas-formats',
          format: 'xlsx',
          direction: 'export-import',
          required: true,
          passed: true,
          coveredFeatures: ['xlsx.values', 'xlsx.formulas', 'xlsx.numberFormats'],
          missingFeatures: [],
          evidence: 'fixture round-tripped',
        },
      ],
    },
    auditabilityScorecard: {
      schemaVersion: 1,
      suite: 'auditability-posture',
      generatedAt: '2026-05-06T10:00:00.000Z',
      source: {
        artifactGenerator: 'scripts/gen-auditability-scorecard.ts',
        previewImplementation: 'packages/agent-api/src/workbook-agent-preview.ts',
        applyImplementation: 'apps/bilig/src/zero/workbook-agent-apply.ts',
        authoritativeApplyImplementation: 'apps/bilig/src/zero/service.ts',
        historyImplementation: 'packages/zero-sync/src/workbook-history-state.ts',
        headedBrowserAuditabilityTestFile: 'e2e/tests/web-shell-remote-sync.pw.ts',
        externalAuditabilityComparisonArtifact: 'packages/benchmarks/baselines/auditability-external-sheets-excel-comparison.json',
      },
      summary: {
        allRequiredControlsPassed: true,
        previewApplyParityPassed: true,
        applyUndoRoundTripPassed: true,
        authoritativeApplyGuardPassed: true,
        historyRevertRedoPassed: true,
        headedBrowserRevertFlowPassed: true,
        coveredControls: [
          'agent.previewDiffParity',
          'agent.applyCapturesUndoBundle',
          'headedBrowser.previewApplyRevertFlow',
          'external.googleSheetsAuditabilityDocs',
          'external.microsoftExcelAuditabilityDocs',
          'external.sheetsExcelAuditabilityComparison',
        ],
        uncoveredControls: [],
        externalGoogleSheetsEvidence: 'official-docs-comparison-artifact',
        externalMicrosoftExcelEvidence: 'official-docs-comparison-artifact',
      },
      controls: [
        {
          id: 'agent-preview-apply-parity',
          category: 'preview-apply',
          required: true,
          passed: true,
          coveredControls: ['agent.previewDiffParity'],
          evidence: 'fixture preview matched apply',
          findings: [],
        },
      ],
    },
    automationScorecard: {
      schemaVersion: 1,
      suite: 'automation-api-extensibility',
      generatedAt: '2026-05-06T12:00:00.000Z',
      source: {
        artifactGenerator: 'scripts/gen-automation-scorecard.ts',
        commandBundleImplementation: 'packages/agent-api/src/workbook-agent-bundles.ts',
        previewImplementation: 'packages/agent-api/src/workbook-agent-preview.ts',
        headlessImplementation: 'packages/headless/src/work-paper-runtime.ts',
        workerRuntimeImplementation: 'apps/web/src/worker-runtime.ts',
        toolRegistryImplementation: 'packages/agent-api/src/workbook-agent-tool-names.ts',
        externalAutomationComparisonArtifact: 'packages/benchmarks/baselines/automation-external-sheets-excel-comparison.json',
      },
      summary: {
        allRequiredControlsPassed: true,
        semanticCommandWorkflowPassed: true,
        headlessServiceWorkflowPassed: true,
        workerPreviewWorkflowPassed: true,
        toolRegistryPassed: true,
        tenXWorkflowAutomationBenchmarkPassed: true,
        registeredToolCount: 98,
        semanticCommandKindCount: 6,
        coveredControls: [
          'agent.semanticBundleValidation',
          'headless.serviceWorkflow',
          'automation.tenXWorkflowBenchmark',
          'googleAppsScriptDirectComparison',
          'officeScriptsDirectComparison',
        ],
        uncoveredControls: [],
        externalGoogleSheetsEvidence: 'official-docs-comparison-artifact',
        externalMicrosoftExcelEvidence: 'official-docs-comparison-artifact',
      },
      controls: [
        {
          id: 'semantic-command-bundle-preview-apply',
          category: 'semantic-command-api',
          required: true,
          passed: true,
          coveredControls: ['agent.semanticBundleValidation'],
          evidence: 'fixture bundle previewed and applied',
          findings: [],
        },
      ],
    },
    collaborationScorecard: {
      schemaVersion: 1,
      suite: 'collaboration-posture',
      generatedAt: '2026-05-06T13:00:00.000Z',
      source: {
        artifactGenerator: 'scripts/gen-collaboration-scorecard.ts',
        workerRuntimeImplementation: 'apps/web/src/worker-runtime.ts',
        presenceImplementation: 'apps/web/src/workbook-presence-model.ts',
        presenceSessionImplementation: 'apps/bilig/src/workbook-runtime/document-presence-session-store.ts',
        viewportPatchImplementation: 'apps/web/src/projected-viewport-patch-application.ts',
        editorConflictImplementation: 'apps/web/src/use-workbook-editor-conflict.tsx',
        headedBrowserViewportTestFile: 'e2e/tests/web-shell-scroll-performance.pw.ts',
        externalCollaborationComparisonArtifact: 'packages/benchmarks/baselines/collaboration-external-sheets-excel-comparison.json',
      },
      summary: {
        allRequiredControlsPassed: true,
        syncRebaseAckPassed: true,
        presenceSelectionPassed: true,
        conflictViewportPassed: true,
        headedBrowserViewportPassed: true,
        longRunningConflictRatePassed: true,
        coveredControls: [
          'sync.pendingRebase',
          'presence.sessionLifecycle',
          'headedBrowser.multiUserViewportSoak',
          'conflict.longRunningZeroUnexpectedConflicts',
          'external.googleSheetsCollaborationDocs',
          'external.microsoftExcelCollaborationDocs',
          'external.sheetsExcelCollaborationComparison',
        ],
        uncoveredControls: [],
        externalGoogleSheetsEvidence: 'official-docs-comparison-artifact',
        externalMicrosoftExcelEvidence: 'official-docs-comparison-artifact',
      },
      controls: [
        {
          id: 'worker-sync-rebase-ack-roundtrip',
          category: 'local-first-sync',
          required: true,
          passed: true,
          coveredControls: ['sync.pendingRebase'],
          evidence: 'fixture pending mutations rebased and acked',
          findings: [],
        },
      ],
    },
    reliabilityScorecard: {
      schemaVersion: 1,
      suite: 'reliability-posture',
      generatedAt: '2026-05-06T11:00:00.000Z',
      source: {
        artifactGenerator: 'scripts/gen-reliability-scorecard.ts',
        workerRuntimeImplementation: 'apps/web/src/worker-runtime.ts',
        mutationJournalImplementation: 'apps/web/src/worker-runtime-mutation-journal.ts',
        zeroSyncImplementation: 'packages/zero-sync/src/schema.ts',
        headedBrowserReliabilityTestFile: 'e2e/tests/web-shell-remote-sync.pw.ts',
        externalReliabilityComparisonArtifact: 'packages/benchmarks/baselines/reliability-external-sheets-excel-comparison.json',
      },
      summary: {
        allRequiredControlsPassed: true,
        pendingReloadPassed: true,
        authoritativeAckPassed: true,
        authoritativeRebasePassed: true,
        failedRetryPassed: true,
        headedBrowserReloadPassed: true,
        headedBrowserCrashSoakPassed: true,
        offlineNetworkPartitionPassed: true,
        coveredControls: [
          'pending.localReloadSurvival',
          'zero.clientDurability',
          'headedBrowser.reloadPersistence',
          'headedBrowser.crashSoak',
          'offline.networkPartitionRecoverySoak',
          'external.googleSheetsReliabilityDocs',
          'external.microsoftExcelReliabilityDocs',
          'external.sheetsExcelReliabilityComparison',
        ],
        uncoveredControls: [],
        externalGoogleSheetsEvidence: 'official-docs-comparison-artifact',
        externalMicrosoftExcelEvidence: 'official-docs-comparison-artifact',
      },
      controls: [
        {
          id: 'pending-mutations-survive-reload',
          category: 'pending-durability',
          required: true,
          passed: true,
          coveredControls: ['pending.localReloadSurvival'],
          evidence: 'fixture pending mutation survived reload',
          findings: [],
        },
      ],
    },
    securityPostureScorecard: {
      schemaVersion: 1,
      suite: 'security-posture',
      generatedAt: '2026-05-06T09:00:00.000Z',
      source: {
        artifactGenerator: 'scripts/gen-security-posture-scorecard.ts',
        formulaRuntimeScanRoots: ['packages/formula/src'],
        importImplementation: 'packages/excel-import/src/index.ts',
        agentPolicyImplementation: 'packages/agent-api/src/workbook-agent-execution-policy.ts',
        browserSecurityHeadersImplementation: 'apps/bilig/src/http/sync-server-security-headers.ts',
        externalSecurityComparisonArtifact: 'packages/benchmarks/baselines/security-external-sheets-excel-comparison.json',
        dependencyAuditCommand: 'pnpm audit --prod --json',
        runtimePackageGate: 'pnpm publish:runtime:check',
      },
      summary: {
        allRequiredControlsPassed: true,
        formulaSandboxPassed: true,
        importSafetyPassed: true,
        agentPermissionPolicyPassed: true,
        runtimePackageHardeningPassed: true,
        browserCspPassed: true,
        dependencyAuditPassed: true,
        coveredControls: [
          'formula.noEval',
          'xlsx.macroWarning',
          'browser.contentSecurityPolicy',
          'dependency.vulnerabilityAudit',
          'external.googleSheetsSecurityDocs',
          'external.microsoftExcelSecurityDocs',
          'external.sheetsExcelSecurityComparison',
        ],
        uncoveredControls: ['deployment.runtimeNetworkPolicy'],
        externalGoogleSheetsEvidence: 'official-docs-comparison-artifact',
        externalMicrosoftExcelEvidence: 'official-docs-comparison-artifact',
      },
      controls: [
        {
          id: 'formula-runtime-no-dynamic-code-execution',
          category: 'formula-sandbox',
          required: true,
          passed: true,
          coveredControls: ['formula.noEval'],
          evidence: 'fixture scan passed',
          findings: [],
        },
      ],
    },
    largeWorkbookSloScorecard: {
      schemaVersion: 1,
      suite: 'large-workbook-slo',
      generatedAt: '2026-05-06T16:00:00.000Z',
      source: {
        benchmarkCommand: 'CI=1 pnpm bench:contracts',
        benchmarkScript: 'scripts/bench-contracts.ts',
        headedBrowserCommand: 'pnpm test:browser:full',
        headedBrowserTestFile: 'e2e/tests/web-shell-scroll-performance.pw.ts',
        artifactGenerator: 'scripts/gen-large-workbook-slo-scorecard.ts',
        externalLargeWorkbookComparisonArtifact: 'packages/benchmarks/baselines/large-workbook-external-sheets-excel-comparison.json',
        externalUiResponsivenessComparisonArtifact: 'packages/benchmarks/baselines/ui-responsiveness-external-sheets-excel-comparison.json',
      },
      summary: {
        coveredLargeWorkbookRows: [100_000, 250_000],
        allSloBudgetsPassed: true,
        allGateBudgetsPassed: true,
        headedBrowserFrameP95Evidence: 'playwright-contracts',
        headedBrowserFrameP95ContractsPassed: true,
        externalGoogleSheetsEvidence: 'official-docs-comparison-artifact',
        externalMicrosoftExcelEvidence: 'official-docs-comparison-artifact',
        externalUiResponsivenessGoogleSheetsEvidence: 'official-docs-comparison-artifact',
        externalUiResponsivenessMicrosoftExcelEvidence: 'official-docs-comparison-artifact',
      },
      measurements: [
        sloMeasurement('load100k', 'large-workbook-scale', 100_000, 230, 1500),
        sloMeasurement('load250k', 'large-workbook-scale', 250_000, 600, 1500),
        sloMeasurement('workerWarmStart100k', 'large-workbook-scale', 100_000, 12, 500),
        sloMeasurement('workerWarmStart250k', 'large-workbook-scale', 250_000, 17, 700),
        sloMeasurement('workerVisibleEdit10k', 'ui-responsiveness', 10_000, 4, 16),
        sloMeasurement('workerReconnectCatchUp100Pending', 'collaboration', 10_000, 270, 2000),
      ],
      headedBrowserFrameP95Contracts: [
        headedBrowserContract('headedDense100kDiagonalBrowse', 'large-workbook-scale', 100_000, 'dense-mixed-100k', 'frameMs.p95', 20),
        headedBrowserContract('headedWide250kMainBodyBrowse', 'large-workbook-scale', 250_000, 'wide-mixed-250k', 'frameMs.p95', 20),
        headedBrowserContract(
          'headedWide250kVisibleEditCommit',
          'ui-responsiveness',
          250_000,
          'wide-mixed-250k',
          'mutationToVisibleMs.p95',
          50,
        ),
      ],
      externalSheetsExcelComparison: {
        artifact: 'packages/benchmarks/baselines/large-workbook-external-sheets-excel-comparison.json',
        sourceBasis: 'official-public-docs-reviewed-2026-05-06',
        officialGoogleSheetsSourceCount: 5,
        officialMicrosoftExcelSourceCount: 2,
        requiredDimensionsPassed: true,
        coveredFeatures: [
          'external.googleSheetsLargeWorkbookDocs',
          'external.microsoftExcelLargeWorkbookDocs',
          'external.sheetsExcelLargeWorkbookScaleComparison',
        ],
        limitations: ['Official-docs comparison, not live timing.'],
        findings: [],
      },
      uiResponsivenessExternalSheetsExcelComparison: {
        artifact: 'packages/benchmarks/baselines/ui-responsiveness-external-sheets-excel-comparison.json',
        sourceBasis: 'official-public-docs-reviewed-2026-05-06',
        officialGoogleSheetsSourceCount: 3,
        officialMicrosoftExcelSourceCount: 4,
        requiredDimensionsPassed: true,
        coveredFeatures: [
          'external.googleSheetsUiResponsivenessDocs',
          'external.microsoftExcelUiResponsivenessDocs',
          'external.sheetsExcelUiResponsivenessComparison',
        ],
        limitations: ['Official-docs comparison, not live timing.'],
        findings: [],
      },
    },
    uiResponsivenessLiveBrowserScorecard: {
      schemaVersion: 1,
      suite: 'ui-responsiveness-live-browser-timing',
      generatedAt: '2026-05-06T20:30:00.000Z',
      host: {
        arch: 'arm64',
        platform: 'darwin',
      },
      source: {
        artifactGenerator: 'scripts/gen-ui-responsiveness-live-browser-scorecard.ts',
        evidenceKind: 'live-public-browser-playwright',
        browserEngine: 'chromium',
        measuredOperation: 'public-workbook-load-and-viewport-scroll',
      },
      benchmark: {
        sampleCount: 3,
        viewport: {
          width: 1440,
          height: 900,
        },
        samplingOrder: 'google-sheets-then-microsoft-excel-web',
      },
      summary: {
        directBrowserTimingCaptured: true,
        allRequiredCasesPassed: true,
        requiredVendorCount: 2,
        capturedVendors: ['google-sheets', 'microsoft-excel-web'],
        limitations: ['Public browser timing is not an authenticated same-corpus edit benchmark.'],
      },
      cases: [
        uiBrowserCase('google-sheets-public-grid-scroll', 'google-sheets', 'Bitcoin Transactions - Google Sheets', 'public-comment-only'),
        uiBrowserCase(
          'microsoft-excel-web-public-xlsx-scroll',
          'microsoft-excel-web',
          'Pivot-Tables-and-Charts.xlsx',
          'public-office-web-viewer',
        ),
      ],
      sameCorpusProof: {
        captured: false,
        evidenceKind: 'not-captured',
        requiredProductCount: 2,
        requiredCaseCount: 9,
        tenXMeanAndP95CaseCount: 0,
        coveredCorpusCaseIds: [],
        limitations: ['Same-corpus live browser timing against Bilig and Google Sheets has not been captured yet.'],
        cases: [],
      },
    },
    competitiveArtifact: {
      generatedAt: '2026-05-05T19:00:09.455Z',
      engines: {
        hyperformula: {
          commit: 'abc123',
          version: '3.2.0',
        },
      },
      scorecard: {
        comparableCount: 2,
        workpaperWins: 2,
        hyperformulaWins: 0,
        directionalMeanRatioGeomean: 0.2,
        directionalP95RatioGeomean: 0.25,
        worstWorkpaperToHyperFormulaMeanRatio: 0.7,
        worstMeanRatioWorkload: 'single-formula-edit-recalc',
        worstWorkpaperToHyperFormulaP95Ratio: 0.8,
        worstP95RatioWorkload: 'single-formula-edit-recalc',
      },
      families: [
        family('structural-rows', 0.7),
        family('structural-columns', 0.8),
        family('dirty-execution', 0.7),
        family('batch-edit', 0.6),
        family('rebuild', 0.05),
        family('range-read', 0.3),
        family('lookup-exact', 0.5),
        family('lookup-text', 0.4),
      ],
      results: [
        {
          workload: 'rebuild-config-toggle',
          comparable: true,
          comparison: {
            workpaperToHyperFormulaMeanRatio: 0.05,
            workpaperToHyperFormulaP95Ratio: 0.08,
          },
        },
        {
          workload: 'single-formula-edit-recalc',
          comparable: true,
          comparison: {
            workpaperToHyperFormulaMeanRatio: 0.7,
            workpaperToHyperFormulaP95Ratio: 0.8,
          },
        },
      ],
    },
  }
}

function uiBrowserCase(
  id: string,
  vendor: 'google-sheets' | 'microsoft-excel-web',
  title: string,
  accessMode: 'public-comment-only' | 'public-office-web-viewer',
): BuildScorecardInput['uiResponsivenessLiveBrowserScorecard']['cases'][number] {
  return {
    id,
    vendor,
    product: vendor === 'google-sheets' ? 'Google Sheets public spreadsheet' : 'Microsoft Office Web Viewer public XLSX',
    sourceUrl:
      vendor === 'google-sheets' ? 'https://docs.google.com/spreadsheets/d/public/edit' : 'https://view.officeapps.live.com/op/view.aspx',
    finalUrl:
      vendor === 'google-sheets'
        ? 'https://docs.google.com/spreadsheets/d/public/edit?gid=0#gid=0'
        : 'https://view.officeapps.live.com/op/view.aspx',
    title,
    accessMode,
    workload: 'open-public-workbook-and-scroll-viewport',
    sampleCount: 3,
    loadToReadyMs: numericSummary([2000, 2100, 2200]),
    scrollResponseMs: numericSummary([90, 95, 100]),
    postScrollFrameMs: numericSummary([10, 11, 12]),
    passed: true,
    limitations: ['Fixture uses representative direct browser timing limitations.'],
  }
}

function numericSummary(samples: number[]) {
  return {
    samples,
    min: samples[0] ?? 0,
    median: samples[1] ?? 0,
    p95: samples[2] ?? 0,
    max: samples[2] ?? 0,
    mean: samples.reduce((sum, value) => sum + value, 0) / samples.length,
  }
}
