import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..')

describe('headless package workflow', () => {
  it('runs current headless test files instead of stale paths', () => {
    const source = readFileSync(resolve(repoRoot, '.github/workflows/headless-package.yml'), 'utf8')
    const testPaths = [...source.matchAll(/packages\/headless\/src\/__tests__\/[A-Za-z0-9.-]+\.test\.ts/g)].map((match) => match[0])
    const scriptTestPaths = [...source.matchAll(/scripts\/__tests__\/[A-Za-z0-9.-]+\.test\.ts/g)].map((match) => match[0])

    expect(testPaths).toContain('packages/headless/src/__tests__/work-paper.test.ts')
    expect(testPaths).toContain('packages/headless/src/__tests__/work-paper-runtime.test.ts')
    expect(testPaths).toContain('packages/headless/src/__tests__/work-paper-parity.test.ts')
    expect(testPaths).toContain('packages/headless/src/__tests__/workpaper-formula-regressions.test.ts')
    expect(testPaths).toContain('packages/headless/src/__tests__/workpaper-version-surface.test.ts')
    expect(testPaths).toContain('packages/headless/src/__tests__/sum-formula-members.test.ts')
    expect(testPaths).toContain('packages/headless/src/__tests__/sumifs-wildcard-arithmetic.test.ts')
    expect(testPaths).toContain('packages/headless/src/__tests__/xlookup-decimal-exact-match.test.ts')
    expect(testPaths).toContain('packages/headless/src/__tests__/persistence.test.ts')
    expect(testPaths).toContain('packages/headless/src/__tests__/persistence.fuzz.test.ts')
    expect(testPaths).toContain('packages/headless/src/__tests__/hyperformula-surface-parity.test.ts')
    expect(scriptTestPaths).toContain('scripts/__tests__/runtime-package-publish-validation.test.ts')

    for (const testPath of [...testPaths, ...scriptTestPaths]) {
      expect(existsSync(resolve(repoRoot, testPath)), `${testPath} should exist`).toBe(true)
    }
  })

  it('keeps publish, benchmark, and clean consumer smoke gates in the package workflow', () => {
    const source = readFileSync(resolve(repoRoot, '.github/workflows/headless-package.yml'), 'utf8')
    const agentDiscoverySource = readFileSync(resolve(repoRoot, 'scripts/sync-agent-discovery-docs.ts'), 'utf8')
    const mcpDirectoryDoc = readFileSync(resolve(repoRoot, 'docs/mcp-spreadsheet-server-directory.md'), 'utf8')

    expect(source).toMatch(/['"]packages\/excel-import\/\*\*['"]/)
    expect(source).toMatch(/['"]packages\/bilig\/\*\*['"]/)
    expect(source).toMatch(/['"]packages\/workpaper\/\*\*['"]/)
    expect(source).toMatch(/['"]packages\/create-workpaper\/\*\*['"]/)
    expect(source).toMatch(/['"]packages\/xlsx-formula-recalc\/\*\*['"]/)
    expect(source).toMatch(/['"]packages\/bilig-xlsx-formula-recalc\/\*\*['"]/)
    expect(source).toMatch(/['"]packages\/sheetjs-formula-recalc\/\*\*['"]/)
    expect(source).toMatch(/['"]packages\/bilig-sheetjs-formula-recalc\/\*\*['"]/)
    expect(source).toMatch(/['"]packages\/exceljs-formula-recalc\/\*\*['"]/)
    expect(source).toMatch(/['"]packages\/bilig-exceljs-formula-recalc\/\*\*['"]/)
    expect(source).toContain('pnpm --filter @bilig/excel-import build')
    expect(source).toContain('pnpm --filter bilig-workpaper build')
    expect(source).toContain('pnpm --filter @bilig/workpaper build')
    expect(source).toContain('pnpm --filter xlsx-formula-recalc build')
    expect(source).toContain('pnpm --filter @bilig/xlsx-formula-recalc build')
    expect(source).toContain('pnpm --filter sheetjs-formula-recalc build')
    expect(source).toContain('pnpm --filter @bilig/sheetjs-formula-recalc build')
    expect(source).toContain('pnpm --filter exceljs-formula-recalc build')
    expect(source).toContain('pnpm --filter @bilig/exceljs-formula-recalc build')
    expect(source).toContain(
      'encoded_package_name="$(node -e "process.stdout.write(encodeURIComponent(process.argv[1]))" "$package_name")"',
    )
    expect(source).toContain('pnpm pack --pack-destination "$package_pack_dir"')
    expect(source).toContain('path: build/npm-packages-runtime/**/*.tgz')
    expect(source).toContain('packages/excel-import/package.json')
    expect(source).toContain('packages/excel-import')
    expect(source).toContain('packages/bilig/package.json')
    expect(source).toContain('packages/bilig')
    expect(source).toContain('packages/workpaper/package.json')
    expect(source).toContain('packages/workpaper')
    expect(source).toContain('packages/xlsx-formula-recalc/package.json')
    expect(source).toContain('packages/xlsx-formula-recalc')
    expect(source).toContain('packages/bilig-xlsx-formula-recalc/package.json')
    expect(source).toContain('packages/bilig-xlsx-formula-recalc')
    expect(source).toContain('packages/sheetjs-formula-recalc/package.json')
    expect(source).toContain('packages/sheetjs-formula-recalc')
    expect(source).toContain('packages/bilig-sheetjs-formula-recalc/package.json')
    expect(source).toContain('packages/bilig-sheetjs-formula-recalc')
    expect(source).toContain('packages/exceljs-formula-recalc/package.json')
    expect(source).toContain('packages/exceljs-formula-recalc')
    expect(source).toContain('packages/bilig-exceljs-formula-recalc/package.json')
    expect(source).toContain('packages/bilig-exceljs-formula-recalc')
    expect(source).toContain('packages/create-workpaper/package.json')
    expect(source).toContain('packages/create-workpaper')
    expect(source).toContain('scripts/check-create-workpaper-package.ts')
    expect(source).toContain('allow_new_packages')
    expect(source).toContain('ALLOW_NEW_NPM_PACKAGES')
    expect(source).toContain('skip_unprovisioned_packages')
    expect(source).toContain('SKIP_UNPROVISIONED_NPM_PACKAGES')
    expect(source).toContain('bun scripts/sync-runtime-release-metadata.ts')
    expect(source).toContain('bun scripts/sync-agent-discovery-docs.ts')
    expect(agentDiscoverySource).toContain('syncVersionedStaticReferenceLine')
    expect(agentDiscoverySource).not.toContain('replace(new RegExp(`@bilig/headless@${stableSemverPattern}`')
    expect(mcpDirectoryDoc).toContain('`io.github.proompteng/bilig-workpaper@0.27.0` with package\n`@bilig/headless@0.27.0`')
    expect(source).toContain('.release-please-manifest.json')
    expect(source).toContain('skills/bilig-workpaper/SKILL.md')
    expect(source).toContain('runner needs runtime d.ts outputs rebuilt after the version sync')
    expect(source).toContain("group: runtime-packages-${{ github.event_name == 'workflow_dispatch' && github.run_id || github.sha }}")
    expect(source).toContain('cancel-in-progress: false')
    expect(source).toContain('id: release_remotes')
    expect(source).toContain('runtime release planning skipped after verification')
    expect(source).toContain('release_from_github_mirror')
    expect(source).toContain('runtime release planning using GitHub mirror')
    expect(source).toContain('Runtime release publishing from GitHub mirror is disabled.')
    expect(source).toContain('GitHub mirror runtime tags could not be fetched; runtime release planning skipped after verification')
    expect(source).toContain('skip_release_planning()')
    expect(source).toContain('canonical Forgejo main could not be fetched; runtime release planning skipped after verification')
    expect(source).toContain('canonical Forgejo runtime tags could not be fetched; runtime release planning skipped after verification')
    expect(source).toContain('GitHub mirror main could not be fetched; runtime release planning skipped after verification')
    expect(source).toContain('RELEASE_ALIGNMENT_REASON')
    expect(source).toContain('reason=stale workflow SHA; newer main exists')
    expect(source).toContain('git push origin HEAD:main')
    expect(source).toContain('git rebase origin/main')
    expect(source).toContain('GitHub main mirrors release metadata SHA')
    expect(source).toContain('Refusing to push release metadata directly to GitHub main.')
    expect(source).toContain('GitHub tag mirror has ${TAG_NAME}')
    expect(source).toContain('Refusing to push runtime tags directly to GitHub.')
    expect(source).not.toContain('git push github')
    expect(source).toContain('git tag -a "${TAG_NAME}" -m "Libraries v${TARGET_VERSION}" HEAD')
    expect(source).toContain('Upload WorkPaper MCPB release asset')
    expect(source).toContain('npm view "@bilig/headless@${TARGET_VERSION}" version')
    expect(source).toContain('pnpm mcpb:workpaper:build -- --package-version "${TARGET_VERSION}"')
    expect(source).toContain('(cd build/mcpb && shasum -a 256 bilig-workpaper.mcpb > bilig-workpaper.mcpb.sha256)')
    expect(source).toContain('gh release upload "${TAG_NAME}"')
    expect(source).toContain('pnpm publish:runtime:check')
    expect(source).toContain('pnpm workpaper:bench:competitive:check')
    expect(source).toContain('pnpm workpaper:smoke:external')
  })
})
