import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..')

describe('headless package workflow', () => {
  it('runs current headless test files instead of stale paths', () => {
    const source = readFileSync(resolve(repoRoot, '.github/workflows/headless-package.yml'), 'utf8')
    const testPaths = [...source.matchAll(/packages\/workpaper\/src\/__tests__\/[A-Za-z0-9.-]+\.test\.ts/g)].map((match) => match[0])
    const scriptTestPaths = [...source.matchAll(/scripts\/__tests__\/[A-Za-z0-9.-]+\.test\.ts/g)].map((match) => match[0])

    expect(testPaths).toContain('packages/workpaper/src/__tests__/work-paper.test.ts')
    expect(testPaths).toContain('packages/workpaper/src/__tests__/work-paper-runtime.test.ts')
    expect(testPaths).toContain('packages/workpaper/src/__tests__/work-paper-parity.test.ts')
    expect(testPaths).toContain('packages/workpaper/src/__tests__/workpaper-formula-regressions.test.ts')
    expect(testPaths).toContain('packages/workpaper/src/__tests__/workpaper-version-surface.test.ts')
    expect(testPaths).toContain('packages/workpaper/src/__tests__/sum-formula-members.test.ts')
    expect(testPaths).toContain('packages/workpaper/src/__tests__/sumifs-wildcard-arithmetic.test.ts')
    expect(testPaths).toContain('packages/workpaper/src/__tests__/xlookup-decimal-exact-match.test.ts')
    expect(testPaths).toContain('packages/workpaper/src/__tests__/persistence.test.ts')
    expect(testPaths).toContain('packages/workpaper/src/__tests__/persistence.fuzz.test.ts')
    expect(scriptTestPaths).toContain('scripts/__tests__/runtime-package-publish-validation.test.ts')

    for (const testPath of [...testPaths, ...scriptTestPaths]) {
      expect(existsSync(resolve(repoRoot, testPath)), `${testPath} should exist`).toBe(true)
    }
  })

  it('keeps publish, benchmark, and package validation gates in the package workflow', () => {
    const source = readFileSync(resolve(repoRoot, '.github/workflows/headless-package.yml'), 'utf8')
    const biligPackageJsonSource = readFileSync(resolve(repoRoot, 'packages/workpaper/package.json'), 'utf8')
    const greenCiScript = readFileSync(resolve(repoRoot, 'scripts/wait-for-github-ci-green.mjs'), 'utf8')
    const agentDiscoverySource = readFileSync(resolve(repoRoot, 'scripts/sync-agent-discovery-docs.ts'), 'utf8')
    const staticReferenceSource = readFileSync(resolve(repoRoot, 'scripts/sync-agent-static-references.ts'), 'utf8')
    const mcpDirectoryDoc = readFileSync(resolve(repoRoot, 'docs/mcp-spreadsheet-server-directory.md'), 'utf8')
    expect(source).toMatch(/['"]packages\/excel-import\/\*\*['"]/)
    expect(source).toMatch(/['"]packages\/workbook\/\*\*['"]/)
    expect(source).toMatch(/['"]packages\/xlsx\/\*\*['"]/)
    expect(source).not.toMatch(/['"]packages\/bilig\/\*\*['"]/)
    expect(source).toMatch(/['"]packages\/workpaper\/\*\*['"]/)
    expect(source).toMatch(/['"]packages\/create-workpaper\/\*\*['"]/)
    expect(source).toMatch(/['"]packages\/xlsx-formula-recalc\/\*\*['"]/)
    expect(source).not.toMatch(/['"]packages\/bilig-xlsx-formula-recalc\/\*\*['"]/)
    expect(source).toMatch(/['"]packages\/sheetjs-formula-recalc\/\*\*['"]/)
    expect(source).not.toMatch(/['"]packages\/bilig-sheetjs-formula-recalc\/\*\*['"]/)
    expect(source).toMatch(/['"]packages\/exceljs-formula-recalc\/\*\*['"]/)
    expect(source).not.toMatch(/['"]packages\/bilig-exceljs-formula-recalc\/\*\*['"]/)
    expect(source).toMatch(/['"]integrations\/n8n-nodes-workpaper\/\*\*['"]/)
    expect(source).toContain('pnpm --filter @bilig/excel-import build')
    expect(source).toContain('pnpm --filter @bilig/xlsx build')
    expect(source).toContain('pnpm --filter @bilig/workbook build')
    expect(source).not.toContain('pnpm --filter bilig-workpaper build')
    expect(source).toContain('pnpm --filter @bilig/workpaper build')
    expect(source).toContain('pnpm --filter @bilig/xlsx-formula-recalc build')
    expect(source).toContain('pnpm --filter @bilig/sheetjs-formula-recalc build')
    expect(source).toContain('pnpm --filter @bilig/exceljs-formula-recalc build')
    const runtimeBuildBlocks = [...source.matchAll(/(?:^          pnpm --filter .+ build\n)+/gmu)]
      .map((match) => match[0])
      .filter((block) => block.includes('pnpm --filter @bilig/workpaper build'))
    expect(runtimeBuildBlocks.length).toBeGreaterThanOrEqual(3)
    for (const runtimeBuildBlock of runtimeBuildBlocks) {
      const biligXlsxBuildIndex = runtimeBuildBlock.indexOf('pnpm --filter @bilig/xlsx build')
      const excelImportBuildIndex = runtimeBuildBlock.indexOf('pnpm --filter @bilig/excel-import build')
      const scopedXlsxBuildIndex = runtimeBuildBlock.indexOf('pnpm --filter @bilig/xlsx-formula-recalc build')
      const headlessBuildIndex = runtimeBuildBlock.indexOf('pnpm --filter @bilig/workpaper build')
      expect(biligXlsxBuildIndex).toBeGreaterThanOrEqual(0)
      expect(biligXlsxBuildIndex).toBeLessThan(headlessBuildIndex)
      if (excelImportBuildIndex >= 0) {
        expect(biligXlsxBuildIndex).toBeLessThan(excelImportBuildIndex)
        expect(excelImportBuildIndex).toBeLessThan(headlessBuildIndex)
      }
      expect(scopedXlsxBuildIndex).toBeLessThan(headlessBuildIndex)
      const buildCommands = runtimeBuildBlock
        .trim()
        .split('\n')
        .map((line) => line.trim())
      expect(new Set(buildCommands).size).toBe(buildCommands.length)
    }
    const biligBuildScript = biligPackageJsonSource
    expect(biligBuildScript).toContain('pnpm --dir ../.. --filter @bilig/xlsx build')
    expect(biligBuildScript).toContain('pnpm --dir ../.. --filter @bilig/excel-import build')
    expect(biligBuildScript.indexOf('pnpm --dir ../.. --filter @bilig/xlsx build')).toBeLessThan(
      biligBuildScript.indexOf('tsc -p tsconfig.json'),
    )
    expect(source).toContain(
      'encoded_package_name="$(node -e "process.stdout.write(encodeURIComponent(process.argv[1]))" "$package_name")"',
    )
    expect(source).toContain('pnpm pack --pack-destination "$package_pack_dir"')
    expect(source).toContain('path: build/npm-packages-runtime/**/*.tgz')
    expect(source).toContain('packages/excel-import/package.json')
    expect(source).toContain('packages/excel-import')
    expect(source).toContain('packages/workbook/package.json')
    expect(source).toContain('packages/workbook')
    expect(source).toContain('packages/xlsx/package.json')
    expect(source).toContain('packages/xlsx')
    expect(source).toContain('packages/workpaper/package.json')
    expect(source).toContain('packages/workpaper')
    expect(source).toContain('packages/workpaper/package.json')
    expect(source).toContain('packages/workpaper/server.json')
    expect(source).toContain('packages/workpaper')
    expect(source).toContain('packages/xlsx-formula-recalc/package.json')
    expect(source).toContain('packages/xlsx-formula-recalc')
    expect(source).toContain('packages/xlsx-formula-recalc/package.json')
    expect(source).toContain('packages/xlsx-formula-recalc')
    expect(source).toContain('packages/sheetjs-formula-recalc/package.json')
    expect(source).toContain('packages/sheetjs-formula-recalc')
    expect(source).toContain('packages/sheetjs-formula-recalc/package.json')
    expect(source).toContain('packages/sheetjs-formula-recalc')
    expect(source).toContain('packages/exceljs-formula-recalc/package.json')
    expect(source).toContain('packages/exceljs-formula-recalc')
    expect(source).toContain('packages/exceljs-formula-recalc/package.json')
    expect(source).toContain('packages/exceljs-formula-recalc')
    expect(source).toContain('packages/create-workpaper/package.json')
    expect(source).toContain('packages/create-workpaper')
    expect(source).toContain('action.yml')
    expect(source).toContain('actions/xlsx-cache-doctor/action.yml')
    expect(source).toContain('scripts/check-create-workpaper-package.ts')
    expect(source).toContain('allow_new_packages')
    expect(source).toContain('ALLOW_NEW_NPM_PACKAGES')
    expect(source).toContain('skip_unprovisioned_packages')
    expect(source).toContain('SKIP_UNPROVISIONED_NPM_PACKAGES')
    expect(source).toContain('bun scripts/sync-runtime-release-metadata.ts')
    expect(source).toContain('bun scripts/sync-agent-discovery-docs.ts')
    expect(agentDiscoverySource).toContain('syncVersionedStaticReferences')
    expect(staticReferenceSource).toContain('syncVersionedStaticReferenceLine')
    expect(staticReferenceSource).toContain("^(\\\\s*)'@bilig/workpaper@${stableSemverPattern}'")
    expect(agentDiscoverySource).not.toContain('replace(new RegExp(`@bilig/workpaper@${stableSemverPattern}`')
    expect(mcpDirectoryDoc).toContain('npm exec --package @bilig/workpaper@latest -- bilig-workpaper-mcp')
    expect(mcpDirectoryDoc).toMatch(/current\s+repo\s+package\s+version\s+is\s+`\d+\.\d+\.\d+`/u)
    expect(source).toContain('.release-please-manifest.json')
    expect(source).toContain('gemini-extension.json')
    expect(source).toContain('skills/bilig-workpaper/SKILL.md')
    expect(source).toContain('runner needs runtime d.ts outputs rebuilt after the version sync')
    expect(source).toContain("group: runtime-packages-${{ github.event_name == 'workflow_dispatch' && github.run_id || github.sha }}")
    expect(source).toContain('cancel-in-progress: false')
    expect(source).toContain("!startsWith(github.event.head_commit.message, 'chore(release): runtime packages v')")
    expect(source).toContain("github.event_name != 'push' ||")
    expect(source).toContain('id: release_remotes')
    expect(source).toContain('runtime release planning skipped after verification')
    expect(source).toContain('release_from_github_mirror')
    expect(source).toContain('runtime release planning using GitHub mirror')
    expect(source).toContain('Runtime release publishing from GitHub mirror is disabled.')
    expect(source).toContain('GitHub mirror runtime tags could not be fetched; runtime release planning skipped after verification')
    expect(source).toContain('skip_release_planning()')
    expect(source).toContain('canonical Forgejo main could not be fetched; runtime release planning skipped after verification')
    expect(source).toContain('canonical Forgejo runtime tags could not be fetched; runtime release planning skipped after verification')
    expect(source).toContain('GitHub mirror main could not be fetched; runtime release planning skipped after verification')
    expect(source).toContain('RELEASE_ALIGNMENT_REASON')
    expect(source).toContain('reason=stale workflow SHA; newer main exists')
    expect(source).toContain('id: publish_release_alignment')
    expect(source).toContain('Report skipped stale runtime release')
    expect(source).toContain('this stale workflow run will not mutate release metadata or publish packages')
    expect(source).toContain('id: release_metadata_alignment')
    expect(source).toContain('Verify release metadata is still current')
    expect(source).toContain('release metadata SHA is stale after github-ci; newer main exists')
    expect(source).toContain('this stale workflow run will not tag, create a release, or publish packages')
    expect(source).toContain("if: steps.publish_release_alignment.outputs.current == 'true'")
    expect(source).toContain(
      "if: steps.release_metadata_alignment.outputs.current == 'true' && steps.npm_provisioning.outputs.publish_allowed != 'true'",
    )
    expect(source).toContain('git push origin HEAD:main')
    expect(source).toContain('git rebase origin/main')
    expect(source).toContain('GitHub main mirrors release metadata SHA')
    expect(source).toContain('Refusing to push release metadata directly to GitHub main.')
    expect(source).toContain('actions: read')
    expect(source).toContain('Wait for github-ci success before release mutation')
    expect(source).toContain('Wait for github-ci success before publishing release metadata')
    expect(source).toContain('Wait for github-ci success before publishing n8n node')
    expect(source).toContain('node scripts/wait-for-github-ci-green.mjs')
    expect(source).toContain('--workflow github-ci')
    expect(source).toContain('--sha "$(git rev-parse HEAD)"')
    expect(source).not.toContain(['pnpm research', 'workpaper', 'bench', 'ironcalc-rust', 'check'].join(':'))
    expect(source).not.toContain(['pnpm headless', 'performance:check'].join(':'))
    expect(source).toContain('sudo apt-get install -y --no-install-recommends librsvg2-bin')
    expect(source).toContain('rsvg-convert --version')
    expect(source).not.toContain('pnpm docs:benchmark-card:generate')
    expect(source).not.toContain('bun scripts/sync-public-evidence.ts')
    expect(source).not.toContain(['packages/benchmarks/baselines/workpaper-vs', 'ironcalc-rust.json'].join('-'))
    expect(source).not.toContain(['packages/benchmarks/baselines/headless-performance', 'leadership-scorecard.json'].join('-'))
    const runtimeGreenCiGateIndex = source.indexOf('Wait for github-ci success before release mutation')
    expect(runtimeGreenCiGateIndex).toBeLessThan(source.indexOf('Sync and commit runtime release metadata'))
    expect(runtimeGreenCiGateIndex).toBeLessThan(source.indexOf('Build runtime package chain', runtimeGreenCiGateIndex))
    const publishRuntimeJobIndex = source.indexOf('name: publish-runtime-packages')
    const rendererInstallIndex = source.indexOf('Install generated asset renderer', publishRuntimeJobIndex)
    const releaseMetadataSyncIndex = source.indexOf('Sync and commit runtime release metadata')
    const agentDiscoverySyncIndex = source.indexOf('bun scripts/sync-agent-discovery-docs.ts')
    expect(rendererInstallIndex).toBeGreaterThan(publishRuntimeJobIndex)
    expect(rendererInstallIndex).toBeLessThan(agentDiscoverySyncIndex)
    expect(agentDiscoverySyncIndex).toBeGreaterThan(releaseMetadataSyncIndex)
    const releaseMetadataGreenCiGateIndex = source.indexOf('Wait for github-ci success before publishing release metadata')
    expect(releaseMetadataGreenCiGateIndex).toBeGreaterThan(source.indexOf('Release metadata SHA: ${head_sha}'))
    const releaseMetadataAlignmentIndex = source.indexOf('Verify release metadata is still current')
    expect(releaseMetadataAlignmentIndex).toBeGreaterThan(releaseMetadataGreenCiGateIndex)
    expect(releaseMetadataAlignmentIndex).toBeLessThan(source.indexOf('Build runtime package chain', releaseMetadataAlignmentIndex))
    const n8nGreenCiGateIndex = source.indexOf('Wait for github-ci success before publishing n8n node')
    expect(n8nGreenCiGateIndex).toBeLessThan(source.indexOf('Publish n8n community node', n8nGreenCiGateIndex))
    expect(greenCiScript).toContain("const defaultWorkflowName = 'github-ci'")
    expect(greenCiScript).toContain("run.status === 'completed' && run.conclusion === 'success'")
    expect(greenCiScript).toContain("'api'")
    expect(greenCiScript).toContain('/actions/runs')
    expect(greenCiScript).toContain('head_sha=')
    expect(greenCiScript).toContain('run lookup failed')
    expect(greenCiScript).not.toContain("'run',")
    expect(greenCiScript).not.toContain("'list',")
    expect(greenCiScript).toContain('did not pass')
    expect(greenCiScript).toContain('Timed out')
    expect(source).toContain('GitHub tag mirror has ${TAG_NAME}')
    expect(source).toContain('Refusing to push runtime tags directly to GitHub.')
    expect(source).not.toContain('git push github')
    expect(source).toContain('git tag -a "${TAG_NAME}" -m "Libraries v${TARGET_VERSION}" HEAD')
    expect(source).toContain('Upload WorkPaper MCPB release asset')
    expect(source).toContain('npm view "@bilig/workpaper@${TARGET_VERSION}" version')
    expect(source).toContain('pnpm mcpb:workpaper:build -- --package-version "${TARGET_VERSION}"')
    expect(source).toContain('(cd build/mcpb && shasum -a 256 bilig-workpaper.mcpb > bilig-workpaper.mcpb.sha256)')
    expect(source).toContain('gh release upload "${TAG_NAME}"')
    expect(source).toContain('Publish MCP Registry entry')
    expect(source).toContain('npm pack "@bilig/workpaper@${TARGET_VERSION}" --pack-destination build/mcp-registry')
    expect(source).toContain('curl -fsSL "https://github.com/modelcontextprotocol/registry/releases/latest/download/mcp-publisher_')
    expect(source).toContain('./mcp-publisher login github-oidc')
    expect(source).toContain('(cd build/mcp-registry/package && ../../../mcp-publisher publish)')
    expect(source).toContain('pnpm publish:runtime:check')
    expect(source).not.toContain('pnpm workpaper:bench:competitive:check')
    expect(source).not.toContain(`pnpm ${['workpaper', 'smoke', 'external'].join(':')}`)
    expect(source).not.toContain([['hyperformula', 'surface'].join('-'), 'parity'].join('-'))
    expect(source).toContain('Verify n8n community node package')
    expect(source).toContain('cd integrations/n8n-nodes-workpaper')
    expect(source).toContain('npm run check')
    expect(source).toContain('publish_n8n_node')
    expect(source).toContain('publish_runtime_packages')
    expect(source).toContain("github.event.inputs.publish_runtime_packages != 'false'")
    expect(source).toContain('publish-n8n-workpaper-node')
    expect(source).toContain('id-token: write')
    expect(source).toContain('Using npm automation token for first-time runtime package creation')
    expect(source).toContain('if [[ "${ALLOW_NEW_NPM_PACKAGES}" == "true" && "${DRY_RUN}" != "true" ]]')
    expect(source).toContain('test -n "${NODE_AUTH_TOKEN:-}"')
    expect(source).toContain('unset NODE_AUTH_TOKEN')
    expect(source).toContain('npm publish "${publish_args[@]}"')
    expect(source).toContain('npm view "${PACKAGE_NAME}@${PACKAGE_VERSION}" version')
    expect(source).not.toContain('workbook-domain')
    expect(source).not.toContain('@bilig/workbook-domain')
    const npmPublishIndex = source.indexOf('Publish runtime package set to npm')
    const mcpbUploadIndex = source.indexOf('Upload WorkPaper MCPB release asset')
    const mcpRegistryPublishIndex = source.indexOf('Publish MCP Registry entry')
    expect(npmPublishIndex).toBeLessThan(mcpbUploadIndex)
    expect(mcpbUploadIndex).toBeLessThan(mcpRegistryPublishIndex)
  })
})
