import type { BiligDominanceScorecard, BuildScorecardInput } from './bilig-dominance-scorecard-types.ts'

export function buildBiligDominanceScorecardSummary(
  input: BuildScorecardInput,
  signals: {
    readonly calculationSemanticsPassed: boolean
    readonly tenXMeanAndP95WorkloadCountAgainstHyperFormula: number
    readonly uiResponsivenessLiveBrowserPassed: boolean
  },
): BiligDominanceScorecard['summary'] {
  return {
    auditabilityCoveredControls: input.auditabilityScorecard.summary.coveredControls,
    auditabilityPosturePassed: input.auditabilityScorecard.summary.allRequiredControlsPassed,
    auditabilityUncoveredControls: input.auditabilityScorecard.summary.uncoveredControls,
    automationCoveredControls: input.automationScorecard.summary.coveredControls,
    automationPosturePassed: input.automationScorecard.summary.allRequiredControlsPassed,
    automationRegisteredToolCount: input.automationScorecard.summary.registeredToolCount,
    automationSemanticCommandKindCount: input.automationScorecard.summary.semanticCommandKindCount,
    automationUncoveredControls: input.automationScorecard.summary.uncoveredControls,
    collaborationCoveredControls: input.collaborationScorecard.summary.coveredControls,
    collaborationPosturePassed: input.collaborationScorecard.summary.allRequiredControlsPassed,
    collaborationUncoveredControls: input.collaborationScorecard.summary.uncoveredControls,
    calculationSemanticsCoveredCanonicalFixtureCount: input.calculationSemanticsScorecard.summary.coveredCanonicalFixtureCount,
    calculationSemanticsCoveredWorkbookSemanticsFixtureCount:
      input.calculationSemanticsScorecard.summary.coveredWorkbookSemanticsFixtureCount,
    calculationSemanticsPassed: signals.calculationSemanticsPassed,
    externalGoogleSheetsEvidence: 'not-captured-in-repo',
    externalMicrosoftExcelEvidence: 'not-captured-in-repo',
    formulaCanonicalProductionPercent: input.formulaSnapshot.canonical.summary.percent,
    googleSheetsLiveCalculationEvidence: input.googleSheetsLiveCalculationScorecard.source.evidenceKind,
    googleSheetsLiveCalculationCaseCount: input.googleSheetsLiveCalculationScorecard.summary.requiredCaseCount,
    googleSheetsLiveCalculationPassed: input.googleSheetsLiveCalculationScorecard.summary.allRequiredCasesPassed,
    googleSheetsLiveCalculationSpreadsheetId: input.googleSheetsLiveCalculationScorecard.googleSheets.spreadsheetId,
    googleSheetsLiveRecalculationEvidence: input.googleSheetsLiveRecalculationScorecard.source.evidenceKind,
    googleSheetsLiveRecalculationCaseCount: input.googleSheetsLiveRecalculationScorecard.summary.requiredCaseCount,
    googleSheetsLiveRecalculationPassed: input.googleSheetsLiveRecalculationScorecard.summary.allRequiredCasesPassed,
    googleSheetsLiveRecalculationTenXMeanAndP95CaseCount: input.googleSheetsLiveRecalculationScorecard.summary.tenXMeanAndP95CaseCount,
    googleSheetsLiveRecalculationSpreadsheetIds: input.googleSheetsLiveRecalculationScorecard.googleSheets.spreadsheets.map(
      (entry) => entry.spreadsheetId,
    ),
    googleSheetsLiveStructuralEvidence: input.googleSheetsLiveStructuralScorecard.source.evidenceKind,
    googleSheetsLiveStructuralCaseCount: input.googleSheetsLiveStructuralScorecard.summary.requiredCaseCount,
    googleSheetsLiveStructuralPassed: input.googleSheetsLiveStructuralScorecard.summary.allRequiredCasesPassed,
    googleSheetsLiveStructuralTenXMeanAndP95CaseCount: input.googleSheetsLiveStructuralScorecard.summary.tenXMeanAndP95CaseCount,
    googleSheetsLiveStructuralSpreadsheetIds: input.googleSheetsLiveStructuralScorecard.googleSheets.spreadsheets.map(
      (entry) => entry.spreadsheetId,
    ),
    googleSheetsLiveLargeWorkbookEvidence: input.googleSheetsLiveLargeWorkbookScorecard.source.evidenceKind,
    googleSheetsLiveLargeWorkbookCaseCount: input.googleSheetsLiveLargeWorkbookScorecard.summary.requiredCaseCount,
    googleSheetsLiveLargeWorkbookPassed: input.googleSheetsLiveLargeWorkbookScorecard.summary.allRequiredCasesPassed,
    googleSheetsLiveLargeWorkbookTenXMeanAndP95CaseCount: input.googleSheetsLiveLargeWorkbookScorecard.summary.tenXMeanAndP95CaseCount,
    googleSheetsLiveLargeWorkbookSpreadsheetIds: input.googleSheetsLiveLargeWorkbookScorecard.googleSheets.spreadsheets.map(
      (entry) => entry.spreadsheetId,
    ),
    microsoftExcelLiveCalculationEvidence: input.microsoftExcelLiveCalculationScorecard.source.evidenceKind,
    microsoftExcelLiveCalculationCaseCount: input.microsoftExcelLiveCalculationScorecard.summary.requiredCaseCount,
    microsoftExcelLiveCalculationPassed: input.microsoftExcelLiveCalculationScorecard.summary.allRequiredCasesPassed,
    microsoftExcelLiveCalculationVersion: input.microsoftExcelLiveCalculationScorecard.microsoftExcel.version,
    microsoftExcelLiveRecalculationEvidence: input.microsoftExcelLiveRecalculationScorecard.source.evidenceKind,
    microsoftExcelLiveRecalculationCaseCount: input.microsoftExcelLiveRecalculationScorecard.summary.requiredCaseCount,
    microsoftExcelLiveRecalculationPassed: input.microsoftExcelLiveRecalculationScorecard.summary.allRequiredCasesPassed,
    microsoftExcelLiveRecalculationTenXMeanAndP95CaseCount: input.microsoftExcelLiveRecalculationScorecard.summary.tenXMeanAndP95CaseCount,
    microsoftExcelLiveRecalculationVersion: input.microsoftExcelLiveRecalculationScorecard.microsoftExcel.version,
    microsoftExcelLiveLargeWorkbookEvidence: input.microsoftExcelLiveLargeWorkbookScorecard.source.evidenceKind,
    microsoftExcelLiveLargeWorkbookCaseCount: input.microsoftExcelLiveLargeWorkbookScorecard.summary.requiredCaseCount,
    microsoftExcelLiveLargeWorkbookPassed: input.microsoftExcelLiveLargeWorkbookScorecard.summary.allRequiredCasesPassed,
    microsoftExcelLiveLargeWorkbookTenXMeanAndP95CaseCount: input.microsoftExcelLiveLargeWorkbookScorecard.summary.tenXMeanAndP95CaseCount,
    microsoftExcelLiveLargeWorkbookVersion: input.microsoftExcelLiveLargeWorkbookScorecard.microsoftExcel.version,
    microsoftExcelLiveStructuralEvidence: input.microsoftExcelLiveStructuralScorecard.source.evidenceKind,
    microsoftExcelLiveStructuralCaseCount: input.microsoftExcelLiveStructuralScorecard.summary.requiredCaseCount,
    microsoftExcelLiveStructuralPassed: input.microsoftExcelLiveStructuralScorecard.summary.allRequiredCasesPassed,
    microsoftExcelLiveStructuralTenXMeanAndP95CaseCount: input.microsoftExcelLiveStructuralScorecard.summary.tenXMeanAndP95CaseCount,
    microsoftExcelLiveStructuralVersion: input.microsoftExcelLiveStructuralScorecard.microsoftExcel.version,
    formulaOfficeListedBreadthPercent: input.formulaSnapshot.formulaBreadth.officeListed.percent,
    formulaTrackedBreadthPercent: input.formulaSnapshot.formulaBreadth.tracked.percent,
    importExportCoveredFeatures: input.importExportFidelityScorecard.summary.coveredFeatures,
    importExportDeclinedRuntimeFeatures: input.importExportFidelityScorecard.summary.declinedRuntimeFeatures,
    importExportFidelityPassed: input.importExportFidelityScorecard.summary.allRequiredCasesPassed,
    importExportUnsupportedFeatures: input.importExportFidelityScorecard.summary.unsupportedFeatures,
    largeWorkbookSloRowsCovered: input.largeWorkbookSloScorecard.summary.coveredLargeWorkbookRows,
    largeWorkbookSloPassed: input.largeWorkbookSloScorecard.summary.allSloBudgetsPassed,
    uiResponsivenessLiveBrowserPassed: signals.uiResponsivenessLiveBrowserPassed,
    uiResponsivenessLiveBrowserVendors: input.uiResponsivenessLiveBrowserScorecard.summary.capturedVendors,
    reliabilityCoveredControls: input.reliabilityScorecard.summary.coveredControls,
    reliabilityPosturePassed: input.reliabilityScorecard.summary.allRequiredControlsPassed,
    reliabilityUncoveredControls: input.reliabilityScorecard.summary.uncoveredControls,
    securityCoveredControls: input.securityPostureScorecard.summary.coveredControls,
    securityPosturePassed: input.securityPostureScorecard.summary.allRequiredControlsPassed,
    securityUncoveredControls: input.securityPostureScorecard.summary.uncoveredControls,
    hyperFormulaComparableWorkloads: input.competitiveArtifact.scorecard.comparableCount,
    hyperFormulaMeanGeomeanRatio: input.competitiveArtifact.scorecard.directionalMeanRatioGeomean,
    hyperFormulaP95GeomeanRatio: input.competitiveArtifact.scorecard.directionalP95RatioGeomean,
    hyperFormulaWins: input.competitiveArtifact.scorecard.hyperformulaWins,
    tenXMeanAndP95WorkloadCountAgainstHyperFormula: signals.tenXMeanAndP95WorkloadCountAgainstHyperFormula,
    workpaperWins: input.competitiveArtifact.scorecard.workpaperWins,
  }
}
