import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const headlessPackageVersion = readHeadlessPackageVersion()
const mcpbReleaseAssetUrl = `https://github.com/proompteng/bilig/releases/download/libraries-v${headlessPackageVersion}/bilig-workpaper.mcpb`

function readHeadlessPackageVersion(): string {
  const parsed: unknown = JSON.parse(readFileSync(join(repoRoot, 'packages', 'headless', 'package.json'), 'utf8'))
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    throw new Error('packages/headless/package.json must be an object')
  }
  const version = Reflect.get(parsed, 'version')
  if (typeof version !== 'string') {
    throw new Error('packages/headless/package.json must define a string version')
  }
  return version
}

export const homepageRequiredLinks = [
  './why-use-bilig.html',
  './why-agents-need-workbook-apis.html',
  './stop-driving-spreadsheets-with-screenshots.html',
  './show-hn-formula-workbooks-node-services.html',
  './formula-workbooks-node-services-agent-tools.html',
  './ai-agent-spreadsheet-tool-node.html',
  './headless-workpaper-agent-handbook.html',
  './agent-workpaper-tool-calling-recipe.html',
  './openai-agents-sdk-workpaper-tool.html',
  './xlsx-formula-recalculation-node.html',
  './xlsx-recalculation-proof.html',
  './xlsx-recalculation-proof.ts',
  './agent-xlsx-formula-recalculation-without-libreoffice.html',
  './stale-xlsx-formula-cache-node.html',
  './sheetjs-formula-result-not-updating-node.html',
  './xlsx-template-formula-recalculation-node.html',
  './xlsx-populate-formula-result-node.html',
  './microsoft-graph-excel-recalculation-node.html',
  './vercel-ai-sdk-langchain-spreadsheet-tool.html',
  './mcp-workpaper-tool-server.html',
  './mcp-spreadsheet-server-directory.html',
  './mcp-client-setup.html',
  './claude-desktop-mcpb-workpaper.html',
  './agent-spreadsheet-tool-call-loop.html',
  './node-service-workpaper-recipe.html',
  './server-side-spreadsheet-automation-node.html',
  './google-sheets-api-alternative-node-workpaper.html',
  './node-spreadsheet-formula-engine.html',
  './evaluate-excel-formulas-in-node-typescript.html',
  './try-bilig-headless-in-node.html',
  './quote-approval-workpaper-api.html',
  './create-bilig-workpaper.html',
  './npm-provenance-package-trust.html',
  './formula-bug-clinic.html',
  './formula-clinic-report.ts',
  './submit-workbook-fixture.html',
  './serverless-workpaper-api-route.html',
  './node-framework-workpaper-adapters.html',
  './persisting-formula-backed-workpaper-documents-in-node.html',
  'examples/serverless-workpaper-api#persistence-adapters',
  './building-a-revenue-model-with-headless-workpaper.html',
  './headless-spreadsheet-engine-comparison.html',
  './javascript-spreadsheet-library-headless-node.html',
  './hyperformula-alternative-headless-workpaper.html',
  'https://github.com/proompteng/bilig/stargazers',
  'https://github.com/proompteng/bilig/discussions/new?category=general',
] as const

export const llmsRequiredLinks = [
  'repository: https://github.com/proompteng/bilig',
  'npm workpaper package: https://www.npmjs.com/package/@bilig/workpaper',
  'npm xlsx recalculation package: https://www.npmjs.com/package/@bilig/xlsx-formula-recalc',
  'npm SheetJS recalculation package: https://www.npmjs.com/package/@bilig/sheetjs-formula-recalc',
  'npm ExcelJS recalculation package: https://www.npmjs.com/package/@bilig/exceljs-formula-recalc',
  'npm full runtime package: https://www.npmjs.com/package/@bilig/headless',
  'npx --package @bilig/xlsx-formula-recalc xlsx-recalc pricing.xlsx',
  'pnpm --dir bilig/examples/headless-workpaper run agent:tool-call',
  'pnpm --dir bilig/examples/headless-workpaper run agent:openai-agents-sdk',
  'pnpm --dir bilig/examples/headless-workpaper run agent:framework-adapters',
  'pnpm --dir bilig/examples/headless-workpaper run agent:verify',
  'https://github.com/proompteng/bilig/tree/main/examples/headless-workpaper#json-records-input',
  'https://proompteng.github.io/bilig/why-agents-need-workbook-apis.html',
  'https://proompteng.github.io/bilig/headless-workpaper-agent-handbook.html',
  'https://proompteng.github.io/bilig/AGENTS.md',
  'https://proompteng.github.io/bilig/.well-known/agent.json',
  'https://proompteng.github.io/bilig/agent.json',
  'https://proompteng.github.io/bilig/skill.txt',
  'https://proompteng.github.io/bilig/llms-full.txt',
  'https://proompteng.github.io/bilig/why-use-bilig.html',
  'https://proompteng.github.io/bilig/sheetjs-formula-result-not-updating-node.html',
  'https://github.com/proompteng/bilig/blob/main/docs/why-use-bilig.md',
  'https://proompteng.github.io/bilig/stop-driving-spreadsheets-with-screenshots.html',
  'https://proompteng.github.io/bilig/formula-workbooks-node-services-agent-tools.html',
  'https://github.com/proompteng/bilig/blob/main/docs/formula-workbooks-node-services-agent-tools.md',
  'https://proompteng.github.io/bilig/ai-agent-spreadsheet-tool-node.html',
  'https://github.com/proompteng/bilig/blob/main/docs/ai-agent-spreadsheet-tool-node.md',
  'https://proompteng.github.io/bilig/try-bilig-headless-in-node.html',
  'https://proompteng.github.io/bilig/quote-approval-workpaper-api.html',
  'https://github.com/proompteng/bilig/blob/main/docs/quote-approval-workpaper-api.md',
  'https://proompteng.github.io/bilig/vercel-ai-sdk-langchain-spreadsheet-tool.html',
  'https://proompteng.github.io/bilig/openai-agents-sdk-workpaper-tool.html',
  'https://proompteng.github.io/bilig/mcp-workpaper-tool-server.html',
  'https://proompteng.github.io/bilig/mcp-spreadsheet-server-directory.html',
  'https://proompteng.github.io/bilig/mcp-client-setup.html',
  'https://smithery.ai/servers/gkonushev/bilig-workpaper',
  'https://proompteng.github.io/bilig/claude-desktop-mcpb-workpaper.html',
  'https://github.com/proompteng/bilig/blob/main/docs/claude-desktop-mcpb-workpaper.md',
  mcpbReleaseAssetUrl,
  `${mcpbReleaseAssetUrl}.sha256`,
  'https://proompteng.github.io/bilig/agent-workpaper-tool-calling-recipe.html',
  'https://proompteng.github.io/bilig/agent-spreadsheet-tool-call-loop.html',
  'https://github.com/proompteng/bilig/blob/main/docs/headless-workpaper-agent-handbook.md',
  'https://proompteng.github.io/bilig/node-service-workpaper-recipe.html',
  'https://proompteng.github.io/bilig/server-side-spreadsheet-automation-node.html',
  'https://proompteng.github.io/bilig/google-sheets-api-alternative-node-workpaper.html',
  'https://proompteng.github.io/bilig/serverless-workpaper-api-route.html',
  'https://proompteng.github.io/bilig/node-framework-workpaper-adapters.html',
  'https://proompteng.github.io/bilig/workbook-automation-examples-node.html',
  'https://github.com/proompteng/bilig/blob/main/docs/workbook-automation-examples-node.md',
  'https://github.com/proompteng/bilig/tree/main/examples/headless-workpaper#invoice-totals',
  'https://github.com/proompteng/bilig/tree/main/examples/headless-workpaper#budget-variance-alerts',
  'https://github.com/proompteng/bilig/tree/main/examples/headless-workpaper#fulfillment-capacity-plan',
  'https://github.com/proompteng/bilig/tree/main/examples/headless-workpaper#quote-approval-threshold',
  'https://github.com/proompteng/bilig/tree/main/examples/headless-workpaper#subscription-mrr-forecast',
  'https://github.com/proompteng/bilig/tree/main/examples/serverless-workpaper-api',
  'https://github.com/proompteng/bilig/tree/main/examples/serverless-workpaper-api#framework-adapters',
  'https://github.com/proompteng/bilig/tree/main/examples/xlsx-recalculation-node',
  'https://github.com/proompteng/bilig/discussions',
  'https://github.com/proompteng/bilig/discussions/157',
  'https://github.com/proompteng/bilig/discussions/167',
  'https://github.com/proompteng/bilig/discussions/230',
  'https://github.com/proompteng/bilig/discussions/270',
  'https://github.com/proompteng/bilig/discussions/307',
  'https://github.com/proompteng/bilig/discussions/308',
  'https://github.com/proompteng/bilig/discussions/335',
  'https://github.com/proompteng/bilig/discussions/115',
  'https://proompteng.github.io/bilig/node-spreadsheet-formula-engine.html',
  'https://proompteng.github.io/bilig/evaluate-excel-formulas-in-node-typescript.html',
  'https://github.com/proompteng/bilig/blob/main/docs/node-spreadsheet-formula-engine.md',
  'https://github.com/proompteng/bilig/blob/main/docs/stop-driving-spreadsheets-with-screenshots.md',
  'https://github.com/proompteng/bilig/blob/main/docs/evaluate-excel-formulas-in-node-typescript.md',
  'https://github.com/proompteng/bilig/blob/main/docs/server-side-spreadsheet-automation-node.md',
  'https://github.com/proompteng/bilig/blob/main/docs/google-sheets-api-alternative-node-workpaper.md',
  'https://github.com/proompteng/bilig/blob/main/docs/node-service-workpaper-recipe.md',
  'https://github.com/proompteng/bilig/blob/main/docs/serverless-workpaper-api-route.md',
  'https://github.com/proompteng/bilig/blob/main/docs/node-framework-workpaper-adapters.md',
  'https://github.com/proompteng/bilig/blob/main/docs/formula-bug-clinic.md',
  'https://github.com/proompteng/bilig/blob/main/docs/formula-clinic-report.ts',
  'https://github.com/proompteng/bilig/blob/main/docs/submit-workbook-fixture.md',
  'https://github.com/proompteng/bilig/blob/main/docs/xlsx-template-formula-recalculation-node.md',
  'https://github.com/proompteng/bilig/blob/main/docs/xlsx-populate-formula-result-node.md',
  'https://github.com/proompteng/bilig/blob/main/docs/xlsx-recalculation-proof.md',
  'https://github.com/proompteng/bilig/blob/main/docs/csv-shaped-workpaper-input-recipe.md',
  'https://github.com/proompteng/bilig/blob/main/docs/unsupported-formula-troubleshooting-recipe.md',
  'https://github.com/proompteng/bilig/blob/main/docs/agent-workpaper-tool-calling-recipe.md',
  'https://github.com/proompteng/bilig/blob/main/docs/vercel-ai-sdk-langchain-spreadsheet-tool.md',
  'https://github.com/proompteng/bilig/blob/main/docs/mcp-workpaper-tool-server.md',
  'https://github.com/proompteng/bilig/blob/main/docs/mcp-spreadsheet-server-directory.md',
  'https://github.com/proompteng/bilig/blob/main/docs/mcp-client-setup.md',
  'https://proompteng.github.io/bilig/.well-known/mcp/server-card.json',
  'https://proompteng.github.io/bilig/.well-known/mcp.json',
  'https://proompteng.github.io/bilig/.well-known/mcp-server-card.json',
  'https://proompteng.github.io/bilig/.well-known/agent-skills/index.json',
  'https://proompteng.github.io/bilig/.well-known/agent-skills/bilig-workpaper/SKILL.txt',
  'https://proompteng.github.io/bilig/.well-known/skills/index.json',
  'https://proompteng.github.io/bilig/.well-known/skills/bilig-workpaper/SKILL.txt',
  'pnpm mcpb:workpaper:build',
  'https://github.com/proompteng/bilig/blob/main/examples/headless-workpaper/mcp-tool-server.ts',
  'https://github.com/proompteng/bilig/blob/main/examples/headless-workpaper/mcp-stdio-server.ts',
  'https://github.com/proompteng/bilig/blob/main/examples/headless-workpaper/agent-framework-adapters.ts',
  'https://github.com/proompteng/bilig/blob/main/docs/agent-spreadsheet-tool-call-loop.md',
  'https://github.com/proompteng/bilig/blob/main/docs/local-workpaper-benchmark-walkthrough.md',
  'https://github.com/proompteng/bilig/blob/main/docs/what-workpaper-benchmark-proves.md',
  'https://github.com/proompteng/bilig/blob/main/docs/production-adoption-checklist-headless-workpaper.md',
  'https://proompteng.github.io/bilig/npm-provenance-package-trust.html',
  'https://github.com/proompteng/bilig/blob/main/docs/npm-provenance-package-trust.md',
  'https://github.com/proompteng/bilig/blob/main/docs/hyperformula-alternative-headless-workpaper.md',
  'https://github.com/proompteng/bilig/blob/main/docs/headless-spreadsheet-engine-comparison.md',
  'https://github.com/proompteng/bilig/blob/main/docs/javascript-spreadsheet-library-headless-node.md',
  'https://github.com/proompteng/bilig/blob/main/docs/sheetjs-exceljs-alternative-formula-workbook-api.md',
  'https://github.com/proompteng/bilig/blob/main/docs/where-bilig-is-not-excel-compatible-yet.md',
  'https://github.com/proompteng/bilig/blob/main/docs/formula-edge-sumifs-paired-criteria-fixture.md',
  'https://github.com/proompteng/bilig/blob/main/docs/formula-edge-groupby-spill-fixture.md',
  'https://github.com/proompteng/bilig/blob/main/docs/new-contributor-guide.md',
  'https://github.com/proompteng/bilig/blob/main/docs/starter-issues.md',
  'https://github.com/proompteng/bilig/blob/main/SECURITY.md',
  'https://github.com/proompteng/bilig/blob/main/SUPPORT.md',
  'https://scorecard.dev/viewer/?uri=github.com/proompteng/bilig',
  'https://github.com/proompteng/bilig/issues?q=is%3Aissue%20state%3Aopen%20label%3Afirst-timers-only',
] as const
