export const communityLaunchPackRequiredLinks = [
  'Latest MCPB execution snapshot on May 13, 2026 after the Claude Desktop bundle',
  'https://proompteng.github.io/bilig/claude-desktop-mcpb-workpaper.html',
  'pnpm mcpb:workpaper:build -- --package-version 0.14.0',
  '`0.14.5` marked as latest',
  'https://github.com/proompteng/bilig/actions/runs/25868014475',
  'https://github.com/proompteng/bilig/discussions/230#discussioncomment-16920242',
  'https://github.com/proompteng/bilig/discussions/157#discussioncomment-16920401',
  'https://github.com/proompteng/bilig/issues/372',
  'Latest technical-content action on May 14, 2026',
  'https://proompteng.github.io/bilig/why-agents-need-workbook-apis.html',
  'Latest homepage polish action on May 14, 2026',
  'Headless workbooks for TypeScript services',
  'Latest TypeScript-example guard action on May 14, 2026',
  'runnable examples are TypeScript files',
  'Latest Hapi route adapter action on May 14, 2026',
  'npm run framework-adapters',
  'Latest AdonisJS route adapter action on May 14, 2026',
  'Latest Oak route adapter action on May 14, 2026',
  'https://github.com/proompteng/bilig/issues/381',
  'read_workpaper_summary',
  'set_workpaper_input_cell',
  'Latest PulseMCP verification snapshot on May 13, 2026 after the directory',
  'https://www.pulsemcp.com/servers?search=bilig&q=bilig',
  'https://proompteng.github.io/bilig/mcp-spreadsheet-server-directory.html',
  'https://github.com/krzysztofspilka/JSpreadsheets/pull/50',
  'https://github.com/zhangming1978/js-spreadsheet-benchmark/issues/1',
  'https://github.com/tolkonepiu/best-of-mcp-servers/pull/192',
  'https://github.com/MunGell/awesome-for-beginners/pull/2012',
  'https://github.com/ever-works/awesome-mcp-servers-data/pull/4',
  'https://github.com/jmstfv/mcpserve/pull/19',
  'Latest conversion snapshot on May 16, 2026',
  '`@bilig/headless@0.16.2`',
  '21,402` clones from `2,534` unique cloners',
  'https://github.com/proompteng/bilig/actions/runs/25955213169',
] as const

export const llmsExternalSurfaceLinks = [
  'https://github.com/krzysztofspilka/JSpreadsheets/pull/50',
  'https://github.com/zhangming1978/js-spreadsheet-benchmark/issues/1',
  'https://github.com/tolkonepiu/best-of-mcp-servers/pull/192',
  'https://github.com/MunGell/awesome-for-beginners/pull/2012',
  'https://github.com/ever-works/awesome-mcp-servers-data/pull/4',
  'https://github.com/jmstfv/mcpserve/pull/19',
] as const
