export function communityLaunchPackRequiredLinks(): readonly string[] {
  return [
    'Latest MCPB execution snapshot on May 13, 2026 after the Claude Desktop bundle',
    'https://proompteng.github.io/bilig/claude-desktop-mcpb-workpaper.html',
    'pnpm mcpb:workpaper:build -- --package-version 0.14.0',
    '`0.14.5` marked as latest',
    'https://github.com/proompteng/bilig/actions/runs/25868014475',
    'https://github.com/proompteng/bilig/discussions/230#discussioncomment-16920242',
    'https://github.com/proompteng/bilig/discussions/157#discussioncomment-16920401',
    'https://github.com/proompteng/bilig/issues/372',
    'Latest technical-content action on May 14, 2026',
    'https://proompteng.github.io/bilig/why-agents-need-workbook-apis.html',
    'Latest homepage polish action on May 14, 2026',
    'Headless workbooks for TypeScript services',
    'Latest TypeScript-example guard action on May 14, 2026',
    'runnable examples are TypeScript files',
    'Latest Hapi route adapter action on May 14, 2026',
    'npm run framework-adapters',
    'Latest AdonisJS route adapter action on May 14, 2026',
    'Latest Oak route adapter action on May 14, 2026',
    'https://github.com/proompteng/bilig/issues/381',
    'read_workpaper_summary',
    'set_workpaper_input_cell',
    'Latest PulseMCP verification snapshot on May 13, 2026 after the directory',
    'https://www.pulsemcp.com/servers?search=bilig&q=bilig',
    'https://proompteng.github.io/bilig/mcp-spreadsheet-server-directory.html',
    'https://github.com/krzysztofspilka/JSpreadsheets/pull/50',
    'https://github.com/statico/jsgrids/pull/94',
    'https://github.com/zhangming1978/js-spreadsheet-benchmark/issues/1',
    'https://github.com/chenz24/openawesome/issues/2#issuecomment-4467648527',
    'https://github.com/tolkonepiu/best-of-mcp-servers/pull/192',
    'https://github.com/MunGell/awesome-for-beginners/pull/2012',
    'https://github.com/ever-works/awesome-mcp-servers-data/pull/4',
    'https://github.com/jmstfv/mcpserve/pull/19',
    'https://github.com/MCPFind/mcp-find/pull/37',
    'https://github.com/mctrinh/awesome-mcp-servers/pull/46',
    'https://mcprepository.com/proompteng/bilig',
    'https://www.libhunt.com/topic/headless-spreadsheet',
    'Latest LibHunt discovery snapshot on May 17, 2026',
    'TypeScript, Spreadsheet, Excel, Agents, and `ai-agents`',
    'tools: 0',
    'package: null',
    'No Glama release',
    'glama.json',
    'Dockerfile admin page',
    'Latest conversion snapshot on May 17, 2026',
    '`@bilig/headless`',
    '28,427` clones from `3,596` unique cloners',
    'comment child `48045467` is dead',
    'comment child `48052854` is flagged',
    'JavaScript Weekly / Node Weekly Editorial Pitch',
    'editor@cooperpress.com',
    'https://github.com/proompteng/bilig/actions/runs/26002693536',
  ] as const
}

export const llmsExternalSurfaceLinks = [
  'https://github.com/krzysztofspilka/JSpreadsheets/pull/50',
  'https://github.com/statico/jsgrids/pull/94',
  'https://github.com/zhangming1978/js-spreadsheet-benchmark/issues/1',
  'https://github.com/chenz24/openawesome/issues/2#issuecomment-4467648527',
  'https://github.com/tolkonepiu/best-of-mcp-servers/pull/192',
  'https://github.com/MunGell/awesome-for-beginners/pull/2012',
  'https://github.com/ever-works/awesome-mcp-servers-data/pull/4',
  'https://github.com/jmstfv/mcpserve/pull/19',
  'https://github.com/MCPFind/mcp-find/pull/37',
  'https://github.com/mctrinh/awesome-mcp-servers/pull/46',
  'https://mcprepository.com/proompteng/bilig',
  'https://www.libhunt.com/topic/headless-spreadsheet',
] as const
