export const communityLaunchPackRequiredLinks = [
  'Latest MCPB execution snapshot on May 13, 2026 after the Claude Desktop bundle',
  'https://proompteng.github.io/bilig/claude-desktop-mcpb-workpaper.html',
  'pnpm mcpb:workpaper:build -- --package-version 0.14.0',
  '`0.14.5` marked as latest',
  'https://github.com/proompteng/bilig/actions/runs/25868014475',
  'https://github.com/proompteng/bilig/discussions/230#discussioncomment-16920242',
  'https://github.com/proompteng/bilig/discussions/157#discussioncomment-16920401',
  'https://github.com/proompteng/bilig/issues/372',
  'read_workpaper_summary',
  'set_workpaper_input_cell',
  'Latest PulseMCP verification snapshot on May 13, 2026 after the directory',
  'https://www.pulsemcp.com/servers?search=bilig&q=bilig',
  'https://proompteng.github.io/bilig/mcp-spreadsheet-server-directory.html',
  'https://github.com/krzysztofspilka/JSpreadsheets/pull/50',
  'https://github.com/zhangming1978/js-spreadsheet-benchmark/issues/1',
  'https://github.com/tolkonepiu/best-of-mcp-servers/pull/192',
  'https://github.com/MunGell/awesome-for-beginners/pull/2012',
  'https://github.com/ever-works/awesome-mcp-servers-data/pull/4',
  'https://github.com/jmstfv/mcpserve/pull/19',
  'https://proompteng.github.io/bilig/product-hunt-launch-kit.html',
] as const

export const llmsExternalSurfaceLinks = [
  'https://github.com/krzysztofspilka/JSpreadsheets/pull/50',
  'https://github.com/zhangming1978/js-spreadsheet-benchmark/issues/1',
  'https://github.com/tolkonepiu/best-of-mcp-servers/pull/192',
  'https://github.com/MunGell/awesome-for-beginners/pull/2012',
  'https://github.com/ever-works/awesome-mcp-servers-data/pull/4',
  'https://github.com/jmstfv/mcpserve/pull/19',
] as const
