#!/usr/bin/env bun

import path from "node:path";

const repoRoot = path.resolve(import.meta.dir, "..");

const enumManifest = {
  ValueTag: [
    ["Empty", 0],
    ["Number", 1],
    ["Boolean", 2],
    ["String", 3],
    ["Error", 4],
  ],
  ErrorCode: [
    ["None", 0],
    ["Div0", 1],
    ["Ref", 2],
    ["Value", 3],
    ["Name", 4],
    ["NA", 5],
    ["Cycle", 6],
    ["Spill", 7],
    ["Blocked", 8],
  ],
  FormulaMode: [
    ["JsOnly", 0],
    ["WasmFastPath", 1],
  ],
  Opcode: [
    ["PushNumber", 1],
    ["PushBoolean", 2],
    ["PushCell", 3],
    ["PushRange", 4],
    ["Add", 5],
    ["Sub", 6],
    ["Mul", 7],
    ["Div", 8],
    ["Pow", 9],
    ["Concat", 10],
    ["Neg", 11],
    ["Eq", 12],
    ["Neq", 13],
    ["Gt", 14],
    ["Gte", 15],
    ["Lt", 16],
    ["Lte", 17],
    ["Jump", 18],
    ["JumpIfFalse", 19],
    ["CallBuiltin", 20],
    ["PushString", 21],
    ["PushError", 22],
    ["Ret", 255],
  ],
  BuiltinId: [
    ["Sum", 1],
    ["Avg", 2],
    ["Min", 3],
    ["Max", 4],
    ["Count", 5],
    ["CountA", 6],
    ["Abs", 7],
    ["Round", 8],
    ["Floor", 9],
    ["Ceiling", 10],
    ["Mod", 11],
    ["If", 12],
    ["And", 13],
    ["Or", 14],
    ["Not", 15],
    ["Len", 16],
    ["Concat", 17],
    ["IsBlank", 18],
    ["IsNumber", 19],
    ["IsText", 20],
    ["Date", 21],
    ["Year", 22],
    ["Month", 23],
    ["Day", 24],
    ["Edate", 25],
    ["Eomonth", 26],
    ["Exact", 27],
    ["Int", 28],
    ["RoundUp", 29],
    ["RoundDown", 30],
    ["Time", 31],
    ["Hour", 32],
    ["Minute", 33],
    ["Second", 34],
    ["Weekday", 35],
    ["Sin", 36],
    ["Cos", 37],
    ["Tan", 38],
    ["Asin", 39],
    ["Acos", 40],
    ["Atan", 41],
    ["Atan2", 42],
    ["Degrees", 43],
    ["Radians", 44],
    ["Exp", 45],
    ["Ln", 46],
    ["Log", 47],
    ["Log10", 48],
    ["Power", 49],
    ["Sqrt", 50],
    ["Pi", 51],
    ["Ifs", 52],
    ["Switch", 53],
    ["Xor", 54],
    ["Ifna", 55],
    ["Days", 56],
    ["Workday", 57],
    ["Networkdays", 58],
    ["Weeknum", 59],
    ["Replace", 60],
    ["Substitute", 61],
    ["Rept", 62],
    ["Na", 63],
    ["Iferror", 64],
    ["Match", 65],
    ["Index", 66],
    ["Vlookup", 67],
    ["Hlookup", 68],
    ["Xlookup", 69],
    ["Xmatch", 70],
    ["Countif", 71],
    ["Countifs", 72],
    ["Sumif", 73],
    ["Sumifs", 74],
    ["Averageif", 75],
    ["Averageifs", 76],
    ["Sumproduct", 77],
    ["Left", 78],
    ["Right", 79],
    ["Mid", 80],
    ["Trim", 81],
    ["Upper", 82],
    ["Lower", 83],
    ["Find", 84],
    ["Search", 85],
    ["Value", 86],
    ["Today", 87],
    ["Now", 88],
    ["Rand", 89],
    ["Sequence", 90],
    ["Offset", 91],
    ["Take", 92],
    ["Drop", 93],
    ["Choosecols", 94],
    ["Chooserows", 95],
    ["Sort", 96],
    ["Sortby", 97],
    ["Tocol", 98],
    ["Torow", 99],
    ["Wraprows", 100],
    ["Wrapcols", 101],
    ["Lookup", 102],
    ["Areas", 103],
    ["Arraytotext", 104],
    ["Columns", 105],
    ["Rows", 106],
    ["Transpose", 107],
    ["Hstack", 108],
    ["Vstack", 109],
    ["Minifs", 110],
    ["Maxifs", 111],
    ["T", 112],
    ["N", 113],
    ["Type", 114],
    ["Delta", 115],
    ["Gestep", 116],
    ["Gauss", 117],
    ["Phi", 118],
    ["Standardize", 119],
    ["Mode", 120],
    ["ModeSngl", 121],
    ["Stdev", 122],
    ["StdevP", 123],
    ["StdevS", 124],
    ["Stdeva", 125],
    ["Stdevp", 126],
    ["Stdevpa", 127],
    ["Var", 128],
    ["VarP", 129],
    ["VarS", 130],
    ["Vara", 131],
    ["Varp", 132],
    ["Varpa", 133],
    ["Skew", 134],
    ["SkewP", 135],
    ["Kurt", 136],
    ["Normdist", 137],
    ["NormDist", 138],
    ["Norminv", 139],
    ["NormInv", 140],
    ["Normsdist", 141],
    ["NormSDist", 142],
    ["Normsinv", 143],
    ["NormSInv", 144],
    ["Loginv", 145],
    ["LognormInv", 146],
    ["Lognormdist", 147],
    ["LognormDist", 148],
    ["ConfidenceNorm", 149],
    ["Effect", 150],
    ["Nominal", 151],
    ["Pduration", 152],
    ["Rri", 153],
    ["Fv", 154],
    ["Pv", 155],
    ["Pmt", 156],
    ["Nper", 157],
    ["Npv", 158],
    ["Ipmt", 159],
    ["Ppmt", 160],
    ["Ispmt", 161],
    ["Permut", 162],
    ["Permutationa", 163],
    ["Erf", 164],
    ["ErfPrecise", 165],
    ["Erfc", 166],
    ["ErfcPrecise", 167],
    ["Fisher", 168],
    ["Fisherinv", 169],
    ["Gammaln", 170],
    ["GammalnPrecise", 171],
    ["Gamma", 172],
    ["Confidence", 173],
    ["Expondist", 174],
    ["ExponDist", 175],
    ["Poisson", 176],
    ["PoissonDist", 177],
    ["Weibull", 178],
    ["WeibullDist", 179],
    ["Gammadist", 180],
    ["GammaDist", 181],
    ["Chidist", 182],
    ["ChisqDistRt", 183],
    ["ChisqDist", 184],
    ["Binomdist", 185],
    ["BinomDist", 186],
    ["BinomDistRange", 187],
    ["Critbinom", 188],
    ["BinomInv", 189],
    ["Hypgeomdist", 190],
    ["HypgeomDist", 191],
    ["Negbinomdist", 192],
    ["NegbinomDist", 193],
    ["Filter", 194],
    ["Unique", 195],
    ["ByrowSum", 196],
    ["BycolSum", 197],
    ["ReduceSum", 198],
    ["ScanSum", 199],
    ["MakearraySum", 200],
    ["ByrowAggregate", 201],
    ["BycolAggregate", 202],
    ["ReduceProduct", 203],
    ["ScanProduct", 204],
    ["Expand", 205],
    ["Trimrange", 206],
    ["Datedif", 207],
    ["Fvschedule", 208],
    ["Db", 209],
    ["Ddb", 210],
    ["Vdb", 211],
    ["Sln", 212],
    ["Syd", 213],
  ],
};

const builtinManifest = [
  { id: "Sum", name: "SUM", supportsWasm: true },
  { id: "Avg", name: "AVG", supportsWasm: true },
  { id: "Min", name: "MIN", supportsWasm: true },
  { id: "Max", name: "MAX", supportsWasm: true },
  { id: "Count", name: "COUNT", supportsWasm: true },
  { id: "CountA", name: "COUNTA", supportsWasm: true },
  { id: "Abs", name: "ABS", supportsWasm: true },
  { id: "Round", name: "ROUND", supportsWasm: true },
  { id: "Floor", name: "FLOOR", supportsWasm: true },
  { id: "Ceiling", name: "CEILING", supportsWasm: true },
  { id: "Mod", name: "MOD", supportsWasm: true },
  { id: "If", name: "IF", supportsWasm: true },
  { id: "And", name: "AND", supportsWasm: true },
  { id: "Or", name: "OR", supportsWasm: true },
  { id: "Not", name: "NOT", supportsWasm: true },
  { id: "Len", name: "LEN", supportsWasm: true },
  { id: "Concat", name: "CONCAT", supportsWasm: true },
  { id: "IsBlank", name: "ISBLANK", supportsWasm: true },
  { id: "IsNumber", name: "ISNUMBER", supportsWasm: true },
  { id: "IsText", name: "ISTEXT", supportsWasm: true },
  { id: "Date", name: "DATE", supportsWasm: true },
  { id: "Year", name: "YEAR", supportsWasm: true },
  { id: "Month", name: "MONTH", supportsWasm: true },
  { id: "Day", name: "DAY", supportsWasm: true },
  { id: "Edate", name: "EDATE", supportsWasm: true },
  { id: "Eomonth", name: "EOMONTH", supportsWasm: true },
  { id: "Datedif", name: "DATEDIF", supportsWasm: true },
  { id: "Exact", name: "EXACT", supportsWasm: true },
  { id: "Int", name: "INT", supportsWasm: true },
  { id: "RoundUp", name: "ROUNDUP", supportsWasm: true },
  { id: "RoundDown", name: "ROUNDDOWN", supportsWasm: true },
  { id: "Time", name: "TIME", supportsWasm: true },
  { id: "Hour", name: "HOUR", supportsWasm: true },
  { id: "Minute", name: "MINUTE", supportsWasm: true },
  { id: "Second", name: "SECOND", supportsWasm: true },
  { id: "Weekday", name: "WEEKDAY", supportsWasm: true },
  { id: "Sin", name: "SIN", supportsWasm: true },
  { id: "Cos", name: "COS", supportsWasm: true },
  { id: "Tan", name: "TAN", supportsWasm: true },
  { id: "Asin", name: "ASIN", supportsWasm: true },
  { id: "Acos", name: "ACOS", supportsWasm: true },
  { id: "Atan", name: "ATAN", supportsWasm: true },
  { id: "Atan2", name: "ATAN2", supportsWasm: true },
  { id: "Degrees", name: "DEGREES", supportsWasm: true },
  { id: "Radians", name: "RADIANS", supportsWasm: true },
  { id: "Exp", name: "EXP", supportsWasm: true },
  { id: "Ln", name: "LN", supportsWasm: true },
  { id: "Log", name: "LOG", supportsWasm: true },
  { id: "Log10", name: "LOG10", supportsWasm: true },
  { id: "Power", name: "POWER", supportsWasm: true },
  { id: "Sqrt", name: "SQRT", supportsWasm: true },
  { id: "Pi", name: "PI", supportsWasm: true },
  { id: "Ifs", name: "IFS", supportsWasm: true },
  { id: "Switch", name: "SWITCH", supportsWasm: true },
  { id: "Xor", name: "XOR", supportsWasm: true },
  { id: "Ifna", name: "IFNA", supportsWasm: true },
  { id: "Days", name: "DAYS", supportsWasm: true },
  { id: "Workday", name: "WORKDAY", supportsWasm: true },
  { id: "Networkdays", name: "NETWORKDAYS", supportsWasm: true },
  { id: "Weeknum", name: "WEEKNUM", supportsWasm: true },
  { id: "Replace", name: "REPLACE", supportsWasm: true },
  { id: "Substitute", name: "SUBSTITUTE", supportsWasm: true },
  { id: "Rept", name: "REPT", supportsWasm: true },
  { id: "Na", name: "NA", supportsWasm: true },
  { id: "Iferror", name: "IFERROR", supportsWasm: true },
  { id: "Match", name: "MATCH", supportsWasm: true },
  { id: "Index", name: "INDEX", supportsWasm: true },
  { id: "Vlookup", name: "VLOOKUP", supportsWasm: true },
  { id: "Hlookup", name: "HLOOKUP", supportsWasm: true },
  { id: "Xlookup", name: "XLOOKUP", supportsWasm: true },
  { id: "Xmatch", name: "XMATCH", supportsWasm: true },
  { id: "Countif", name: "COUNTIF", supportsWasm: true },
  { id: "Countifs", name: "COUNTIFS", supportsWasm: true },
  { id: "Sumif", name: "SUMIF", supportsWasm: true },
  { id: "Sumifs", name: "SUMIFS", supportsWasm: true },
  { id: "Averageif", name: "AVERAGEIF", supportsWasm: true },
  { id: "Averageifs", name: "AVERAGEIFS", supportsWasm: true },
  { id: "Sumproduct", name: "SUMPRODUCT", supportsWasm: true },
  { id: "Left", name: "LEFT", supportsWasm: true },
  { id: "Right", name: "RIGHT", supportsWasm: true },
  { id: "Mid", name: "MID", supportsWasm: true },
  { id: "Trim", name: "TRIM", supportsWasm: true },
  { id: "Upper", name: "UPPER", supportsWasm: true },
  { id: "Lower", name: "LOWER", supportsWasm: true },
  { id: "Find", name: "FIND", supportsWasm: true },
  { id: "Search", name: "SEARCH", supportsWasm: true },
  { id: "Value", name: "VALUE", supportsWasm: true },
  { id: "Today", name: "TODAY", supportsWasm: true },
  { id: "Now", name: "NOW", supportsWasm: true },
  { id: "Rand", name: "RAND", supportsWasm: true },
  { id: "Sequence", name: "SEQUENCE", supportsWasm: true },
  { id: "Filter", name: "FILTER", supportsWasm: true },
  { id: "Unique", name: "UNIQUE", supportsWasm: true },
  { id: "ByrowSum", name: "__BYROW_SUM", supportsWasm: true },
  { id: "BycolSum", name: "__BYCOL_SUM", supportsWasm: true },
  { id: "ReduceSum", name: "__REDUCE_SUM", supportsWasm: true },
  { id: "ScanSum", name: "__SCAN_SUM", supportsWasm: true },
  { id: "MakearraySum", name: "__MAKEARRAY_SUM", supportsWasm: true },
  { id: "ByrowAggregate", name: "__BYROW_AGGREGATE", supportsWasm: true },
  { id: "BycolAggregate", name: "__BYCOL_AGGREGATE", supportsWasm: true },
  { id: "ReduceProduct", name: "__REDUCE_PRODUCT", supportsWasm: true },
  { id: "ScanProduct", name: "__SCAN_PRODUCT", supportsWasm: true },
  { id: "Offset", name: "OFFSET", supportsWasm: true },
  { id: "Take", name: "TAKE", supportsWasm: true },
  { id: "Drop", name: "DROP", supportsWasm: true },
  { id: "Expand", name: "EXPAND", supportsWasm: true },
  { id: "Trimrange", name: "TRIMRANGE", supportsWasm: true },
  { id: "Choosecols", name: "CHOOSECOLS", supportsWasm: true },
  { id: "Chooserows", name: "CHOOSEROWS", supportsWasm: true },
  { id: "Sort", name: "SORT", supportsWasm: true },
  { id: "Sortby", name: "SORTBY", supportsWasm: true },
  { id: "Tocol", name: "TOCOL", supportsWasm: true },
  { id: "Torow", name: "TOROW", supportsWasm: true },
  { id: "Wraprows", name: "WRAPROWS", supportsWasm: true },
  { id: "Wrapcols", name: "WRAPCOLS", supportsWasm: true },
  { id: "Lookup", name: "LOOKUP", supportsWasm: true },
  { id: "Areas", name: "AREAS", supportsWasm: true },
  { id: "Arraytotext", name: "ARRAYTOTEXT", supportsWasm: true },
  { id: "Columns", name: "COLUMNS", supportsWasm: true },
  { id: "Rows", name: "ROWS", supportsWasm: true },
  { id: "Transpose", name: "TRANSPOSE", supportsWasm: true },
  { id: "Hstack", name: "HSTACK", supportsWasm: true },
  { id: "Vstack", name: "VSTACK", supportsWasm: true },
  { id: "Minifs", name: "MINIFS", supportsWasm: true },
  { id: "Maxifs", name: "MAXIFS", supportsWasm: true },
  { id: "T", name: "T", supportsWasm: true },
  { id: "N", name: "N", supportsWasm: true },
  { id: "Type", name: "TYPE", supportsWasm: true },
  { id: "Delta", name: "DELTA", supportsWasm: true },
  { id: "Gestep", name: "GESTEP", supportsWasm: true },
  { id: "Gauss", name: "GAUSS", supportsWasm: true },
  { id: "Phi", name: "PHI", supportsWasm: true },
  { id: "Standardize", name: "STANDARDIZE", supportsWasm: true },
  { id: "Mode", name: "MODE", supportsWasm: true },
  { id: "ModeSngl", name: "MODE.SNGL", supportsWasm: true },
  { id: "Stdev", name: "STDEV", supportsWasm: true },
  { id: "StdevP", name: "STDEV.P", supportsWasm: true },
  { id: "StdevS", name: "STDEV.S", supportsWasm: true },
  { id: "Stdeva", name: "STDEVA", supportsWasm: true },
  { id: "Stdevp", name: "STDEVP", supportsWasm: true },
  { id: "Stdevpa", name: "STDEVPA", supportsWasm: true },
  { id: "Var", name: "VAR", supportsWasm: true },
  { id: "VarP", name: "VAR.P", supportsWasm: true },
  { id: "VarS", name: "VAR.S", supportsWasm: true },
  { id: "Vara", name: "VARA", supportsWasm: true },
  { id: "Varp", name: "VARP", supportsWasm: true },
  { id: "Varpa", name: "VARPA", supportsWasm: true },
  { id: "Skew", name: "SKEW", supportsWasm: true },
  { id: "SkewP", name: "SKEW.P", supportsWasm: true },
  { id: "Kurt", name: "KURT", supportsWasm: true },
  { id: "Normdist", name: "NORMDIST", supportsWasm: true },
  { id: "NormDist", name: "NORM.DIST", supportsWasm: true },
  { id: "Norminv", name: "NORMINV", supportsWasm: true },
  { id: "NormInv", name: "NORM.INV", supportsWasm: true },
  { id: "Normsdist", name: "NORMSDIST", supportsWasm: true },
  { id: "NormSDist", name: "NORM.S.DIST", supportsWasm: true },
  { id: "Normsinv", name: "NORMSINV", supportsWasm: true },
  { id: "NormSInv", name: "NORM.S.INV", supportsWasm: true },
  { id: "Loginv", name: "LOGINV", supportsWasm: true },
  { id: "LognormInv", name: "LOGNORM.INV", supportsWasm: true },
  { id: "Lognormdist", name: "LOGNORMDIST", supportsWasm: true },
  { id: "LognormDist", name: "LOGNORM.DIST", supportsWasm: true },
  { id: "ConfidenceNorm", name: "CONFIDENCE.NORM", supportsWasm: true },
  { id: "Effect", name: "EFFECT", supportsWasm: true },
  { id: "Nominal", name: "NOMINAL", supportsWasm: true },
  { id: "Pduration", name: "PDURATION", supportsWasm: true },
  { id: "Rri", name: "RRI", supportsWasm: true },
  { id: "Fv", name: "FV", supportsWasm: true },
  { id: "Fvschedule", name: "FVSCHEDULE", supportsWasm: true },
  { id: "Db", name: "DB", supportsWasm: true },
  { id: "Ddb", name: "DDB", supportsWasm: true },
  { id: "Vdb", name: "VDB", supportsWasm: true },
  { id: "Pv", name: "PV", supportsWasm: true },
  { id: "Pmt", name: "PMT", supportsWasm: true },
  { id: "Nper", name: "NPER", supportsWasm: true },
  { id: "Npv", name: "NPV", supportsWasm: true },
  { id: "Ipmt", name: "IPMT", supportsWasm: true },
  { id: "Ppmt", name: "PPMT", supportsWasm: true },
  { id: "Ispmt", name: "ISPMT", supportsWasm: true },
  { id: "Sln", name: "SLN", supportsWasm: true },
  { id: "Syd", name: "SYD", supportsWasm: true },
  { id: "Permut", name: "PERMUT", supportsWasm: true },
  { id: "Permutationa", name: "PERMUTATIONA", supportsWasm: true },
  { id: "Erf", name: "ERF", supportsWasm: true },
  { id: "ErfPrecise", name: "ERF.PRECISE", supportsWasm: true },
  { id: "Erfc", name: "ERFC", supportsWasm: true },
  { id: "ErfcPrecise", name: "ERFC.PRECISE", supportsWasm: true },
  { id: "Fisher", name: "FISHER", supportsWasm: true },
  { id: "Fisherinv", name: "FISHERINV", supportsWasm: true },
  { id: "Gammaln", name: "GAMMALN", supportsWasm: true },
  { id: "GammalnPrecise", name: "GAMMALN.PRECISE", supportsWasm: true },
  { id: "Gamma", name: "GAMMA", supportsWasm: true },
  { id: "Confidence", name: "CONFIDENCE", supportsWasm: true },
  { id: "Expondist", name: "EXPONDIST", supportsWasm: true },
  { id: "ExponDist", name: "EXPON.DIST", supportsWasm: true },
  { id: "Poisson", name: "POISSON", supportsWasm: true },
  { id: "PoissonDist", name: "POISSON.DIST", supportsWasm: true },
  { id: "Weibull", name: "WEIBULL", supportsWasm: true },
  { id: "WeibullDist", name: "WEIBULL.DIST", supportsWasm: true },
  { id: "Gammadist", name: "GAMMADIST", supportsWasm: true },
  { id: "GammaDist", name: "GAMMA.DIST", supportsWasm: true },
  { id: "Chidist", name: "CHIDIST", supportsWasm: true },
  { id: "ChisqDistRt", name: "CHISQ.DIST.RT", supportsWasm: true },
  { id: "ChisqDist", name: "CHISQ.DIST", supportsWasm: true },
  { id: "Binomdist", name: "BINOMDIST", supportsWasm: true },
  { id: "BinomDist", name: "BINOM.DIST", supportsWasm: true },
  { id: "BinomDistRange", name: "BINOM.DIST.RANGE", supportsWasm: true },
  { id: "Critbinom", name: "CRITBINOM", supportsWasm: true },
  { id: "BinomInv", name: "BINOM.INV", supportsWasm: true },
  { id: "Hypgeomdist", name: "HYPGEOMDIST", supportsWasm: true },
  { id: "HypgeomDist", name: "HYPGEOM.DIST", supportsWasm: true },
  { id: "Negbinomdist", name: "NEGBINOMDIST", supportsWasm: true },
  { id: "NegbinomDist", name: "NEGBINOM.DIST", supportsWasm: true },
];

const generatedHeader = `// GENERATED FILE. DO NOT EDIT DIRECTLY.\n// Source: scripts/gen-protocol.ts\n\n`;

function renderEnum(name, entries) {
  const lines = entries.map(([key, value]) => `  ${key} = ${value}`);
  return `export enum ${name} {\n${lines.join(",\n")}\n}\n`;
}

function renderProtocolEnums() {
  return (
    generatedHeader +
    Object.entries(enumManifest)
      .map(([name, entries]) => renderEnum(name, entries))
      .join("\n")
  );
}

function renderOpcodeNames() {
  return enumManifest.Opcode.map(([name]) => `  [Opcode.${name}]: "${name}"`).join(",\n");
}

function renderBuiltins() {
  return builtinManifest
    .map(
      ({ id, name, supportsWasm }) =>
        `  { id: BuiltinId.${id}, name: "${name}", supportsWasm: ${supportsWasm} }`,
    )
    .join(",\n");
}

function renderOpcodesModule() {
  return `${generatedHeader}import { BuiltinId, Opcode } from "./enums.js";

export interface BuiltinDescriptor {
  readonly id: BuiltinId;
  readonly name: string;
  readonly supportsWasm: boolean;
}

export const OPCODE_NAMES: Record<Opcode, string> = {
${renderOpcodeNames()}
};

export const BUILTINS: BuiltinDescriptor[] = [
${renderBuiltins()}
];
`;
}

const generatedFiles = [
  {
    path: path.join(repoRoot, "packages/protocol/src/enums.ts"),
    contents: renderProtocolEnums(),
  },
  {
    path: path.join(repoRoot, "packages/protocol/src/opcodes.ts"),
    contents: renderOpcodesModule(),
  },
  {
    path: path.join(repoRoot, "packages/wasm-kernel/assembly/protocol.ts"),
    contents: renderProtocolEnums(),
  },
];

async function main() {
  const checkMode = Bun.argv.includes("--check");
  const staleFiles = (
    await Promise.all(
      generatedFiles.map(async (file) => {
        let existing = "";
        try {
          existing = await Bun.file(file.path).text();
        } catch {
          existing = "";
        }

        if (existing === file.contents) {
          return null;
        }
        if (!checkMode) {
          await Bun.write(file.path, file.contents);
        }
        return path.relative(repoRoot, file.path);
      }),
    )
  ).filter((entry) => entry !== null);

  if (checkMode && staleFiles.length > 0) {
    console.error(
      `Protocol artifacts are stale:\n${staleFiles.map((entry) => `- ${entry}`).join("\n")}`,
    );
    process.exitCode = 1;
    return;
  }

  if (!checkMode) {
    if (staleFiles.length === 0) {
      console.log("Protocol artifacts are already up to date.");
      return;
    }
    console.log(
      `Updated protocol artifacts:\n${staleFiles.map((entry) => `- ${entry}`).join("\n")}`,
    );
  }
}

await main();
