#!/usr/bin/env bun

import path from "node:path";

const repoRoot = path.resolve(import.meta.dir, "..");

const enumManifest = {
  ValueTag: [
    ["Empty", 0],
    ["Number", 1],
    ["Boolean", 2],
    ["String", 3],
    ["Error", 4],
  ],
  ErrorCode: [
    ["None", 0],
    ["Div0", 1],
    ["Ref", 2],
    ["Value", 3],
    ["Name", 4],
    ["NA", 5],
    ["Cycle", 6],
    ["Spill", 7],
    ["Blocked", 8],
  ],
  FormulaMode: [
    ["JsOnly", 0],
    ["WasmFastPath", 1],
  ],
  Opcode: [
    ["PushNumber", 1],
    ["PushBoolean", 2],
    ["PushCell", 3],
    ["PushRange", 4],
    ["Add", 5],
    ["Sub", 6],
    ["Mul", 7],
    ["Div", 8],
    ["Pow", 9],
    ["Concat", 10],
    ["Neg", 11],
    ["Eq", 12],
    ["Neq", 13],
    ["Gt", 14],
    ["Gte", 15],
    ["Lt", 16],
    ["Lte", 17],
    ["Jump", 18],
    ["JumpIfFalse", 19],
    ["CallBuiltin", 20],
    ["PushString", 21],
    ["PushError", 22],
    ["Ret", 255],
  ],
  BuiltinId: [
    ["Sum", 1],
    ["Avg", 2],
    ["Min", 3],
    ["Max", 4],
    ["Count", 5],
    ["CountA", 6],
    ["Abs", 7],
    ["Round", 8],
    ["Floor", 9],
    ["Ceiling", 10],
    ["Mod", 11],
    ["If", 12],
    ["And", 13],
    ["Or", 14],
    ["Not", 15],
    ["Len", 16],
    ["Concat", 17],
    ["IsBlank", 18],
    ["IsNumber", 19],
    ["IsText", 20],
    ["Date", 21],
    ["Year", 22],
    ["Month", 23],
    ["Day", 24],
    ["Edate", 25],
    ["Eomonth", 26],
    ["Exact", 27],
    ["Int", 28],
    ["RoundUp", 29],
    ["RoundDown", 30],
    ["Time", 31],
    ["Hour", 32],
    ["Minute", 33],
    ["Second", 34],
    ["Weekday", 35],
    ["Sin", 36],
    ["Cos", 37],
    ["Tan", 38],
    ["Asin", 39],
    ["Acos", 40],
    ["Atan", 41],
    ["Atan2", 42],
    ["Degrees", 43],
    ["Radians", 44],
    ["Exp", 45],
    ["Ln", 46],
    ["Log", 47],
    ["Log10", 48],
    ["Power", 49],
    ["Sqrt", 50],
    ["Pi", 51],
    ["Ifs", 52],
    ["Switch", 53],
    ["Xor", 54],
    ["Ifna", 55],
    ["Days", 56],
    ["Workday", 57],
    ["Networkdays", 58],
    ["Weeknum", 59],
    ["Replace", 60],
    ["Substitute", 61],
    ["Rept", 62],
    ["Na", 63],
    ["Iferror", 64],
    ["Match", 65],
    ["Index", 66],
    ["Vlookup", 67],
    ["Hlookup", 68],
    ["Xlookup", 69],
    ["Xmatch", 70],
    ["Countif", 71],
    ["Countifs", 72],
    ["Sumif", 73],
    ["Sumifs", 74],
    ["Averageif", 75],
    ["Averageifs", 76],
    ["Sumproduct", 77],
    ["Left", 78],
    ["Right", 79],
    ["Mid", 80],
    ["Trim", 81],
    ["Upper", 82],
    ["Lower", 83],
    ["Find", 84],
    ["Search", 85],
    ["Value", 86],
    ["Today", 87],
    ["Now", 88],
    ["Rand", 89],
    ["Sequence", 90],
    ["Offset", 91],
    ["Take", 92],
    ["Drop", 93],
    ["Choosecols", 94],
    ["Chooserows", 95],
    ["Sort", 96],
    ["Sortby", 97],
    ["Tocol", 98],
    ["Torow", 99],
    ["Wraprows", 100],
    ["Wrapcols", 101],
    ["Lookup", 102],
    ["Areas", 103],
    ["Arraytotext", 104],
    ["Columns", 105],
    ["Rows", 106],
    ["Transpose", 107],
    ["Hstack", 108],
    ["Vstack", 109],
    ["Minifs", 110],
    ["Maxifs", 111],
    ["T", 112],
    ["N", 113],
    ["Type", 114],
    ["Delta", 115],
    ["Gestep", 116],
    ["Gauss", 117],
    ["Phi", 118],
    ["Standardize", 119],
    ["Mode", 120],
    ["ModeSngl", 121],
    ["Stdev", 122],
    ["StdevP", 123],
    ["StdevS", 124],
    ["Stdeva", 125],
    ["Stdevp", 126],
    ["Stdevpa", 127],
    ["Var", 128],
    ["VarP", 129],
    ["VarS", 130],
    ["Vara", 131],
    ["Varp", 132],
    ["Varpa", 133],
    ["Skew", 134],
    ["SkewP", 135],
    ["Kurt", 136],
    ["Normdist", 137],
    ["NormDist", 138],
    ["Norminv", 139],
    ["NormInv", 140],
    ["Normsdist", 141],
    ["NormSDist", 142],
    ["Normsinv", 143],
    ["NormSInv", 144],
    ["Loginv", 145],
    ["LognormInv", 146],
    ["Lognormdist", 147],
    ["LognormDist", 148],
    ["ConfidenceNorm", 149],
    ["Effect", 150],
    ["Nominal", 151],
    ["Pduration", 152],
    ["Rri", 153],
    ["Fv", 154],
    ["Pv", 155],
    ["Pmt", 156],
    ["Nper", 157],
    ["Npv", 158],
    ["Ipmt", 159],
    ["Ppmt", 160],
    ["Ispmt", 161],
    ["Permut", 162],
    ["Permutationa", 163],
    ["Erf", 164],
    ["ErfPrecise", 165],
    ["Erfc", 166],
    ["ErfcPrecise", 167],
    ["Fisher", 168],
    ["Fisherinv", 169],
    ["Gammaln", 170],
    ["GammalnPrecise", 171],
    ["Gamma", 172],
    ["Confidence", 173],
    ["Expondist", 174],
    ["ExponDist", 175],
    ["Poisson", 176],
    ["PoissonDist", 177],
    ["Weibull", 178],
    ["WeibullDist", 179],
    ["Gammadist", 180],
    ["GammaDist", 181],
    ["Chidist", 182],
    ["ChisqDistRt", 183],
    ["ChisqDist", 184],
    ["Binomdist", 185],
    ["BinomDist", 186],
    ["BinomDistRange", 187],
    ["Critbinom", 188],
    ["BinomInv", 189],
    ["Hypgeomdist", 190],
    ["HypgeomDist", 191],
    ["Negbinomdist", 192],
    ["NegbinomDist", 193],
    ["Filter", 194],
    ["Unique", 195],
    ["ByrowSum", 196],
    ["BycolSum", 197],
    ["ReduceSum", 198],
    ["ScanSum", 199],
    ["MakearraySum", 200],
    ["ByrowAggregate", 201],
    ["BycolAggregate", 202],
    ["GroupbySumCanonical", 203],
    ["PivotbySumCanonical", 204],
    ["ReduceProduct", 205],
    ["ScanProduct", 206],
    ["Expand", 207],
    ["Trimrange", 208],
    ["Datedif", 209],
    ["Fvschedule", 210],
    ["Db", 211],
    ["Ddb", 212],
    ["Vdb", 213],
    ["Sln", 214],
    ["Syd", 215],
    ["LegacyChidist", 216],
    ["Chiinv", 217],
    ["ChisqInvRt", 218],
    ["ChisqInv", 219],
    ["Chisqdist", 220],
    ["Chisqinv", 221],
    ["LegacyChiinv", 222],
    ["BetaDist", 223],
    ["BetaInv", 224],
    ["Betadist", 225],
    ["Betainv", 226],
    ["FDist", 227],
    ["FDistRt", 228],
    ["FInv", 229],
    ["FInvRt", 230],
    ["Fdist", 231],
    ["Finv", 232],
    ["LegacyFdist", 233],
    ["LegacyFinv", 234],
    ["ChisqTest", 235],
    ["Chitest", 236],
    ["LegacyChitest", 237],
    ["FTest", 238],
    ["Ftest", 239],
    ["ZTest", 240],
    ["Ztest", 241],
    ["WorkdayIntl", 242],
    ["NetworkdaysIntl", 243],
    ["Numbervalue", 244],
    ["Valuetotext", 245],
    ["Leftb", 246],
    ["Midb", 247],
    ["Rightb", 248],
    ["Findb", 249],
    ["Lenb", 250],
    ["Searchb", 251],
    ["Replaceb", 252],
    ["Address", 253],
    ["Dollar", 254],
    ["Dollarde", 255],
    ["Dollarfr", 256],
    ["Base", 257],
    ["Decimal", 258],
    ["Bitand", 259],
    ["Bitor", 260],
    ["Bitxor", 261],
    ["Bitlshift", 262],
    ["Bitrshift", 263],
    ["Bin2dec", 264],
    ["Bin2hex", 265],
    ["Bin2oct", 266],
    ["Dec2bin", 267],
    ["Dec2hex", 268],
    ["Dec2oct", 269],
    ["Hex2bin", 270],
    ["Hex2dec", 271],
    ["Hex2oct", 272],
    ["Oct2bin", 273],
    ["Oct2dec", 274],
    ["Oct2hex", 275],
    ["Char", 276],
    ["Code", 277],
    ["Unicode", 278],
    ["Unichar", 279],
    ["Clean", 280],
    ["Days360", 281],
    ["Yearfrac", 282],
    ["Countblank", 283],
    ["Isoweeknum", 284],
    ["Timevalue", 285],
    ["Choose", 286],
    ["Textbefore", 287],
    ["Textafter", 288],
    ["Textjoin", 289],
    ["Textsplit", 290],
    ["Correl", 291],
    ["Covar", 292],
    ["Pearson", 293],
    ["CovarianceP", 294],
    ["CovarianceS", 295],
    ["Forecast", 296],
    ["Intercept", 297],
    ["Rsq", 298],
    ["Slope", 299],
    ["Steyx", 300],
    ["Rank", 301],
    ["RankEq", 302],
    ["RankAvg", 303],
    ["Median", 304],
    ["Small", 305],
    ["Large", 306],
    ["Percentile", 307],
    ["PercentileInc", 308],
    ["PercentileExc", 309],
    ["Quartile", 310],
    ["QuartileInc", 311],
    ["QuartileExc", 312],
    ["Percentrank", 313],
    ["PercentrankInc", 314],
    ["PercentrankExc", 315],
    ["ModeMult", 316],
    ["Frequency", 317],
    ["Disc", 318],
    ["Intrate", 319],
    ["Received", 320],
    ["Pricedisc", 321],
    ["Yielddisc", 322],
    ["Tbillprice", 323],
    ["Tbillyield", 324],
    ["Tbilleq", 325],
    ["Pricemat", 326],
    ["Yieldmat", 327],
    ["Coupdaybs", 328],
    ["Coupdays", 329],
    ["Coupdaysnc", 330],
    ["Coupncd", 331],
    ["Coupnum", 332],
    ["Couppcd", 333],
    ["Price", 334],
    ["Yield", 335],
    ["Duration", 336],
    ["Mduration", 337],
    ["Rate", 338],
    ["Cumipmt", 339],
    ["Cumprinc", 340],
    ["Irr", 341],
    ["Mirr", 342],
    ["Xnpv", 343],
    ["Xirr", 344],
    ["TDist", 345],
    ["TDistRt", 346],
    ["TDist2T", 347],
    ["TInv", 348],
    ["TInv2T", 349],
    ["Tdist", 350],
    ["Tinv", 351],
    ["TTest", 352],
    ["Ttest", 353],
    ["ConfidenceT", 354],
    ["GammaInv", 355],
    ["Gammainv", 356],
    ["Asc", 357],
    ["Jis", 358],
    ["Dbcs", 359],
    ["Daverage", 360],
    ["Dcount", 361],
    ["Dcounta", 362],
    ["Dget", 363],
    ["Dmax", 364],
    ["Dmin", 365],
    ["Dproduct", 366],
    ["Dstdev", 367],
    ["Dstdevp", 368],
    ["Dsum", 369],
    ["Dvar", 370],
    ["Dvarp", 371],
    ["Prob", 372],
    ["Trimmean", 373],
    ["Growth", 374],
    ["Trend", 375],
    ["Linest", 376],
    ["Logest", 377],
    ["Besseli", 378],
    ["Besselj", 379],
    ["Besselk", 380],
    ["Bessely", 381],
    ["Convert", 382],
    ["Euroconvert", 383],
    ["Sinh", 384],
    ["Cosh", 385],
    ["Tanh", 386],
    ["Asinh", 387],
    ["Acosh", 388],
    ["Atanh", 389],
    ["Acot", 390],
    ["Acoth", 391],
    ["Cot", 392],
    ["Coth", 393],
    ["Csc", 394],
    ["Csch", 395],
    ["Sec", 396],
    ["Sech", 397],
    ["Sign", 398],
    ["Even", 399],
    ["Odd", 400],
    ["Fact", 401],
    ["Factdouble", 402],
    ["Combin", 403],
    ["Combina", 404],
    ["Gcd", 405],
    ["Lcm", 406],
    ["Product", 407],
    ["Quotient", 408],
    ["Geomean", 409],
    ["Harmean", 410],
    ["Sumsq", 411],
    ["Bahttext", 412],
    ["Oddlprice", 413],
    ["Oddlyield", 414],
    ["Oddfprice", 415],
    ["Oddfyield", 416],
    ["Text", 417],
    ["Phonetic", 418],
    ["FloorMath", 419],
    ["FloorPrecise", 420],
    ["CeilingMath", 421],
    ["CeilingPrecise", 422],
    ["IsoCeiling", 423],
    ["Trunc", 424],
    ["Mround", 425],
    ["Sqrtpi", 426],
    ["Seriessum", 427],
  ],
};

const builtinManifest = [
  { id: "Sum", name: "SUM", supportsWasm: true },
  { id: "Avg", name: "AVG", supportsWasm: true },
  { id: "Min", name: "MIN", supportsWasm: true },
  { id: "Max", name: "MAX", supportsWasm: true },
  { id: "Count", name: "COUNT", supportsWasm: true },
  { id: "CountA", name: "COUNTA", supportsWasm: true },
  { id: "Countblank", name: "COUNTBLANK", supportsWasm: true },
  { id: "Abs", name: "ABS", supportsWasm: true },
  { id: "Round", name: "ROUND", supportsWasm: true },
  { id: "Floor", name: "FLOOR", supportsWasm: true },
  { id: "Ceiling", name: "CEILING", supportsWasm: true },
  { id: "Mod", name: "MOD", supportsWasm: true },
  { id: "If", name: "IF", supportsWasm: true },
  { id: "And", name: "AND", supportsWasm: true },
  { id: "Or", name: "OR", supportsWasm: true },
  { id: "Not", name: "NOT", supportsWasm: true },
  { id: "Len", name: "LEN", supportsWasm: true },
  { id: "Concat", name: "CONCAT", supportsWasm: true },
  { id: "IsBlank", name: "ISBLANK", supportsWasm: true },
  { id: "IsNumber", name: "ISNUMBER", supportsWasm: true },
  { id: "IsText", name: "ISTEXT", supportsWasm: true },
  { id: "Date", name: "DATE", supportsWasm: true },
  { id: "Year", name: "YEAR", supportsWasm: true },
  { id: "Month", name: "MONTH", supportsWasm: true },
  { id: "Day", name: "DAY", supportsWasm: true },
  { id: "Edate", name: "EDATE", supportsWasm: true },
  { id: "Eomonth", name: "EOMONTH", supportsWasm: true },
  { id: "Datedif", name: "DATEDIF", supportsWasm: true },
  { id: "Exact", name: "EXACT", supportsWasm: true },
  { id: "Int", name: "INT", supportsWasm: true },
  { id: "RoundUp", name: "ROUNDUP", supportsWasm: true },
  { id: "RoundDown", name: "ROUNDDOWN", supportsWasm: true },
  { id: "Time", name: "TIME", supportsWasm: true },
  { id: "Hour", name: "HOUR", supportsWasm: true },
  { id: "Minute", name: "MINUTE", supportsWasm: true },
  { id: "Second", name: "SECOND", supportsWasm: true },
  { id: "Weekday", name: "WEEKDAY", supportsWasm: true },
  { id: "Sin", name: "SIN", supportsWasm: true },
  { id: "Cos", name: "COS", supportsWasm: true },
  { id: "Tan", name: "TAN", supportsWasm: true },
  { id: "Asin", name: "ASIN", supportsWasm: true },
  { id: "Acos", name: "ACOS", supportsWasm: true },
  { id: "Atan", name: "ATAN", supportsWasm: true },
  { id: "Atan2", name: "ATAN2", supportsWasm: true },
  { id: "Degrees", name: "DEGREES", supportsWasm: true },
  { id: "Radians", name: "RADIANS", supportsWasm: true },
  { id: "Exp", name: "EXP", supportsWasm: true },
  { id: "Ln", name: "LN", supportsWasm: true },
  { id: "Log", name: "LOG", supportsWasm: true },
  { id: "Log10", name: "LOG10", supportsWasm: true },
  { id: "Power", name: "POWER", supportsWasm: true },
  { id: "Sqrt", name: "SQRT", supportsWasm: true },
  { id: "Pi", name: "PI", supportsWasm: true },
  { id: "Ifs", name: "IFS", supportsWasm: true },
  { id: "Switch", name: "SWITCH", supportsWasm: true },
  { id: "Xor", name: "XOR", supportsWasm: true },
  { id: "Ifna", name: "IFNA", supportsWasm: true },
  { id: "Days", name: "DAYS", supportsWasm: true },
  { id: "Workday", name: "WORKDAY", supportsWasm: true },
  { id: "Networkdays", name: "NETWORKDAYS", supportsWasm: true },
  { id: "WorkdayIntl", name: "WORKDAY.INTL", supportsWasm: true },
  { id: "NetworkdaysIntl", name: "NETWORKDAYS.INTL", supportsWasm: true },
  { id: "Weeknum", name: "WEEKNUM", supportsWasm: true },
  { id: "Replace", name: "REPLACE", supportsWasm: true },
  { id: "Substitute", name: "SUBSTITUTE", supportsWasm: true },
  { id: "Rept", name: "REPT", supportsWasm: true },
  { id: "Na", name: "NA", supportsWasm: true },
  { id: "Iferror", name: "IFERROR", supportsWasm: true },
  { id: "Match", name: "MATCH", supportsWasm: true },
  { id: "Index", name: "INDEX", supportsWasm: true },
  { id: "Vlookup", name: "VLOOKUP", supportsWasm: true },
  { id: "Hlookup", name: "HLOOKUP", supportsWasm: true },
  { id: "Xlookup", name: "XLOOKUP", supportsWasm: true },
  { id: "Xmatch", name: "XMATCH", supportsWasm: true },
  { id: "Countif", name: "COUNTIF", supportsWasm: true },
  { id: "Countifs", name: "COUNTIFS", supportsWasm: true },
  { id: "Sumif", name: "SUMIF", supportsWasm: true },
  { id: "Sumifs", name: "SUMIFS", supportsWasm: true },
  { id: "Averageif", name: "AVERAGEIF", supportsWasm: true },
  { id: "Averageifs", name: "AVERAGEIFS", supportsWasm: true },
  { id: "Sumproduct", name: "SUMPRODUCT", supportsWasm: true },
  { id: "Left", name: "LEFT", supportsWasm: true },
  { id: "Right", name: "RIGHT", supportsWasm: true },
  { id: "Mid", name: "MID", supportsWasm: true },
  { id: "Trim", name: "TRIM", supportsWasm: true },
  { id: "Upper", name: "UPPER", supportsWasm: true },
  { id: "Lower", name: "LOWER", supportsWasm: true },
  { id: "Find", name: "FIND", supportsWasm: true },
  { id: "Search", name: "SEARCH", supportsWasm: true },
  { id: "Value", name: "VALUE", supportsWasm: true },
  { id: "Numbervalue", name: "NUMBERVALUE", supportsWasm: true },
  { id: "Valuetotext", name: "VALUETOTEXT", supportsWasm: true },
  { id: "Leftb", name: "LEFTB", supportsWasm: true },
  { id: "Midb", name: "MIDB", supportsWasm: true },
  { id: "Rightb", name: "RIGHTB", supportsWasm: true },
  { id: "Findb", name: "FINDB", supportsWasm: true },
  { id: "Lenb", name: "LENB", supportsWasm: true },
  { id: "Searchb", name: "SEARCHB", supportsWasm: true },
  { id: "Replaceb", name: "REPLACEB", supportsWasm: true },
  { id: "Address", name: "ADDRESS", supportsWasm: true },
  { id: "Dollar", name: "DOLLAR", supportsWasm: true },
  { id: "Dollarde", name: "DOLLARDE", supportsWasm: true },
  { id: "Dollarfr", name: "DOLLARFR", supportsWasm: true },
  { id: "Base", name: "BASE", supportsWasm: true },
  { id: "Decimal", name: "DECIMAL", supportsWasm: true },
  { id: "Bitand", name: "BITAND", supportsWasm: true },
  { id: "Bitor", name: "BITOR", supportsWasm: true },
  { id: "Bitxor", name: "BITXOR", supportsWasm: true },
  { id: "Bitlshift", name: "BITLSHIFT", supportsWasm: true },
  { id: "Bitrshift", name: "BITRSHIFT", supportsWasm: true },
  { id: "Besseli", name: "BESSELI", supportsWasm: true },
  { id: "Besselj", name: "BESSELJ", supportsWasm: true },
  { id: "Besselk", name: "BESSELK", supportsWasm: true },
  { id: "Bessely", name: "BESSELY", supportsWasm: true },
  { id: "Convert", name: "CONVERT", supportsWasm: true },
  { id: "Euroconvert", name: "EUROCONVERT", supportsWasm: true },
  { id: "Sinh", name: "SINH", supportsWasm: true },
  { id: "Cosh", name: "COSH", supportsWasm: true },
  { id: "Tanh", name: "TANH", supportsWasm: true },
  { id: "Asinh", name: "ASINH", supportsWasm: true },
  { id: "Acosh", name: "ACOSH", supportsWasm: true },
  { id: "Atanh", name: "ATANH", supportsWasm: true },
  { id: "Acot", name: "ACOT", supportsWasm: true },
  { id: "Acoth", name: "ACOTH", supportsWasm: true },
  { id: "Cot", name: "COT", supportsWasm: true },
  { id: "Coth", name: "COTH", supportsWasm: true },
  { id: "Csc", name: "CSC", supportsWasm: true },
  { id: "Csch", name: "CSCH", supportsWasm: true },
  { id: "Sec", name: "SEC", supportsWasm: true },
  { id: "Sech", name: "SECH", supportsWasm: true },
  { id: "Sign", name: "SIGN", supportsWasm: true },
  { id: "Even", name: "EVEN", supportsWasm: true },
  { id: "Odd", name: "ODD", supportsWasm: true },
  { id: "Fact", name: "FACT", supportsWasm: true },
  { id: "Factdouble", name: "FACTDOUBLE", supportsWasm: true },
  { id: "Combin", name: "COMBIN", supportsWasm: true },
  { id: "Combina", name: "COMBINA", supportsWasm: true },
  { id: "Gcd", name: "GCD", supportsWasm: true },
  { id: "Lcm", name: "LCM", supportsWasm: true },
  { id: "Product", name: "PRODUCT", supportsWasm: true },
  { id: "Quotient", name: "QUOTIENT", supportsWasm: true },
  { id: "Geomean", name: "GEOMEAN", supportsWasm: true },
  { id: "Harmean", name: "HARMEAN", supportsWasm: true },
  { id: "Sumsq", name: "SUMSQ", supportsWasm: true },
  { id: "Bin2dec", name: "BIN2DEC", supportsWasm: true },
  { id: "Bin2hex", name: "BIN2HEX", supportsWasm: true },
  { id: "Bin2oct", name: "BIN2OCT", supportsWasm: true },
  { id: "Dec2bin", name: "DEC2BIN", supportsWasm: true },
  { id: "Dec2hex", name: "DEC2HEX", supportsWasm: true },
  { id: "Dec2oct", name: "DEC2OCT", supportsWasm: true },
  { id: "Hex2bin", name: "HEX2BIN", supportsWasm: true },
  { id: "Hex2dec", name: "HEX2DEC", supportsWasm: true },
  { id: "Hex2oct", name: "HEX2OCT", supportsWasm: true },
  { id: "Oct2bin", name: "OCT2BIN", supportsWasm: true },
  { id: "Oct2dec", name: "OCT2DEC", supportsWasm: true },
  { id: "Oct2hex", name: "OCT2HEX", supportsWasm: true },
  { id: "Char", name: "CHAR", supportsWasm: true },
  { id: "Code", name: "CODE", supportsWasm: true },
  { id: "Unicode", name: "UNICODE", supportsWasm: true },
  { id: "Unichar", name: "UNICHAR", supportsWasm: true },
  { id: "Clean", name: "CLEAN", supportsWasm: true },
  { id: "Choose", name: "CHOOSE", supportsWasm: true },
  { id: "Textbefore", name: "TEXTBEFORE", supportsWasm: true },
  { id: "Textafter", name: "TEXTAFTER", supportsWasm: true },
  { id: "Textjoin", name: "TEXTJOIN", supportsWasm: true },
  { id: "Textsplit", name: "TEXTSPLIT", supportsWasm: true },
  { id: "Correl", name: "CORREL", supportsWasm: true },
  { id: "Covar", name: "COVAR", supportsWasm: true },
  { id: "Pearson", name: "PEARSON", supportsWasm: true },
  { id: "CovarianceP", name: "COVARIANCE.P", supportsWasm: true },
  { id: "CovarianceS", name: "COVARIANCE.S", supportsWasm: true },
  { id: "Forecast", name: "FORECAST", supportsWasm: true },
  { id: "Linest", name: "LINEST", supportsWasm: true },
  { id: "Logest", name: "LOGEST", supportsWasm: true },
  { id: "Intercept", name: "INTERCEPT", supportsWasm: true },
  { id: "Rsq", name: "RSQ", supportsWasm: true },
  { id: "Slope", name: "SLOPE", supportsWasm: true },
  { id: "Steyx", name: "STEYX", supportsWasm: true },
  { id: "Median", name: "MEDIAN", supportsWasm: true },
  { id: "Small", name: "SMALL", supportsWasm: true },
  { id: "Large", name: "LARGE", supportsWasm: true },
  { id: "Percentile", name: "PERCENTILE", supportsWasm: true },
  { id: "PercentileInc", name: "PERCENTILE.INC", supportsWasm: true },
  { id: "PercentileExc", name: "PERCENTILE.EXC", supportsWasm: true },
  { id: "Quartile", name: "QUARTILE", supportsWasm: true },
  { id: "QuartileInc", name: "QUARTILE.INC", supportsWasm: true },
  { id: "QuartileExc", name: "QUARTILE.EXC", supportsWasm: true },
  { id: "Percentrank", name: "PERCENTRANK", supportsWasm: true },
  { id: "PercentrankInc", name: "PERCENTRANK.INC", supportsWasm: true },
  { id: "PercentrankExc", name: "PERCENTRANK.EXC", supportsWasm: true },
  { id: "ModeMult", name: "MODE.MULT", supportsWasm: true },
  { id: "Frequency", name: "FREQUENCY", supportsWasm: true },
  { id: "Disc", name: "DISC", supportsWasm: true },
  { id: "Intrate", name: "INTRATE", supportsWasm: true },
  { id: "Received", name: "RECEIVED", supportsWasm: true },
  { id: "Rank", name: "RANK", supportsWasm: true },
  { id: "RankEq", name: "RANK.EQ", supportsWasm: true },
  { id: "RankAvg", name: "RANK.AVG", supportsWasm: true },
  { id: "Days360", name: "DAYS360", supportsWasm: true },
  { id: "Yearfrac", name: "YEARFRAC", supportsWasm: true },
  { id: "Today", name: "TODAY", supportsWasm: true },
  { id: "Now", name: "NOW", supportsWasm: true },
  { id: "Rand", name: "RAND", supportsWasm: true },
  { id: "Isoweeknum", name: "ISOWEEKNUM", supportsWasm: true },
  { id: "Timevalue", name: "TIMEVALUE", supportsWasm: true },
  { id: "Sequence", name: "SEQUENCE", supportsWasm: true },
  { id: "Filter", name: "FILTER", supportsWasm: true },
  { id: "Unique", name: "UNIQUE", supportsWasm: true },
  { id: "ByrowSum", name: "__BYROW_SUM", supportsWasm: true },
  { id: "BycolSum", name: "__BYCOL_SUM", supportsWasm: true },
  { id: "ReduceSum", name: "__REDUCE_SUM", supportsWasm: true },
  { id: "ScanSum", name: "__SCAN_SUM", supportsWasm: true },
  { id: "MakearraySum", name: "__MAKEARRAY_SUM", supportsWasm: true },
  { id: "ByrowAggregate", name: "__BYROW_AGGREGATE", supportsWasm: true },
  { id: "BycolAggregate", name: "__BYCOL_AGGREGATE", supportsWasm: true },
  { id: "GroupbySumCanonical", name: "__GROUPBY_SUM_CANONICAL", supportsWasm: true },
  { id: "PivotbySumCanonical", name: "__PIVOTBY_SUM_CANONICAL", supportsWasm: true },
  { id: "ReduceProduct", name: "__REDUCE_PRODUCT", supportsWasm: true },
  { id: "ScanProduct", name: "__SCAN_PRODUCT", supportsWasm: true },
  { id: "Offset", name: "OFFSET", supportsWasm: true },
  { id: "Take", name: "TAKE", supportsWasm: true },
  { id: "Drop", name: "DROP", supportsWasm: true },
  { id: "Expand", name: "EXPAND", supportsWasm: true },
  { id: "Trimrange", name: "TRIMRANGE", supportsWasm: true },
  { id: "Choosecols", name: "CHOOSECOLS", supportsWasm: true },
  { id: "Chooserows", name: "CHOOSEROWS", supportsWasm: true },
  { id: "Sort", name: "SORT", supportsWasm: true },
  { id: "Sortby", name: "SORTBY", supportsWasm: true },
  { id: "Tocol", name: "TOCOL", supportsWasm: true },
  { id: "Torow", name: "TOROW", supportsWasm: true },
  { id: "Wraprows", name: "WRAPROWS", supportsWasm: true },
  { id: "Wrapcols", name: "WRAPCOLS", supportsWasm: true },
  { id: "Lookup", name: "LOOKUP", supportsWasm: true },
  { id: "Areas", name: "AREAS", supportsWasm: true },
  { id: "Arraytotext", name: "ARRAYTOTEXT", supportsWasm: true },
  { id: "Columns", name: "COLUMNS", supportsWasm: true },
  { id: "Rows", name: "ROWS", supportsWasm: true },
  { id: "Transpose", name: "TRANSPOSE", supportsWasm: true },
  { id: "Hstack", name: "HSTACK", supportsWasm: true },
  { id: "Vstack", name: "VSTACK", supportsWasm: true },
  { id: "Minifs", name: "MINIFS", supportsWasm: true },
  { id: "Maxifs", name: "MAXIFS", supportsWasm: true },
  { id: "T", name: "T", supportsWasm: true },
  { id: "N", name: "N", supportsWasm: true },
  { id: "Type", name: "TYPE", supportsWasm: true },
  { id: "Delta", name: "DELTA", supportsWasm: true },
  { id: "Gestep", name: "GESTEP", supportsWasm: true },
  { id: "Gauss", name: "GAUSS", supportsWasm: true },
  { id: "Phi", name: "PHI", supportsWasm: true },
  { id: "Standardize", name: "STANDARDIZE", supportsWasm: true },
  { id: "Mode", name: "MODE", supportsWasm: true },
  { id: "ModeSngl", name: "MODE.SNGL", supportsWasm: true },
  { id: "Stdev", name: "STDEV", supportsWasm: true },
  { id: "StdevP", name: "STDEV.P", supportsWasm: true },
  { id: "StdevS", name: "STDEV.S", supportsWasm: true },
  { id: "Stdeva", name: "STDEVA", supportsWasm: true },
  { id: "Stdevp", name: "STDEVP", supportsWasm: true },
  { id: "Stdevpa", name: "STDEVPA", supportsWasm: true },
  { id: "Var", name: "VAR", supportsWasm: true },
  { id: "VarP", name: "VAR.P", supportsWasm: true },
  { id: "VarS", name: "VAR.S", supportsWasm: true },
  { id: "Vara", name: "VARA", supportsWasm: true },
  { id: "Varp", name: "VARP", supportsWasm: true },
  { id: "Varpa", name: "VARPA", supportsWasm: true },
  { id: "Skew", name: "SKEW", supportsWasm: true },
  { id: "SkewP", name: "SKEW.P", supportsWasm: true },
  { id: "Kurt", name: "KURT", supportsWasm: true },
  { id: "Normdist", name: "NORMDIST", supportsWasm: true },
  { id: "NormDist", name: "NORM.DIST", supportsWasm: true },
  { id: "Norminv", name: "NORMINV", supportsWasm: true },
  { id: "NormInv", name: "NORM.INV", supportsWasm: true },
  { id: "Normsdist", name: "NORMSDIST", supportsWasm: true },
  { id: "NormSDist", name: "NORM.S.DIST", supportsWasm: true },
  { id: "Normsinv", name: "NORMSINV", supportsWasm: true },
  { id: "NormSInv", name: "NORM.S.INV", supportsWasm: true },
  { id: "Loginv", name: "LOGINV", supportsWasm: true },
  { id: "LognormInv", name: "LOGNORM.INV", supportsWasm: true },
  { id: "Lognormdist", name: "LOGNORMDIST", supportsWasm: true },
  { id: "LognormDist", name: "LOGNORM.DIST", supportsWasm: true },
  { id: "ConfidenceNorm", name: "CONFIDENCE.NORM", supportsWasm: true },
  { id: "ConfidenceT", name: "CONFIDENCE.T", supportsWasm: true },
  { id: "GammaInv", name: "GAMMA.INV", supportsWasm: true },
  { id: "Gammainv", name: "GAMMAINV", supportsWasm: true },
  { id: "Effect", name: "EFFECT", supportsWasm: true },
  { id: "Nominal", name: "NOMINAL", supportsWasm: true },
  { id: "Pduration", name: "PDURATION", supportsWasm: true },
  { id: "Rri", name: "RRI", supportsWasm: true },
  { id: "Fv", name: "FV", supportsWasm: true },
  { id: "Fvschedule", name: "FVSCHEDULE", supportsWasm: true },
  { id: "Db", name: "DB", supportsWasm: true },
  { id: "Ddb", name: "DDB", supportsWasm: true },
  { id: "Vdb", name: "VDB", supportsWasm: true },
  { id: "Pv", name: "PV", supportsWasm: true },
  { id: "Pmt", name: "PMT", supportsWasm: true },
  { id: "Nper", name: "NPER", supportsWasm: true },
  { id: "Npv", name: "NPV", supportsWasm: true },
  { id: "Ipmt", name: "IPMT", supportsWasm: true },
  { id: "Ppmt", name: "PPMT", supportsWasm: true },
  { id: "Ispmt", name: "ISPMT", supportsWasm: true },
  { id: "Sln", name: "SLN", supportsWasm: true },
  { id: "Syd", name: "SYD", supportsWasm: true },
  { id: "Permut", name: "PERMUT", supportsWasm: true },
  { id: "Permutationa", name: "PERMUTATIONA", supportsWasm: true },
  { id: "Erf", name: "ERF", supportsWasm: true },
  { id: "ErfPrecise", name: "ERF.PRECISE", supportsWasm: true },
  { id: "Erfc", name: "ERFC", supportsWasm: true },
  { id: "ErfcPrecise", name: "ERFC.PRECISE", supportsWasm: true },
  { id: "Fisher", name: "FISHER", supportsWasm: true },
  { id: "Fisherinv", name: "FISHERINV", supportsWasm: true },
  { id: "Gammaln", name: "GAMMALN", supportsWasm: true },
  { id: "GammalnPrecise", name: "GAMMALN.PRECISE", supportsWasm: true },
  { id: "Gamma", name: "GAMMA", supportsWasm: true },
  { id: "Confidence", name: "CONFIDENCE", supportsWasm: true },
  { id: "Expondist", name: "EXPONDIST", supportsWasm: true },
  { id: "ExponDist", name: "EXPON.DIST", supportsWasm: true },
  { id: "Poisson", name: "POISSON", supportsWasm: true },
  { id: "PoissonDist", name: "POISSON.DIST", supportsWasm: true },
  { id: "Weibull", name: "WEIBULL", supportsWasm: true },
  { id: "WeibullDist", name: "WEIBULL.DIST", supportsWasm: true },
  { id: "Gammadist", name: "GAMMADIST", supportsWasm: true },
  { id: "GammaDist", name: "GAMMA.DIST", supportsWasm: true },
  { id: "Chidist", name: "CHIDIST", supportsWasm: true },
  { id: "LegacyChidist", name: "LEGACY.CHIDIST", supportsWasm: true },
  { id: "Chiinv", name: "CHIINV", supportsWasm: true },
  { id: "ChisqDistRt", name: "CHISQ.DIST.RT", supportsWasm: true },
  { id: "ChisqDist", name: "CHISQ.DIST", supportsWasm: true },
  { id: "ChisqInvRt", name: "CHISQ.INV.RT", supportsWasm: true },
  { id: "ChisqInv", name: "CHISQ.INV", supportsWasm: true },
  { id: "Chisqdist", name: "CHISQDIST", supportsWasm: true },
  { id: "Chisqinv", name: "CHISQINV", supportsWasm: true },
  { id: "LegacyChiinv", name: "LEGACY.CHIINV", supportsWasm: true },
  { id: "BetaDist", name: "BETA.DIST", supportsWasm: true },
  { id: "BetaInv", name: "BETA.INV", supportsWasm: true },
  { id: "Betadist", name: "BETADIST", supportsWasm: true },
  { id: "Betainv", name: "BETAINV", supportsWasm: true },
  { id: "FDist", name: "F.DIST", supportsWasm: true },
  { id: "FDistRt", name: "F.DIST.RT", supportsWasm: true },
  { id: "FInv", name: "F.INV", supportsWasm: true },
  { id: "FInvRt", name: "F.INV.RT", supportsWasm: true },
  { id: "Fdist", name: "FDIST", supportsWasm: true },
  { id: "Finv", name: "FINV", supportsWasm: true },
  { id: "LegacyFdist", name: "LEGACY.FDIST", supportsWasm: true },
  { id: "LegacyFinv", name: "LEGACY.FINV", supportsWasm: true },
  { id: "ChisqTest", name: "CHISQ.TEST", supportsWasm: true },
  { id: "Chitest", name: "CHITEST", supportsWasm: true },
  { id: "LegacyChitest", name: "LEGACY.CHITEST", supportsWasm: true },
  { id: "FTest", name: "F.TEST", supportsWasm: true },
  { id: "Ftest", name: "FTEST", supportsWasm: true },
  { id: "ZTest", name: "Z.TEST", supportsWasm: true },
  { id: "Ztest", name: "ZTEST", supportsWasm: true },
  { id: "Binomdist", name: "BINOMDIST", supportsWasm: true },
  { id: "BinomDist", name: "BINOM.DIST", supportsWasm: true },
  { id: "BinomDistRange", name: "BINOM.DIST.RANGE", supportsWasm: true },
  { id: "Critbinom", name: "CRITBINOM", supportsWasm: true },
  { id: "BinomInv", name: "BINOM.INV", supportsWasm: true },
  { id: "Hypgeomdist", name: "HYPGEOMDIST", supportsWasm: true },
  { id: "HypgeomDist", name: "HYPGEOM.DIST", supportsWasm: true },
  { id: "Negbinomdist", name: "NEGBINOMDIST", supportsWasm: true },
  { id: "NegbinomDist", name: "NEGBINOM.DIST", supportsWasm: true },
  { id: "Pricedisc", name: "PRICEDISC", supportsWasm: true },
  { id: "Yielddisc", name: "YIELDDISC", supportsWasm: true },
  { id: "Tbillprice", name: "TBILLPRICE", supportsWasm: true },
  { id: "Tbillyield", name: "TBILLYIELD", supportsWasm: true },
  { id: "Tbilleq", name: "TBILLEQ", supportsWasm: true },
  { id: "Pricemat", name: "PRICEMAT", supportsWasm: true },
  { id: "Yieldmat", name: "YIELDMAT", supportsWasm: true },
  { id: "Coupdaybs", name: "COUPDAYBS", supportsWasm: true },
  { id: "Coupdays", name: "COUPDAYS", supportsWasm: true },
  { id: "Coupdaysnc", name: "COUPDAYSNC", supportsWasm: true },
  { id: "Coupncd", name: "COUPNCD", supportsWasm: true },
  { id: "Coupnum", name: "COUPNUM", supportsWasm: true },
  { id: "Couppcd", name: "COUPPCD", supportsWasm: true },
  { id: "Price", name: "PRICE", supportsWasm: true },
  { id: "Yield", name: "YIELD", supportsWasm: true },
  { id: "Duration", name: "DURATION", supportsWasm: true },
  { id: "Mduration", name: "MDURATION", supportsWasm: true },
  { id: "Rate", name: "RATE", supportsWasm: true },
  { id: "Cumipmt", name: "CUMIPMT", supportsWasm: true },
  { id: "Cumprinc", name: "CUMPRINC", supportsWasm: true },
  { id: "Irr", name: "IRR", supportsWasm: true },
  { id: "Mirr", name: "MIRR", supportsWasm: true },
  { id: "Xnpv", name: "XNPV", supportsWasm: true },
  { id: "Xirr", name: "XIRR", supportsWasm: true },
  { id: "TDist", name: "T.DIST", supportsWasm: true },
  { id: "TDistRt", name: "T.DIST.RT", supportsWasm: true },
  { id: "TDist2T", name: "T.DIST.2T", supportsWasm: true },
  { id: "TInv", name: "T.INV", supportsWasm: true },
  { id: "TInv2T", name: "T.INV.2T", supportsWasm: true },
  { id: "Tdist", name: "TDIST", supportsWasm: true },
  { id: "Tinv", name: "TINV", supportsWasm: true },
  { id: "TTest", name: "T.TEST", supportsWasm: true },
  { id: "Ttest", name: "TTEST", supportsWasm: true },
  { id: "Asc", name: "ASC", supportsWasm: true },
  { id: "Jis", name: "JIS", supportsWasm: true },
  { id: "Dbcs", name: "DBCS", supportsWasm: true },
  { id: "Bahttext", name: "BAHTTEXT", supportsWasm: true },
  { id: "Text", name: "TEXT", supportsWasm: true },
  { id: "Phonetic", name: "PHONETIC", supportsWasm: true },
  { id: "FloorMath", name: "FLOOR.MATH", supportsWasm: true },
  { id: "FloorPrecise", name: "FLOOR.PRECISE", supportsWasm: true },
  { id: "CeilingMath", name: "CEILING.MATH", supportsWasm: true },
  { id: "CeilingPrecise", name: "CEILING.PRECISE", supportsWasm: true },
  { id: "IsoCeiling", name: "ISO.CEILING", supportsWasm: true },
  { id: "Trunc", name: "TRUNC", supportsWasm: true },
  { id: "Mround", name: "MROUND", supportsWasm: true },
  { id: "Sqrtpi", name: "SQRTPI", supportsWasm: true },
  { id: "Seriessum", name: "SERIESSUM", supportsWasm: true },
  { id: "Oddlprice", name: "ODDLPRICE", supportsWasm: true },
  { id: "Oddlyield", name: "ODDLYIELD", supportsWasm: true },
  { id: "Daverage", name: "DAVERAGE", supportsWasm: true },
  { id: "Dcount", name: "DCOUNT", supportsWasm: true },
  { id: "Dcounta", name: "DCOUNTA", supportsWasm: true },
  { id: "Dget", name: "DGET", supportsWasm: true },
  { id: "Dmax", name: "DMAX", supportsWasm: true },
  { id: "Dmin", name: "DMIN", supportsWasm: true },
  { id: "Dproduct", name: "DPRODUCT", supportsWasm: true },
  { id: "Dstdev", name: "DSTDEV", supportsWasm: true },
  { id: "Dstdevp", name: "DSTDEVP", supportsWasm: true },
  { id: "Dsum", name: "DSUM", supportsWasm: true },
  { id: "Dvar", name: "DVAR", supportsWasm: true },
  { id: "Dvarp", name: "DVARP", supportsWasm: true },
  { id: "Prob", name: "PROB", supportsWasm: true },
  { id: "Trimmean", name: "TRIMMEAN", supportsWasm: true },
  { id: "Growth", name: "GROWTH", supportsWasm: true },
  { id: "Trend", name: "TREND", supportsWasm: true },
  { id: "Oddfprice", name: "ODDFPRICE", supportsWasm: true },
  { id: "Oddfyield", name: "ODDFYIELD", supportsWasm: true },
];

const generatedHeader = `// GENERATED FILE. DO NOT EDIT DIRECTLY.\n// Source: scripts/gen-protocol.ts\n\n`;

function renderEnum(name, entries) {
  const lines = entries.map(([key, value]) => `  ${key} = ${value}`);
  return `export enum ${name} {\n${lines.join(",\n")}\n}\n`;
}

function renderProtocolEnums() {
  return (
    generatedHeader +
    Object.entries(enumManifest)
      .map(([name, entries]) => renderEnum(name, entries))
      .join("\n")
  );
}

function renderOpcodeNames() {
  return enumManifest.Opcode.map(([name]) => `  [Opcode.${name}]: "${name}"`).join(",\n");
}

function renderBuiltins() {
  return builtinManifest
    .map(
      ({ id, name, supportsWasm }) =>
        `  { id: BuiltinId.${id}, name: "${name}", supportsWasm: ${supportsWasm} }`,
    )
    .join(",\n");
}

function renderOpcodesModule() {
  return `${generatedHeader}import { BuiltinId, Opcode } from "./enums.js";

export interface BuiltinDescriptor {
  readonly id: BuiltinId;
  readonly name: string;
  readonly supportsWasm: boolean;
}

export const OPCODE_NAMES: Record<Opcode, string> = {
${renderOpcodeNames()}
};

export const BUILTINS: BuiltinDescriptor[] = [
${renderBuiltins()}
];
`;
}

const generatedFiles = [
  {
    path: path.join(repoRoot, "packages/protocol/src/enums.ts"),
    contents: renderProtocolEnums(),
  },
  {
    path: path.join(repoRoot, "packages/protocol/src/opcodes.ts"),
    contents: renderOpcodesModule(),
  },
  {
    path: path.join(repoRoot, "packages/wasm-kernel/assembly/protocol.ts"),
    contents: renderProtocolEnums(),
  },
];

async function main() {
  const checkMode = Bun.argv.includes("--check");
  const staleFiles = (
    await Promise.all(
      generatedFiles.map(async (file) => {
        let existing = "";
        try {
          existing = await Bun.file(file.path).text();
        } catch {
          existing = "";
        }

        if (existing === file.contents) {
          return null;
        }
        if (!checkMode) {
          await Bun.write(file.path, file.contents);
        }
        return path.relative(repoRoot, file.path);
      }),
    )
  ).filter((entry) => entry !== null);

  if (checkMode && staleFiles.length > 0) {
    console.error(
      `Protocol artifacts are stale:\n${staleFiles.map((entry) => `- ${entry}`).join("\n")}`,
    );
    process.exitCode = 1;
    return;
  }

  if (!checkMode) {
    if (staleFiles.length === 0) {
      console.log("Protocol artifacts are already up to date.");
      return;
    }
    console.log(
      `Updated protocol artifacts:\n${staleFiles.map((entry) => `- ${entry}`).join("\n")}`,
    );
  }
}

await main();
