import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

export function writeXlsxImportScript(projectDir: string): void {
  writeFileSync(
    join(projectDir, 'xlsx-import.mjs'),
    [
      'import { ValueTag } from "@bilig/protocol";',
      'import { WorkPaper } from "@bilig/headless";',
      'import { exportXlsx, importXlsx } from "@bilig/excel-import";',
      '',
      'const snapshot = {',
      '  version: 1,',
      '  workbook: {',
      '    name: "Structured Financial Model",',
      '    metadata: {',
      '      definedNames: [',
      '        { name: "Currency", value: { kind: "cell-ref", sheetName: "Constants", address: "F7" } },',
      '        { name: "Start_Year", value: { kind: "cell-ref", sheetName: "Constants", address: "B10" } },',
      '      ],',
      '      tables: [',
      '        {',
      '          name: "tblPFS",',
      '          sheetName: "Constants",',
      '          startAddress: "H6",',
      '          endAddress: "O7",',
      '          columnNames: ["Period", "Revenue", "CoGS", "Gross Profit", "Opex", "EBITDA", "Tax", "Cash"],',
      '          headerRow: true,',
      '          totalsRow: false,',
      '        },',
      '        {',
      '          name: "tblActuals",',
      '          sheetName: "Imports",',
      '          startAddress: "A6",',
      '          endAddress: "D8",',
      '          columnNames: ["Account", "Value", "Year", "Period"],',
      '          headerRow: true,',
      '          totalsRow: false,',
      '        },',
      '        {',
      '          name: "Table3",',
      '          sheetName: "PlayerData",',
      '          startAddress: "G3",',
      '          endAddress: "G5",',
      '          columnNames: ["Height"],',
      '          headerRow: true,',
      '          totalsRow: false,',
      '        },',
      '      ],',
      '    },',
      '  },',
      '  sheets: [',
      '    {',
      '      id: 1,',
      '      name: "Constants",',
      '      order: 0,',
      '      cells: [',
      '        { address: "B10", value: 2012 },',
      '        { address: "F7", value: "USD" },',
      '        { address: "F9", formula: "Currency & \\"  000s\\"" },',
      '        { address: "H6", value: "Period" },',
      '        { address: "I6", value: "Revenue" },',
      '        { address: "J6", value: "CoGS" },',
      '        { address: "K6", value: "Gross Profit" },',
      '        { address: "L6", value: "Opex" },',
      '        { address: "M6", value: "EBITDA" },',
      '        { address: "N6", value: "Tax" },',
      '        { address: "O6", value: "Cash" },',
      '        { address: "H7", formula: "ROW()-ROW(tblPFS[#Headers])" },',
      '      ],',
      '    },',
      '    {',
      '      id: 2,',
      '      name: "Imports",',
      '      order: 1,',
      '      cells: [',
      '        { address: "A6", value: "Account" },',
      '        { address: "B6", value: "Value" },',
      '        { address: "C6", value: "Year" },',
      '        { address: "D6", value: "Period" },',
      '        { address: "A7", value: "Revenue" },',
      '        { address: "B7", value: 100 },',
      '        { address: "C7", value: 2011 },',
      '        { address: "D7", formula: "tblActuals[[#This Row],[Year]]-Start_Year+1" },',
      '        { address: "A8", value: "Revenue" },',
      '        { address: "B8", value: 125 },',
      '        { address: "C8", value: 2012 },',
      '        { address: "D8", formula: "tblActuals[[#This Row],[Year]]-Start_Year+1" },',
      '        { address: "F10", formula: "SUM(tblActuals[Value])" },',
      '      ],',
      '    },',
      '    {',
      '      id: 3,',
      '      name: "PlayerData",',
      '      order: 2,',
      '      cells: [',
      '        { address: "G3", value: "Height" },',
      '        { address: "G4", value: "5\'7" },',
      '        { address: "G5", value: "5\'9" },',
      '        { address: "M4", formula: "SUM(LEFT(Table3[[#This Row],[Height]],1), RIGHT(Table3[[#This Row],[Height]], LEN(Table3[[#This Row],[Height]])-2)/12)" },',
      '        { address: "M5", formula: "SUM(LEFT(Table3[[#This Row],[Height]],1), RIGHT(Table3[[#This Row],[Height]], LEN(Table3[[#This Row],[Height]])-2)/12)" },',
      '      ],',
      '    },',
      '  ],',
      '};',
      '',
      'const imported = importXlsx(exportXlsx(snapshot), "structured-financial-model.xlsx");',
      'const importedConstants = imported.snapshot.sheets.find((sheet) => sheet.name === "Constants");',
      'const importedImports = imported.snapshot.sheets.find((sheet) => sheet.name === "Imports");',
      'const importedPlayerData = imported.snapshot.sheets.find((sheet) => sheet.name === "PlayerData");',
      'const translatedStructuredRefs =',
      '  !importedConstants?.cells.find((cell) => cell.address === "H7")?.formula?.includes("tblPFS[#Headers]") &&',
      '  !importedImports?.cells.find((cell) => cell.address === "D7")?.formula?.includes("[[#This Row],[Year]]") &&',
      '  !importedImports?.cells.find((cell) => cell.address === "F10")?.formula?.includes("tblActuals[Value]") &&',
      '  !importedPlayerData?.cells.find((cell) => cell.address === "M4")?.formula?.includes("Table3[[#This Row],[Height]]");',
      'const workbook = WorkPaper.buildFromSnapshot(imported.snapshot, { maxRows: 20, maxColumns: 16, useColumnIndex: true });',
      'const constantsId = workbook.getSheetId("Constants");',
      'const importsId = workbook.getSheetId("Imports");',
      'const playerDataId = workbook.getSheetId("PlayerData");',
      'if (constantsId === undefined || importsId === undefined || playerDataId === undefined) throw new Error("Imported XLSX sheets are missing");',
      'const read = (sheet, row, col) => workbook.getCellValue({ sheet, row, col });',
      'const currencyLabel = read(constantsId, 8, 5);',
      'const headerPeriod = read(constantsId, 6, 7);',
      'const firstPeriod = read(importsId, 6, 3);',
      'const secondPeriod = read(importsId, 7, 3);',
      'const totalValue = read(importsId, 9, 5);',
      'const heightFeet = read(playerDataId, 3, 12);',
      'if (!translatedStructuredRefs || currencyLabel.tag !== ValueTag.String || headerPeriod.tag !== ValueTag.Number || firstPeriod.tag !== ValueTag.Number || secondPeriod.tag !== ValueTag.Number || totalValue.tag !== ValueTag.Number || heightFeet.tag !== ValueTag.Number) {',
      '  throw new Error(`Unexpected XLSX import values: ${JSON.stringify({ translatedStructuredRefs, currencyLabel, headerPeriod, firstPeriod, secondPeriod, totalValue, heightFeet })}`);',
      '}',
      'console.log(JSON.stringify({',
      '  currencyLabel: currencyLabel.value,',
      '  headerPeriod: headerPeriod.value,',
      '  heightFeet: heightFeet.value,',
      '  firstPeriod: firstPeriod.value,',
      '  secondPeriod: secondPeriod.value,',
      '  totalValue: totalValue.value,',
      '  translatedStructuredRefs,',
      '}));',
      '',
    ].join('\n'),
  )
}
