import { describe, expect, it } from "vitest";
import {
  WORKBOOK_AGENT_TOOL_NAMES,
  isWorkbookAgentToolName,
  normalizeWorkbookAgentToolName,
} from "../workbook-agent-tool-names.js";

describe("workbook agent tool names", () => {
  it("uses clean unprefixed canonical tool names", () => {
    expect(WORKBOOK_AGENT_TOOL_NAMES.readWorkbook).toBe("read_workbook");
    expect(WORKBOOK_AGENT_TOOL_NAMES.listSheets).toBe("list_sheets");
    expect(WORKBOOK_AGENT_TOOL_NAMES.getSheetView).toBe("get_sheet_view");
    expect(WORKBOOK_AGENT_TOOL_NAMES.getUsedRange).toBe("get_used_range");
    expect(WORKBOOK_AGENT_TOOL_NAMES.getCurrentRegion).toBe("get_current_region");
    expect(WORKBOOK_AGENT_TOOL_NAMES.startWorkflow).toBe("start_workflow");
    expect(WORKBOOK_AGENT_TOOL_NAMES.listNamedRanges).toBe("list_named_ranges");
    expect(WORKBOOK_AGENT_TOOL_NAMES.listTables).toBe("list_tables");
    expect(WORKBOOK_AGENT_TOOL_NAMES.listPivots).toBe("list_pivots");
    expect(WORKBOOK_AGENT_TOOL_NAMES.listDataValidationRules).toBe("list_data_validation_rules");
    expect(WORKBOOK_AGENT_TOOL_NAMES.getConditionalFormats).toBe("get_conditional_formats");
    expect(WORKBOOK_AGENT_TOOL_NAMES.getComments).toBe("get_comments");
    expect(WORKBOOK_AGENT_TOOL_NAMES.setFormula).toBe("set_formula");
    expect(WORKBOOK_AGENT_TOOL_NAMES.getRowMetadata).toBe("get_row_metadata");
    expect(WORKBOOK_AGENT_TOOL_NAMES.getColumnMetadata).toBe("get_column_metadata");
    expect(WORKBOOK_AGENT_TOOL_NAMES.createNamedRange).toBe("create_named_range");
    expect(WORKBOOK_AGENT_TOOL_NAMES.createTable).toBe("create_table");
    expect(WORKBOOK_AGENT_TOOL_NAMES.createPivotTable).toBe("create_pivot_table");
    expect(WORKBOOK_AGENT_TOOL_NAMES.createDataValidation).toBe("create_data_validation");
    expect(WORKBOOK_AGENT_TOOL_NAMES.updateDataValidation).toBe("update_data_validation");
    expect(WORKBOOK_AGENT_TOOL_NAMES.removeDataValidation).toBe("remove_data_validation");
    expect(WORKBOOK_AGENT_TOOL_NAMES.addConditionalFormat).toBe("add_conditional_format");
    expect(WORKBOOK_AGENT_TOOL_NAMES.updateConditionalFormat).toBe("update_conditional_format");
    expect(WORKBOOK_AGENT_TOOL_NAMES.removeConditionalFormat).toBe("remove_conditional_format");
    expect(WORKBOOK_AGENT_TOOL_NAMES.addComment).toBe("add_comment");
    expect(WORKBOOK_AGENT_TOOL_NAMES.replyComment).toBe("reply_comment");
    expect(WORKBOOK_AGENT_TOOL_NAMES.resolveComment).toBe("resolve_comment");
    expect(WORKBOOK_AGENT_TOOL_NAMES.deleteComment).toBe("delete_comment");
    expect(WORKBOOK_AGENT_TOOL_NAMES.addNote).toBe("add_note");
    expect(WORKBOOK_AGENT_TOOL_NAMES.updateNote).toBe("update_note");
    expect(WORKBOOK_AGENT_TOOL_NAMES.deleteNote).toBe("delete_note");
    expect(WORKBOOK_AGENT_TOOL_NAMES.createSheet).toBe("create_sheet");
    expect(WORKBOOK_AGENT_TOOL_NAMES.deleteSheet).toBe("delete_sheet");
    expect(WORKBOOK_AGENT_TOOL_NAMES.insertRows).toBe("insert_rows");
    expect(WORKBOOK_AGENT_TOOL_NAMES.deleteColumns).toBe("delete_columns");
    expect(WORKBOOK_AGENT_TOOL_NAMES.setFilter).toBe("set_filter");
  });

  it("normalizes legacy prefixed tool names for compatibility", () => {
    expect(normalizeWorkbookAgentToolName("bilig_read_workbook")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.readWorkbook,
    );
    expect(normalizeWorkbookAgentToolName("bilig.read_workbook")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.readWorkbook,
    );
    expect(normalizeWorkbookAgentToolName("bilig_start_workflow")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.startWorkflow,
    );
    expect(normalizeWorkbookAgentToolName("bilig_list_sheets")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.listSheets,
    );
    expect(normalizeWorkbookAgentToolName("bilig.get_used_range")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.getUsedRange,
    );
    expect(normalizeWorkbookAgentToolName("bilig_set_formula")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.setFormula,
    );
    expect(normalizeWorkbookAgentToolName("bilig_list_named_ranges")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.listNamedRanges,
    );
    expect(normalizeWorkbookAgentToolName("bilig.list_tables")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.listTables,
    );
    expect(normalizeWorkbookAgentToolName("bilig_list_pivots")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.listPivots,
    );
    expect(normalizeWorkbookAgentToolName("bilig.list_data_validation_rules")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.listDataValidationRules,
    );
    expect(normalizeWorkbookAgentToolName("bilig_get_conditional_formats")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.getConditionalFormats,
    );
    expect(normalizeWorkbookAgentToolName("bilig.get_comments")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.getComments,
    );
    expect(normalizeWorkbookAgentToolName("bilig.update_named_range")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.updateNamedRange,
    );
    expect(normalizeWorkbookAgentToolName("bilig_create_table")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.createTable,
    );
    expect(normalizeWorkbookAgentToolName("bilig_create_data_validation")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.createDataValidation,
    );
    expect(normalizeWorkbookAgentToolName("bilig.update_data_validation")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.updateDataValidation,
    );
    expect(normalizeWorkbookAgentToolName("bilig.remove_data_validation")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.removeDataValidation,
    );
    expect(normalizeWorkbookAgentToolName("bilig_add_conditional_format")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.addConditionalFormat,
    );
    expect(normalizeWorkbookAgentToolName("bilig.update_conditional_format")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.updateConditionalFormat,
    );
    expect(normalizeWorkbookAgentToolName("bilig.remove_conditional_format")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.removeConditionalFormat,
    );
    expect(normalizeWorkbookAgentToolName("bilig_add_comment")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.addComment,
    );
    expect(normalizeWorkbookAgentToolName("bilig.reply_comment")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.replyComment,
    );
    expect(normalizeWorkbookAgentToolName("bilig_resolve_comment")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.resolveComment,
    );
    expect(normalizeWorkbookAgentToolName("bilig.delete_comment")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.deleteComment,
    );
    expect(normalizeWorkbookAgentToolName("bilig_add_note")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.addNote,
    );
    expect(normalizeWorkbookAgentToolName("bilig.update_note")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.updateNote,
    );
    expect(normalizeWorkbookAgentToolName("bilig_delete_note")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.deleteNote,
    );
    expect(normalizeWorkbookAgentToolName("bilig.delete_pivot_table")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.deletePivotTable,
    );
    expect(normalizeWorkbookAgentToolName("bilig_get_row_metadata")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.getRowMetadata,
    );
    expect(normalizeWorkbookAgentToolName("bilig_insert_rows")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.insertRows,
    );
    expect(normalizeWorkbookAgentToolName("bilig_delete_sheet")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.deleteSheet,
    );
    expect(normalizeWorkbookAgentToolName("bilig.delete_columns")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.deleteColumns,
    );
    expect(normalizeWorkbookAgentToolName("bilig.clear_sort")).toBe(
      WORKBOOK_AGENT_TOOL_NAMES.clearSort,
    );
    expect(isWorkbookAgentToolName("bilig_search_workbook")).toBe(true);
    expect(isWorkbookAgentToolName("insert_rows")).toBe(true);
    expect(isWorkbookAgentToolName("set_filter")).toBe(true);
    expect(isWorkbookAgentToolName("search_workbook")).toBe(true);
    expect(isWorkbookAgentToolName("list_sheets")).toBe(true);
    expect(isWorkbookAgentToolName("get_current_region")).toBe(true);
    expect(isWorkbookAgentToolName("set_formula")).toBe(true);
    expect(isWorkbookAgentToolName("list_named_ranges")).toBe(true);
    expect(isWorkbookAgentToolName("list_tables")).toBe(true);
    expect(isWorkbookAgentToolName("list_pivots")).toBe(true);
    expect(isWorkbookAgentToolName("list_data_validation_rules")).toBe(true);
    expect(isWorkbookAgentToolName("get_conditional_formats")).toBe(true);
    expect(isWorkbookAgentToolName("get_comments")).toBe(true);
    expect(isWorkbookAgentToolName("get_row_metadata")).toBe(true);
    expect(isWorkbookAgentToolName("get_column_metadata")).toBe(true);
    expect(isWorkbookAgentToolName("create_named_range")).toBe(true);
    expect(isWorkbookAgentToolName("create_table")).toBe(true);
    expect(isWorkbookAgentToolName("create_data_validation")).toBe(true);
    expect(isWorkbookAgentToolName("update_data_validation")).toBe(true);
    expect(isWorkbookAgentToolName("remove_data_validation")).toBe(true);
    expect(isWorkbookAgentToolName("add_conditional_format")).toBe(true);
    expect(isWorkbookAgentToolName("update_conditional_format")).toBe(true);
    expect(isWorkbookAgentToolName("remove_conditional_format")).toBe(true);
    expect(isWorkbookAgentToolName("add_comment")).toBe(true);
    expect(isWorkbookAgentToolName("reply_comment")).toBe(true);
    expect(isWorkbookAgentToolName("resolve_comment")).toBe(true);
    expect(isWorkbookAgentToolName("delete_comment")).toBe(true);
    expect(isWorkbookAgentToolName("add_note")).toBe(true);
    expect(isWorkbookAgentToolName("update_note")).toBe(true);
    expect(isWorkbookAgentToolName("delete_note")).toBe(true);
    expect(isWorkbookAgentToolName("delete_pivot_table")).toBe(true);
  });
});
